### ISSUE TITLE
Grupo de estudos HTML

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#1]
Formação de grupo para estudar HTML

**Comment by SoullPower** [comment]
Pode me por nessa :D

**Comment by idlua** [comment]
@SoullPower tudo certo?
Me fala uma coisa, já aprendeu alguma coisa de HTML ou é o primeiro contato? Como ainda não tem muita gente por aqui dependendo do seu nível posso te dar alguns toques pra não ficar parado.

**Comment by SoullPower** [comment]
Sim sim ja posso dizer que tenho conhecimento intermediário em HTML, mas gostaria sim de uns toque pra ir fazendo algo, ficar parado é tenso =/

**Comment by woliveiras** [comment]
Da pra passar uns layouts/desafios pro @SoullPower ein... Que tal @idlua?

**Comment by SoullPower** [comment]
Opa, mas já vou logo dizendo que tenho sérias dificuldades com posicionamento em CSS =/

**Comment by idlua** [comment]
@SoullPower ah, logo você desenrola! Me fala alguma forma de contato teu, te chamo lá e a gente troca uma ideia. Se não vamos ficar dando spam de código aqui a toda momento. :b

**Comment by woliveiras** [comment]
Relaxa pow... A intenção é praticar mesmo! :smile:

**Comment by SoullPower** [comment]
Vou mandar meu perfil do facebook e meu número do Whattsapp

Facebook: https://www.facebook.com/claudio.junior.3979

Whattsapp: (19) 98322-0873

**Comment by woliveiras** [comment]
Eita, evita postar número de celular aqui @SoullPower... Vou até deixar avisado no README. Isso é um perigo pra sua segurança... Fica exposto a alguém que possa passar trote ou mesmo golpes.

**Comment by SoullPower** [comment]
Pronto, desculpe

**Comment by woliveiras** [comment]
Que isso mano, sem problemas. É que vai quee.... ;D

**Comment by banduka** [comment]
Let's go

**Comment by LarissaAbreu** [comment]
Opa... To dentro dessa também :)

**Comment by woliveiras** [comment]
Galera, com base nas ideias do pessoal nas outras issues, criamos um time no slack.

Cada grupo de estudos pode criar um canal lá para conversar os assuntos de vocês.

Caso não queiram, não são obrigados a usar esse Slack viu, podem fazer como acharem melhor. :)

 https://ctgroups.herokuapp.com/

**Comment by davidasimoes** [comment]
Posso participar tbm?

**Comment by idlua** [comment]
@davidasimoes pode sim, ainda não formou um grupo de 5.

**Comment by Stoque** [comment]
Pode me botar nesse também

**Comment by woliveiras** [comment]
\o/

**Comment by woliveiras** [comment]
\o/

**Comment by Josue23** [comment]
Bota eu no grupo também please

Manjo um pouquinho de Hrml
Só me enrolo um pouco com Css

On Monday, 28 March 2016, William Oliveira <notifications@github.com> wrote:

> \o/
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/sobre/issues/1#issuecomment-202647431>
>


--

**Comment by WendellAdriel** [comment]
Grupo fechado, irei abrir a issue do grupo formado!!!! :wink:
