### ISSUE TITLE
Felipe Orlando: Knowledge is power.

### ISSUE THREAD

**Issue by felipeorlando** [training-center/sobre#1]
Fala, galera!

Meu nome é **Felipe Orlando** e trabalho com desenvolvimento web desde quando não podia chamar isso de trabalho, mas sim como "_puramente hobbie_", quando comecei a me aventurar em PHP e JS para fazer um blog sobre **Harry Potter**.

Hoje em dia, meu prazer é em **não programar** e fazer as coisas acontecerem. Criar do zero uma solução incrível e transformar algo incrível em...

<div align="center"><img src="https://media.giphy.com/media/Qh6NZWsFx1G1O/giphy.gif"></div>

Pra mim, focar no resultado final (experiência do usuário, performance, disponibilidade, segurança) e em clean-code (arquitetura, DRY, SOLID) é muito mais importante do que ficar se preocupando com a linguagem e/ou reinventar a roda.

Moro em São José dos Campos, SP. Trabalho atualmente como desenvolvedor full-stack (muito mais pro lado back-end) com tecnologias como Ruby, Rails, PHP, Laravel, JS, Angular. Estou em processo de transição de empresas, em breve dou um parecer sobre. 👍 

Meu objetivo para com o Centro de Treinamento é fomentar o conteúdo para iniciantes e poder criar maneiras para que os mesmos possam ter um interação maior com outros.

Obviamente, terei o maior prazer de ajudar qualquer pessoa, tudo o que estiver ao meu alcance. 

É isso aí, bora ensinar/aprender! 😄

**Now, say my name.**
⚡ **[GitHub](https://github.com/fbeegle)** | **[LinkedIn](https://www.linkedin.com/in/fbeegle)**

**Comment by woliveiras** [comment]
Fala @fbeegle! 

@training-center/moderators, o Felipe entrou em contato comigo por email para auxiliar na produção de [conteúdo](https://github.com/training-center/materials) para a galera que estuda nos Grupos. :smile:

**Comment by danilovaz** [comment]
@fbeegle bem vindo conterrâneo!

**Comment by LarissaAbreu** [comment]
Opa, @fbeegle. Seja muito bem vindo! Vai ser um up e tanto nos grupos.

Se quiser interagir legal com a galera entra lá no slack do CT que é onde a gente conversa mais (ou tenta rs) :bowtie:

**Comment by woliveiras** [comment]
Já mandei o invite para a Org e coloquei no time! \o/

**Comment by felipeorlando** [comment]
@woliveiras é nozes!

@danilovaz viva sanja! 

@LarissaAbreu tâmo lá!
