### ISSUE TITLE
Camisetas do Training Center

### ISSUE THREAD

**Issue by lflimeira** [training-center/sobre#10]
Foi levantada a ideia de criar camisetas do Training Center, para o pessoal usar e poder divulgar ainda mais o projeto.

Pensando nisso, criamos essa issue para que todos possam dar ideias de como pode funcionar a logística, indicarem lugares para fazer as camisetas, opinarem sobre a arte e tudo relacionado a isso.

Minha ideia inicial junto com o @woliveiras é de separar por regiões, já que pessoas de todo o Brasil e até mesmo do mundo todo, fazem parte do TC.

Bora discutir essa ideia e fazer acontecer galera :)

**Comment by mtferreira** [comment]
quando vc fala separação por região, vc tá falando de tipo sudeste, nordeste, sul? ou algo mais específico?

**Comment by lflimeira** [comment]
@mtferreira não definimos nada, poderia ser por estados, e fazer uma padronização de design e com base nesse padrão cada região poderia personalizar dando a sua cara ao TC, o que acha da ideia?

**Comment by giovannicruz97** [comment]
Eu sugiro uma camiseta preta com detalhes em laranja. Quanto a região, poderíamos definir por capitais e subregiões. Por exemplo: Região de São Paulo (Capital) e Região do Vale do Paraíba (Subregião)

**Comment by lflimeira** [comment]
@giovannicruz97  o problema de ficar tão dividido é que o valor das camisetas pode acabar ficando alto, e precisaríamos de várias pessoas para fazer essa quantidade de design para as diferentes regiões.

**Comment by woliveiras** [comment]
Muito dividido pode ser ruim nessa primeira parte, galera.

O esquema é fazer por estado, pois ai rola a atenção especial com cada estado (logo personalizado, cores personalizadas, etc) e fica mais fácil de gerenciar.

Quando tiver muita gente engajada nesse tipo de coisa (e até alguns líderes locais) ai da pra fazer bem mais dividido. 😄

**Comment by mtferreira** [comment]
tb acho que pelo estado fica melhor, o esquema de região mais específica vai reduzir bastante a quantidade de pessoas nesses "grupos", o que pode fazer possivelmente a camisa ficar inviável em termos de preço, como o @lflimeira msm falou.

**Comment by adeonir** [comment]
A ideia das camiseta é muito boa, mas isso de cada região personalizar a sua? Sei lá...

Cadê o style guide que a gente usa pra deixar o código padronizado? Devemos manter isso também na identidade visual do projeto...

Nessa primeira fase, acho que deveríamos procurar uma empresa parceira, uma [Camiseteria](https://www.camiseteria.com/) da vida, pra produzir e distribuir.

**Comment by lflimeira** [comment]
"Devemos manter isso também na identidade visual do projeto..." Concordo com vc @adeonir foi isso que quis dizer com criar uma padronização, só n sabia que já existia uma kkkkkk

Quanto ao que eu falei de personalizar, era para dar a oportunidade de cada região levar um pouco da cultura dela na camisa e diversificar. Mas como falei, foi uma ideia inicial a ser discutida, se ficar melhor podemos fazer apenas um modelo inicialmente.

Quanto a empresa acho uma boa ideia, estava com a ideia de mandar fazer e vender as camisetas a preço de custo, mas se tiver algum contato do tipo acho que seria legal. :)

**Comment by adeonir** [comment]
Já existe um repositório sobre a [identidade visual](https://github.com/training-center/brand-guide).

Mandar fazer e vender a preço de custo seria o ideal pra nós, só ver uma maneira de fazer isso sem que 1 só fique responsável pelo pagamento, estoque e despacho das camisetas. Por isso achei melhor envolver uma empresa, que já tem toda essa logística.

Outra opção seria preparar um kit para download com as estampas e cada um manda produzir a sua.

**Comment by lflimeira** [comment]
Ahhh boa ideia, acho uma boa saída, me agrada mais a opção de envolver uma outra empresa, mas a segunda opção tbm parece uma boa saída se não conseguir achar uma empresa parceira.

Mas acho que para começar seria legal ter uma arte, tem alguém que manja fazer isso que pode nos ajudar?

**Comment by adeonir** [comment]
o/

Só falta tempo =(

**Comment by anony000** [comment]
Galera eu estudo design e já fiz algumas estampas se quiserem posso dar uma força.

**Comment by adeonir** [comment]
Opa, @anony000 manda ae...

**Comment by cotts** [comment]
Pessoal... Como esse projeto ninguém está tocando, vou começar a dar uma olhada... vou abrir um canal no slack e ir passando informações...

**Comment by woliveiras** [comment]
Perfeito, manooo

**Comment by woliveiras** [comment]
Galera, o @cotts vai tacar pau nessa ideia e podemos usar a issue #16 para discutir sobre.
