### ISSUE TITLE
Grupo de estudos WordPress 

### ISSUE THREAD

**Issue by cvalentefilho** [training-center/sobre#10]
Formação de grupo para estudar WordPress

**Comment by heliomsolivas** [comment]
eu topo

**Comment by woliveiras** [comment]
Seria da hora você passar os esquemas do WP-API pra galera ein @cvalentefilho :smile:

**Comment by LarissaAbreu** [comment]
To dentro xD

**Comment by marquinhusgoncalves** [comment]
**Tô dentro**

**Comment by heliomsolivas** [comment]
se alguém manjar eu tava procurando material sobre wp-settings utilizando algum framework ou na mão mesmo .-.

**Comment by cvalentefilho** [comment]
@heliomsolivas o que você queria com wp-settings?

**Comment by heliomsolivas** [comment]
@cvalentefilho criar o meu próprio wp-settings, me indicaram alguns fw mas fiquei meio perdido

**Comment by vicainelli** [comment]
Quero.

**Comment by WendellAdriel** [comment]
Grupo fechado, irei abrir a issue do grupo formado!!!! :wink:
