### ISSUE TITLE
Encontro informal do Training Center no [RS]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#11]
Essa issue servirá para marcar um encontro presencial e informal do Training Center no RS para tratar de como podem ser os próximos encontros e para as pessoas se conhecerem.

**Comment by alinebastos** [comment]
Pessoal de Porto Alegre, quem topa um encontrinho? o/

**Comment by jonatanvianna** [comment]
Opa eae! Bora

**Comment by imingrid** [comment]
Eu vou 🤘

**Comment by adeonir** [comment]
Eu sei chegar até Porto Alegre 🙄 
Não conheço muito, mas vambora...

**Comment by AdrianoBiolchi** [comment]
Eu sei chegar até Porto Alegre²
Também não conheço muito mas se fechar as datas, boraaa!

**Comment by kamysa** [comment]
sou do RJ, mas gostei da ideia. rsrs

**Comment by alinebastos** [comment]
Pessoal, quero criar o nosso grupo no [Meetup](https://www.meetup.com/), como o pessoal de SP já fez, pra gente se agilizar por lá.
Masss.. apesar de ter a opção gratuita, tem que colocar os dados do cartão de crédito, coisa que eu não possuo no momento.
Alguém se habilitaria de criar lá o grupo Training Center RS?

**Comment by alinebastos** [comment]
Cade vcs?

**Comment by adeonir** [comment]
Oi @alinebastos, vou dar uma olhada nisso aí no fds, posso usar meu cartão.

**Comment by benguimaraes** [comment]
Vamos!

**Comment by FelipeSGAndrade** [comment]
Como ta a organização desse encontro? Tô muuuuito interessado

**Comment by alinebastos** [comment]
@adeonir (consegui te marcar \o/) chegou a ver o site do meetup?
Vamos organizar esse encontro :D

**Comment by FelipeSGAndrade** [comment]
aguardando a resposta dele, mas, se precisar, eu consigo criar também

**Comment by FelipeSGAndrade** [comment]
https://www.meetup.com/pt-BR/Training-Center-RS

**Comment by woliveiras** [comment]
Isso tudo é muito lindo!

**Comment by woliveiras** [comment]
Fala, galera!

Esse meetup já está rodando, então vou fechar a issue e qualquer coisa é só abrir outras no nosso repositório meetups.
