### ISSUE TITLE
Encontro informal do Training Center em [SC]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#12]
Essa issue servirá para marcar um encontro presencial e informal do Training Center em SC para tratar de como podem ser os próximos encontros e para as pessoas se conhecerem.

**Comment by ismaelirc** [comment]
Existe alguma cidade específica em vista?

**Comment by woliveiras** [comment]
Ainda não @ismaelirc 

Essa issue servirá para definir onde vai ser. 😄

**Comment by ismaelirc** [comment]
Bacana, então sugiro Blumenau :D

**Comment by cotts** [comment]
Floripa!

**Comment by anony000** [comment]
Blumenau seria uma boa

**Comment by eduardoBenn** [comment]
Opa, Blumenau me agrada muito também! =D

**Comment by cleitonsouza** [comment]
O interessante de ser em Blumenau é que fica no meio do caminho para todas as pessoas do estado, então seria o ideal. A não ser que se perceba que a maioria das pessoas são do litoral, dai fica melhor em Floripa mesmo.

**Comment by woliveiras** [comment]
Fala, galera! 

Bora criar esse Meetup ai!? 

Segue esse esquema: https://github.com/training-center/meetups#como-posso-iniciar-um-meetup

Vou fechar a issue pra gente centralizar tudo o que for de meetups lá no outro repo.
