### ISSUE TITLE
Vamos pensar um pouco..

### ISSUE THREAD

**Issue by idlua** [training-center/sobre#12]
Criei essa issue nessa vibe Telecurso 2000 pra discutirmos algumas formas de nos organizarmos para estudar.

O @woliveiras  já deu boas sugestões na [md de descrição do projeto] (https://github.com/training-center/sobre), como organizar grupos de no mínimo 5 pessoas e criar times no Slack.

A gente poderia também, continuamente à essa ideia, criar uma issue específica para cada grupo aqui, dando um nome de identificação para não misturar as coisas, e todas as maiores questões dos membros de um determinado grupo seriam tratadas nela (issue do grupo).

Coisas como:
- Postar nossas dúvidas;
- Definirmos horários para estudarmos juntos;
- Compartilhar nossas evoluções no aprendizado;
- Dar algumas dicas sobre os mais variados assuntos;
- e etc.

## Por que criar issues para cada grupo?

Este é um projeto que sem dúvida irá perdurar por bastante tempo. Nossas discussões aqui poderão no futuro servir de acervo para outros grupos que virão. Então nossas discussões, dicas, dúvidas solucionadas e tudo o mais que discutirmos poderiam ser aproveitadas por outros.
Essa é basicamente a ideia da galera do [fórum do Front-End Brasil] (https://github.com/frontendbr/forum) e que tem dado muito certo.

O que acham?

**Comment by woliveiras** [comment]
Muito foda esses pontos levantados @idlua!

Cara, acho que um esquema como o que falou vira bem. A galera pode definir um nome pro seu grupo e abrirem essa issue. Seria algo bem interessante até pra todo mundo acompanhar juntos o desenvolvimento da galera.

Inicialmente, pensei só em deixar o espaço pra galera abrir as issues e montar os grupos, mas achei interessante deixar um registro do que está acontecendo aqui pros próximos grupos se espelharem. Da hora!

Vou atualizar o README!!! ;D

**Comment by woliveiras** [comment]
Da uma olhada em como ficou agora @idlua

**Comment by idlua** [comment]
@woliveiras show!

**Comment by woliveiras** [comment]
\o/
