### ISSUE TITLE
Encontro informal do Training Center no [DF]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#13]
Essa issue servirá para marcar um encontro presencial e informal do Training Center no DF para tratar de como podem ser os próximos encontros e para as pessoas se conhecerem.

**Comment by neuraman** [comment]
Opa pessoal que quiser marcar algo... contem comigo!

**Comment by rberts** [comment]
Opa! Eu já ia criar aqui, mesmo achando que não ia ter quase ninguém do DF, haha! :D
To dentro também.

**Comment by icarofigueiredo** [comment]
Tamo junto! Só falar a data!

**Comment by gnbezerra** [comment]
Opa, cheguei agora no Training Center, mas acho que poderíamos ressuscitar a ideia do encontro no DF!

A issue é um pouco antiga, então quem do DF participaria atualmente? Bora agitar isso aqui!

**Comment by woliveiras** [comment]
Bora movimentar esse negócio, @gnbezerra! 

Já está no nosso Slack?

Lá o engajamento é maior e o pessoal vai te responder mais rápido.

**Comment by gnbezerra** [comment]
Tô sim, vou perguntar por lá então! Se conseguirmos combinar algo copio a informação para cá.

**Comment by woliveiras** [comment]
Perfeito! \o/

**Comment by woliveiras** [comment]
Fala, galera!  

Bora criar esse Meetup ai!? 

Segue esse esquema: https://github.com/training-center/meetups#como-posso-iniciar-um-meetup

Vou fechar a issue pra gente centralizar tudo o que for de meetups lá no outro repo.
