### ISSUE TITLE
Encontro informal do Training Center em [SP]

### ISSUE THREAD

**Issue by manzoliric** [training-center/sobre#14]
Essa issue servirá para marcar um encontro presencial e informal do Training Center em SP para tratar de como podem ser os próximos encontros e para as pessoas se conhecerem.

**Comment by hjdesigner** [comment]
Topo o/

**Comment by matheusggds** [comment]
Opa, to on!

**Comment by hjdesigner** [comment]
@richmanzoli Se tem uma ideia de como vai ser isso? Tipo meetup ou uma coisa mais descotraida tipo devber?

**Comment by manzoliric** [comment]
Bom, eu gostaria algo mais Devbeer haha mas ai é com o pessoal, o que acham melhor?

**Comment by vinirossi** [comment]
Não sei como funciona esse negócio de github ainda, mas acho que é só escrever por aqui neh?
Enfim, eu topo essa para. Não bebo cerveja, mas pego um refri ou suco ou água.

**Comment by hjdesigner** [comment]
@vinirossi é assim mesmo kkk. Legal, a ideia de bar fica mais descontraído.

**Comment by hjdesigner** [comment]
@vinirossi é assim mesmo kkk. Legal, a ideia de bar fica mais descontraído.

**Comment by woliveiras** [comment]
Opa, em SP eu vou ein 😄

**Comment by kvnol** [comment]
Tamo junto! :metal:

**Comment by manzoliric** [comment]
Opa, vamos marcar isso ai então, quando seria um dia bom??

**Comment by hjdesigner** [comment]
Primeiro temos que achar um lugar de bacana e de fácil acesso para chegar. O que você acha de 14/06? todo mundo já recebeu e é uma sexta-feira.

**Comment by renanoliveira0** [comment]
Rola criar um grupo no meet up não?

**Comment by lflimeira** [comment]
Galera, poderíamos fazer em um lugar mais central, perto da Paulista por exemplo. Poderíamos fazer um DevBeer mensal o que acham?

Estipulamos um dia todo mês no mesmo lugar, e podemos ir moldando o formato dos eventos (shark bowl, mini apresentações, temas pré estabelecidos), o formato que a galera curtir mais.

Eu gosto do Shark Bowl, se quiserem saber como é, deem uma olhada https://github.com/duodraco/shark-bowl.

**Comment by kvnol** [comment]
Concordo com o @lflimeira em ser na Paulista, fica perto pra todo mundo: pra quem vem do Morumbi/Vila Olímpia e pra quem vem do outro lado ABC e tal.

**Comment by manzoliric** [comment]
Paulista é de boa pra mim, lugar bacana e não é tão longe, bom, vamos criar um Meetup?
E gostei bastante da ideia do Shark Bowl!

**Comment by manzoliric** [comment]
O evento será apenas para encontro, trocar umas ideias, networking ou terá algum assunto específico??

**Comment by lflimeira** [comment]
Opa bora, se quiserem eu conheço um lugar baca, que eu sempre vou fazer reunião lá.
É aonde ocorre um meetup de inglês. [Laje 795 - Telhado do The Hostel Paulista](https://www.google.com/maps/place/R.+Pamplona,+795+-+Jardim+Paulista,+S%C3%A3o+Paulo+-+SP,+01405-001,+Brazil/@-23.5650336,-46.6570997,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce59c61f40d747:0x3df6ad8b2ed86a94!8m2!3d-23.5650336!4d-46.654911?hl=en)

**Comment by lflimeira** [comment]
@richmanzoli  se for shark bowl cada um propõe um assunto pode ser desde carreira até tecnologia especifica.

**Comment by lflimeira** [comment]
O Meetup é gratuito para criar um evento la? Alguém já está criando ?

**Comment by manzoliric** [comment]
Então, é de graça.. mas pede cartão de credito, creio que seja 6 meses gratis.. até 50 membros no meetup, ia criar mais meu cartão está em casa, se ninguem criar, chegando em casa eu crio!

**Comment by woliveiras** [comment]
Uma alternativa ao Meetup.com é o nvite: https://nvite.com/

Não sei se é interessante criar algo pago para a comunidade visto que não temos nenhuma fonte de renda.

Acham interessante montarmos um apoia.se da vida para custear essas coisas?

**Comment by lflimeira** [comment]
Pessoal, fiquei afastado por um tempo, como ficou resolvido? 

@woliveiras  acho que por hora da para levar sem um apoia.se, podemos utilizar essas opções gratuitas.

O apoia.se seria legal quando tiver mais questões que demandam gastos fixos, o que vc acha?

**Comment by woliveiras** [comment]
Concordo @lflimeira

**Comment by manzoliric** [comment]
Fechado, vou pesquisar umas alternativas do meetup e vou criar um evento/encontro nele, tentei no nvite e acho que ele está no beta e tenho que aguardar haha mas vou procurar um e criar e volto aqui!

**Comment by lflimeira** [comment]
Combinado :)

**Comment by lflimeira** [comment]
Eae galera, bora marcar esse encontro, conversei com o dono do bar que eu citei, e ele falou que é tranquilo para marcar o meetup lá.

**Comment by kvnol** [comment]
Seria legal, também, abrir um grupo do Meetup pra cada cidade que fosse sediar. Pra não ficar um grupo com gente do Brasil todo. Ou vocês pensam o contrário? Que seria melhor ter todos os eventos num único espaço.

PS: pensando bem, até seria legal ter toda a comunidade num só grupo do Meetup.

**Comment by woliveiras** [comment]
Seria legal um grupo por localidade mesmo, @kvnol 

Mas estamos tentando evitar custos agora, ai vamos planejar algum esquema legal pra fazer a divulgação e controle de participantes.

Por enquanto vamos sem formalidades, na loucura mesmo pra gente se conhecer, fazer bagunça, sem formato, sem padrão, sem nada. 😂

**Comment by kvnol** [comment]
> Por enquanto vamos sem formalidades, na loucura mesmo pra gente se conhecer, fazer bagunça, sem formato, sem padrão, sem nada. :joy:

Massa! Tamo junto.

**Comment by lflimeira** [comment]
Galera, vamos agitar esse encontro para esse mês ainda, ou começo do mês que vem (antes do BrazilJS)?

Para fazer acontecer podemos marcar aqui mesmo e vamos divulgando. O que acham?

**Comment by lflimeira** [comment]
@woliveiras  @richmanzoli vamos colocar para frente esse encontro? Vamos fechar um dia e agitar a galera de SP, o que acham?

**Comment by manzoliric** [comment]
Opa rapaziada, desculpa, dei uma sumida, muito trabalho haha mas vamos sim!!!! alguem ai com dicas de lugares? algum bar ou local normal? sem gastar dinheiro

**Comment by lflimeira** [comment]
Então eu conheço o  Laje 795 - Telhado do The Hostel Paulista, la vc só paga o que consumir, é perto do metrô e bem centralizado. Posso conversar com eles para ver a disponibilidade, poderíamos já fechar encontros mensais o que acham?

**Comment by lflimeira** [comment]
@richmanzoli  eu estava dando uma olhada no meetup, e eles possuem um plano limitado para começar, mas acho que é mais do que o suficiente. Vou criar lá já @woliveiras. Ai depois podemos criar um texto legal.

**Comment by lflimeira** [comment]
@here https://www.meetup.com/pt-BR/Training-Center-SP/ :smile:

**Comment by Kirmayrtomaz** [comment]
Tô dentro lol

**Comment by khaosdoctor** [comment]
Pessoal, acho que posso ter encontrado um local para nos reunirmos de tempos em tempos.

A empresa aonde trabalho realiza feedbacks com os funcionários ao longo do trimestre, em um desses feedbacks o pessoal, sabendo que estou envolvido em comunidades e tudo mais, me pediu para que eu incluísse mais a comunidade no nosso local de trabalho, pois o objetivo deles é apresentar a empresa aos devs como um local referência de trabalho, pois eles querem se tornar referências em tecnologia.

## Como isso funcionaria

Temos que avisar com antecedência o pessoal lá, então se formos realizar esses meetups com uma certa assiduidade, podem focar isto em mim se for lá! Me disseram que vão providenciar a infra estrutura necessária (comida, bebida e estrutura) para que possamos fazer nossos meetups. 

Basta termos todo o roteiro do que queremos fazer, bem como as datas e quanto tempo vai durar. Se avisarmos com uma antecedência bacana acho que podemos realizar nosso primeiro evento lá! Quem ficar curioso o link está [aqui](https://squidit.com.br)

---

Estive falando com a @FernandaBernardo também, que disse que é possível fazer algo na Elo7 também. Então me veio a ideia de podermos fazer algo itinerante, rodando a cidade toda para que possamos atingir a maior quantidade de membros possíveis de todos os cantos :)

**Comment by lflimeira** [comment]
@khaosdoctor Eu curti a ideia de ser itinerante, e eu topo fazer um primeiro evento onde vc trabalha. 

Poderíamos fazer duas palestras e uma roda de conversas.  Vc acha que consegue marcar para dia 23 agora? 

Se conseguir já marcamos no meetup, e abrimos um call for papers :smile:

**Comment by khaosdoctor** [comment]
Eu acho que para este mês o pessoal ainda não vai conseguir, porque como seria o primeiro contato deles com esse tipo de coisa, seria melhor para eles planejarem um pouco mais. Estou em contato com o pessoal já pra poder ver uma data e definir as ideias de como vai ser.

Ai qualquer coisa eu comento aqui atualizando 😆

**Comment by lflimeira** [comment]
Opa, tranquilo.

Ai quando tiver algo já marcamos lá no meetup :smile:

**Comment by phhoffmann** [comment]
to dentro também! seja onde for ou quando for, rs

**Comment by khaosdoctor** [comment]
@lflimeira Consegui contato com o pessoal e eles me deram carta branca pra vir falar com vocês. Vou te passar os detalhes e já posto aqui os pontos principais

**Comment by lflimeira** [comment]
Opa, demorou @khaosdoctor, assim que tiver uma data, da um toque. Ai podemos colocar no meetup 😄

**Comment by hdamaich** [comment]
Opa comentando para ficar por dentro da thread. Marquem num final de semana, fica mais facil pra quem não é de SP capital ir 💃

**Comment by khaosdoctor** [comment]
O problema @hdamaich é que a maioria das empresas que estão cedendo os espaços só podem durante a semana porque tem gente e tal pra receber :/

**Comment by woliveiras** [comment]
Fala, galera! 

O Meetup está rolando a todo vapor!

Vou fechar a issue e se alguém tiver algo a acrescentar é só levantar no nosso repositório meetups
