### ISSUE TITLE
Encontro informal do Training Center em [CWB]

### ISSUE THREAD

**Issue by marcelabomfim** [training-center/sobre#15]
Essa issue servirá para marcar um encontro presencial e informal do Training Center em Curitiba para tratar de como podem ser os próximos encontros e para as pessoas se conhecerem.

**Comment by ismaelirc** [comment]
\O/

**Comment by aferreira44** [comment]
Tamo junto!

**Comment by fdaciuk** [comment]
\o/

**Comment by IuryChagas** [comment]
_o/

**Comment by mayronceccon** [comment]
=)

**Comment by marcelabomfim** [comment]
E aí, quem tem alguma sugestão de como/onde pode ser o encontro ?

**Comment by fdaciuk** [comment]
Tem dois lugares que eu acho que é tranquilo pra agilizar meetups (a galera de WP normalmente faz lá):
- Aldeia Coworking
- Nex Coworking

Posso trocar uma ideia com a galera que organiza os meetups de WP pra ver quem são os contatos =)

Se alguém tiver algum lugar já encaminhado só avisar :D

**Comment by ismaelirc** [comment]
O Aldeia seria legal, inclusive teve um PHPDay lá na semana passada e a
estrutura deles é bem legal pra encontros

**Comment by marcelabomfim** [comment]
É eu também fui no PHPDay e trabalho com o organizador, posso ver como foi o processo pra agendar lá.
Mas antes do local devíamos pensar em como será o formato do encontro, acho legal ter um pessoal mais experiente pra trocar uma ideia e ao mesmo tempo ter uma galera com a bagagem menor para contar como se vira nesse mundão de Devs.
Já voto em carreira como primeiro tópico. O que me dizem?

**Comment by nandomoreirame** [comment]
:ok_hand:

**Comment by leonardomerlin** [comment]
Fala galera. Parabéns pela iniciativa do encontro. Mudei aqui pra Curitiba em dezembro agora e ainda estou procurando lugares/eventos pra começar a interagir e contribuir com a comunidade.

Achei bacana tópico de **carreira** sugerido pela @marcelabomfim :+1:

**Comment by woliveiras** [comment]
Fala, @marcelabomfim  

Bora criar esse Meetup ai!? 

Segue esse esquema: https://github.com/training-center/meetups#como-posso-iniciar-um-meetup

Vou fechar a issue pra gente centralizar tudo o que for de meetups lá no outro repo.

**Comment by marcelabomfim** [comment]
Hey pessoal, acabei criando o meetup essa semana, ainda não tem nada marcado mas chega aí: https://www.meetup.com/pt-BR/Training-Center-CWB/
Aliás, quem estiver afim de ajudar na organização ou ir preparando uma talk é só falar comigo lá no slack :smiley:

**Comment by maaryhabad** [comment]
Eu quero participar da organização!

Em ter, 14 de nov de 2017 às 13:36, Marcela Bomfim <notifications@github.com>
escreveu:

**Comment by marcelabomfim** [comment]
@maaryhabad vou te mandar mensagem lá no slack pra gente conversar melhor, pode ser ?

**Comment by maaryhabad** [comment]
Pode sim! Eu to fora de casa agora mas assim que puder eu respondo!

Em ter, 14 de nov de 2017 às 14:02, Marcela Bomfim <notifications@github.com>
escreveu:

**Comment by nandomoreirame** [comment]
Tem um Coworking bem legal aqui onde trabalho. [Workshop - Agência & Escola](https://ageworkshop.com.br/), eles estão disponibilizando o espaço aqui pra gente fazer, o que acha @marcelabomfim ?

**Comment by maaryhabad** [comment]
Amei ❤️

Em ter, 14 de nov de 2017 às 14:36, Fernando Moreira <
notifications@github.com> escreveu:

**Comment by ismaelirc** [comment]
Dae, povo. Conseguiram um lugar pra fazer?

Em ter, 14 de nov de 2017 às 14:37, Mariana Beilune Abad <
notifications@github.com> escreveu:

**Comment by erenbrito** [comment]
Ainda não @ismaelirc , mas estamos quase lá!

**Comment by erenbrito** [comment]
Já que essa issue está fechada, vamos continuar o papo aqui https://github.com/training-center/meetups/issues/17
