### ISSUE TITLE
Concurso de design para a camiseta do TC

### ISSUE THREAD

**Issue by lflimeira** [training-center/sobre#16]
Eae galera, tudo bem?

Estamos abrindo um concurso de design para a camiseta do Training Center, com o intuito de dar a oportunidade para as pessoas exporem os seus trabalhos e também termos uma arte bacana para nossas camisetas.

# Como participar

Para participar envie a sua arte até o dia 12/07, após esse período iremos iniciar as votações abertas para todos os integrantes do Training Center. A arte mais votada será utilizada em nossas camisetas.

# Regras

Para evitar problemas, as artes devem ser uma criação original dos participantes, ou seja artes e materiais utilizados de fontes não autorizadas serão retiradas do concurso.

A identidade a seguir está aqui:  https://github.com/training-center/brand-guide

**Comment by felipefernandes** [comment]
Seria legal disponibilizar a logo do TC pro pessoal usar, não?

**Comment by lflimeira** [comment]
@felipefernandes  possuímos um brand guide https://github.com/training-center/brand-guide.

**Comment by woliveiras** [comment]
@cotts

**Comment by khaosdoctor** [comment]
Essa eu quero acompanhar

**Comment by cotts** [comment]
Pessoal, vou fazer um esquema parecido com o dos adesivos, porém vou bolar uns designs para as camisetas e com isso criar um typeform para votação do layout....

**Comment by khaosdoctor** [comment]
Vamos fechar essa issue então @cotts?

**Comment by woliveiras** [comment]
Acredito que podemos fechar por que a votação toda vai rolar no canal #brindes no nosso Slack, @khaosdoctor 

O que acha, @lflimeira?

**Comment by cotts** [comment]
Deixa aberta para poder colocar o typeform com os layouts... pq às vezes pode se perder o link lá no slack..

**Comment by lflimeira** [comment]
Acho que daria para fechar sim... Mandamos a mensagens para todos lá no Slack usando channel e vamos lembrando o pessoal, até pq a galera n costuma ver as issues aqui.

Ou se preferirem podemos criar uma outra issue e fechar essa, pois essa foi criada com o propósito de rolar um concurso e tals, até a data lá no meu primeiro comentário está desatualizada, o pessoal pode bater o olho lá e ver que já foi, aí n vão nem ler até o fim :smile:

**Comment by cotts** [comment]
Justo... blz então...
