### ISSUE TITLE
Criar Slack para CT

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/sobre#16]
Criar uma Team no Slack para o CT e criar um channel para cada grupo formado.

**Comment by WendellAdriel** [comment]
@woliveiras não esquece brother!!! :wink:

**Comment by woliveiras** [comment]
Pra agora!

É bom deixar as issues abertas com os nomes dos grupos pra saber quem está em cada grupo em específico né?

**Comment by woliveiras** [comment]
Feito! https://ctgroups.slack.com/

Vou criar o Badge e o auto invite aqui para o grupo > https://github.com/training-center/sobre/issues/18
