### ISSUE TITLE
Adesivos Training Center

### ISSUE THREAD

**Issue by cotts** [training-center/sobre#17]
Pessoal, estarei orçando adesivos para divulgar o CT nos meetups que participo aqui em SC e também poderei fazer para quem quiser e mandar pelo correio, quem tiver interesse vai respondendo que vou criar uma planilha para controle.

É uma boa escolhermos também o layout do adesivo.

**Comment by khaosdoctor** [comment]
QUERO!

Acho que pode ser o logo, ou então podemos refazer uma identidade visual, pode ser uma boa

**Comment by lucasmarques73** [comment]
Também quero, moro no interior de minas, vê se tem como enviar. meu CEP 37903-506

**Comment by brunorafael8** [comment]
Quero também

**Comment by cotts** [comment]
Pensei nesse logo aqui

https://github.com/training-center/sobre/blob/master/img/logo/logo-circle.png

**Comment by lucasmarques73** [comment]
Achei legal. Será que o pessoal do stickerdev ou nerdstickers não fazem e quem quiser compra deles? Tipo a promoção do DEVNAESTRADA

**Comment by cotts** [comment]
Então... @lucasmarques73 , até dá pra ver, mas ai tem que ver quanto que vai ficar o preço, eu vou fazer um pacote por minha conta pra entregar em um meetup, ai se o pessoal quiser mais acho que sai mais em conta... mas a gente vai vendo...

**Comment by ranosi** [comment]
Cara essa ideia de ver com o stickerdev e/ou nerdstikers é boa heim. Com certeza pegarei.

**Comment by alinebastos** [comment]
Amei a ideia!
Se eu tivesse grana eu comparia uma leva pra distribuir aqui no BrazilJS :)

**Comment by cotts** [comment]
Aqui onde moro tem uma empresa que faz adesivos também.. eu vou ver quanto fica o valor em cada uma e a qualidade... Tenho q levar em conta o valor do frete também... Pegando em mãos aqui, as cidades onde as pessoas morarem perto, dá pra enviar para uma delas e depois irem entregando, ou até por carta registrada individualmente que sai baratinho...

**Comment by jpnathan** [comment]
Quero tbm!

**Comment by 88patota** [comment]
Tb quero xD

**Comment by jamile-dev** [comment]
Eu quero o/
Queria até camisa do CT ahahaha <3

**Comment by anony000** [comment]
Eu quero :v

**Comment by vicainelli** [comment]
Indicação de gráfica.. https://www.paulistacartoes.com.br/

**Comment by lflimeira** [comment]
Opa, eu quero tbm. Dependendo quanto ficar e quanto tempo demorar, eu vou querer uma quantidade razoável para levar para o BrazilJS.

**Comment by cotts** [comment]
Vou orçar semana que vem e já encomendar... deve dar tempo sim...

**Comment by khaosdoctor** [comment]
Dá um toque pra gente se precisar de alguma coisa

**Comment by ericalves** [comment]
Opa! Tbm quero! :D

**Comment by giovannicruz97** [comment]
Eu quero aaaaa

**Comment by lflimeira** [comment]
@cotts Como ficou os adesivos? Será que rola para o BrazilJS? Se precisar de alguma ajuda só dar um toque :smile:

**Comment by cotts** [comment]
@lflimeira amanhã terei os valores certinho e o que ficou mais em conta e mais rápido

**Comment by lflimeira** [comment]
Opa, tranquilo @cotts, obrigado pelo retorno.

**Comment by cotts** [comment]
Pessoal, Realizei a cotação, O próximo passo é avaliar pessoalmente a qualidade do material para poder fechar e em seguida fechar o valor de envio com o custo específico para cada um.

Se várias pessoas morarem em um mesmo centro, posso enviar para uma delas (com a devida autorização dos demais e retirem com ela), fica à critério de vocês.


Favor preencherem a planilha com o nome e quantidade que vão querer.

https://docs.google.com/spreadsheets/d/1KmRElN705JQaRe92XhedpR1QjPb10UnN_Hq-C0ipsdM/edit?usp=sharing


@khaosdoctor 
@lucasmarques73 
@brunorafael8 
@ranosi 
@alinebastos 
@phillip18 
@patota 
@JamileLima 
@anony000 
@vicainelli 
@lflimeira 
@ericalves

**Comment by mtferreira** [comment]
tb to interessado nos adesivos, ainda da tempo? rsrs

**Comment by lflimeira** [comment]
@cotts Eu preciso de permissão para acessar a planilha, eu já enviei a solicitação :smiley:

**Comment by mauraodev** [comment]
opa também quero o adesivo

**Comment by cotts** [comment]
Desculpe.. Já liberei os acessos lá mas agora com esse link aqui está liberado direto

https://docs.google.com/spreadsheets/d/1KmRElN705JQaRe92XhedpR1QjPb10UnN_Hq-C0ipsdM/edit?usp=drivesdk

Eu vou tentar ir seguindo o cronograma que eu fiz lá na planilha... ainda dá tempo..

**Comment by mtferreira** [comment]
@cotts nao vi o prazo la, mas preenchi rsr. Quanto ao valor, tem alguma informação? vlw!

**Comment by cotts** [comment]
@mtferreira a aba workflow não está visível?

**Comment by cotts** [comment]
Pessoal... vamos fechar no adesivo redondo de 4cm?

**Comment by FeelipePM** [comment]
Eu também quero!

**Comment by Kirmayrtomaz** [comment]
Ei quero lol

**Comment by FeelipePM** [comment]
Quer minha localização?

Sent using the free mail.com iPhone App

**Comment by cotts** [comment]
Os endereços vou pegar depois que estiver com os adesivos em mãos

**Comment by FeelipePM** [comment]
Ok

Sent using the free mail.com iPhone App

**Comment by khaosdoctor** [comment]
Já preenchi o meu lá :)

**Comment by cotts** [comment]
Pessoal, como foram mais adesivos solicitados do que o que eu havia cotado, o preço foi calculado, e já avaliei o material, favor verificarem a aba Prazos para acompanharem o andamento e tentarmos cumprir o prazo lá.

**Comment by cotts** [comment]
Pessoal... 
Para quem quiser ir preenchendo os dados de envio para agilizar, segue formulário.

https://cotts.typeform.com/to/sI9Cjj

**Comment by FeelipePM** [comment]
Já deixei meu endereço via typeform

Sent using the free mail.com iPhone App

**Comment by cotts** [comment]
@FeelipePM, me manda mensagem lá no slack, tu consegue pegar os adesivos direto comigo.

**Comment by gustavocardoso** [comment]
Olá... eu tb quero! Como fica o valor?

**Comment by cotts** [comment]
Pessoal.. a planilha foi fechada para edição... Amanhã realizarei o pedido dos adesivos e dar continuidade no fluxo.

**Comment by alfalmeida** [comment]
Também quero!

**Comment by khaosdoctor** [comment]
Fechando aqui porque já foram pedidos 😆
