### ISSUE TITLE
Sugestão de evento online do CT.

### ISSUE THREAD

**Issue by ghost** [training-center/sobre#19]
Apenas uma sugestão que pode ser bastante modificada ok ? :)

# A ideia

Seria um tipo de evento online com palestras ou bate papo com mentores que estivessem disponíveis ( seja para apresentar algo bacana que tem pesquisado, abordar um tema que acha que pode ser interessante ), seria online para facilitar o acesso/divulgação. 

# Objetivo

O intuito maior seria a divulgação do projeto, conhecermos melhor alguns mentores e quem sabe fazer uma boa ação ^^

# Extra

Um evento gratuito mas que poderia rolar um tipo de doação simbólica que fosse revertido para alguma instituição ( apoio a criança com câncer / algum Lar para idosos e etc ),  talvez para doações maiores, o doador ganhasse algum brinde como adesivos do CT #17.

**Comment by woliveiras** [comment]
Sua ideia é muito boa, @allysonthales!

Como você imagina esse evento acontecendo?

Por exemplo: você imagina a galera fazendo um hangout e trocando de palestrante a cada 40 min e durante esses 40 min eles realmente palestram sobre um assunto estilo um TDC, BrazilJS, etc?

**Comment by khaosdoctor** [comment]
Muito bom mesmo! Acho que é uma excelente ideia :) estou com a mesma dúvida do @woliveiras, mas acho que pode ser muito válido!

**Comment by alinebastos** [comment]
Gostei! :)

**Comment by kellfluz** [comment]
Nossa, isso me ajudaria em muitos sentidos!

Também gostei da ideia. :D

**Comment by jamile-dev** [comment]
A ideia é muito boa! Contem comigo!
Acredito que isso ajudaria até mesmo em relação a motivação para dar continuidade ao projeto! <3

**Comment by khaosdoctor** [comment]
Isso poderia estar relacionado com: https://github.com/frontendbr/forum/issues/636 ?

**Comment by ghost** [comment]
Perdão a demora kk @woliveiras eu imaginei como um evento maior mesmo, com uma sequencia de palestra no mesmo dia, não tinha pensado nisso mas seria interessante um tipo de "serie" que poderia ser feito a cada 2 meses com alguém do CT ou ate mesmo alguém em nome do CT.   enfim, ficaria com uma decisão do que acharem melhor mesmo, mas sendo uma serie periódica de palestras, não vejo muita possibilidade do esquema de uma doação a alguma instituição carente, mas agregaria bastante conhecimento sim.

**Comment by khaosdoctor** [comment]
Define melhor essa ideia ai @allysonthales :) ai manda aqui pra gente ver certinho como podemos fazer

**Comment by ghost** [comment]
OK, vou falar como eu pensei e vocês mandar ai as mudanças que acharem melhor. 
Pensei em um evento com 3 focos, divulgar o CT ( porque vi que meus amigos da facul n conhecem ), Apresentar os mentores ( porque, falando por mim, só conheço 2 ) e fazer uma boa ação. 

O evento seria em um ou dois dias ( dependendo da quantidade de "palestras" disponíveis ) com ocorrendo durante a noite ( porque acredito ser melhor para a maioria ), mas não que não entre tão tarde da noite ( tipo ate 23h ), acredito que umas 5 palestras por dia seria ok ( daria um pouco mais de 3 horas, 40 min cada ). 

Rolaria uma divulgação boa para atrair principalmente aqueles que não conhecem o CT, junto do link de inscrição seria passado o github para quem se interessar, ler sobre. A inscrição seria gratuita, porem aceitaria doações que seriam 100% revertido para alguma instituição carente, doaçãos de 15 reais receberiam um adesivo do CT de brinde ( ai teria que ver preço para envio se da certo ou não ). Poderia ser ate mesmo no youtube, mas é possivel conseguir uma parceria com a eventials para botar o evento la.

Basicamente a ideia era essa, não pensei tão fundo mas em essência seria isso acima.

Vendo no Slack vi que fizeram um apoie.me para o CT, as doações poderiam ser com o intuito também de ajudar nos custos que estão la no site.  Outra coisas seriam sorteios, não sei se rolaria mas geralmente empresas tipo Caelum oferecem camisas, canecas, adesivos e etc para a organização sortear no evento... mas enfim, isso são só algumas ideias "plus".

**Comment by khaosdoctor** [comment]
> O evento seria em um ou dois dias ( dependendo da quantidade de "palestras" disponíveis ) com ocorrendo durante a noite ( porque acredito ser melhor para a maioria ), mas não que não entre tão tarde da noite ( tipo ate 23h ), acredito que umas 5 palestras por dia seria ok ( daria um pouco mais de 3 horas, 40 min cada ).

Este seria um evento presencial?

> A inscrição seria gratuita, porem aceitaria doações que seriam 100% revertido para alguma instituição carente, doaçãos de 15 reais receberiam um adesivo do CT de brinde ( ai teria que ver preço para envio se da certo ou não ). 

Como você disse, criamos um apoia.se para poder custear os valores da própria comunidade, então podemos usar as doações com este fim, pelo próprio apoia.se/trainingcenter para podermos custear tanto os adesivos quanto outras coisas.

> Outra coisas seriam sorteios, não sei se rolaria mas geralmente empresas tipo Caelum oferecem camisas, canecas, adesivos e etc para a organização sortear no evento... mas enfim, isso são só algumas ideias "plus".

Sempre que fazemos eventos em comunidades como o [ABCDev](https://github.com/abc-dev) tentamos conseguir o máximo de patrocínios para podermos fazer este tipo de coisa, é bem viável sim :)

**PS:** Eventos presenciais são caros para alugar um local e etc, como podemos reduzir os custos?

**Comment by lflimeira** [comment]
@khaosdoctor acredito que a ideia é um evento online, ele citou isso lá no começo da issue :smile: 

Nesse caso, eu acredito que seja viável, precisaria de uma divulgação boa para que a galera acompanhe ao vivo.

**Comment by khaosdoctor** [comment]
Se for online ai show de bola :D

Só que eu acho que fica meio cansativo não? 3h de palestras online e etc... Temos que trabalhar nessa dinâmica

**Comment by lflimeira** [comment]
Isso é verdade @khaosdoctor, ficaria bem cansativo. Talvez fazer palestras de 15 min e poucas palestras talvez ficasse melhor.

**Comment by kellfluz** [comment]
Eu pensei também em pegar um assunto específico e fazer uma palestra por dia/semana, sei lá. Porque ai da para aprofundar bastante no assunto. Só uma ideia.
Mas palestras com tempo menor também já ajudaria.

**Comment by khaosdoctor** [comment]
Poderia ser um conjunto de talks **ao longo da semana**, mas não todas juntas no mesmo dia

**Comment by allangrds** [comment]
> Poderia ser um conjunto de talks ao longo da semana, mas não todas juntas no mesmo dia.

Seria mto bom. Diminui a carga pra galera que quiser ver.

**Comment by alfalmeida** [comment]
Cria uma espécie de CT TV. 
Por exemplo: Segunda Backend palestra ás 8pm de PHP, às 8:30pm de Python. Quartas feira Database seguindo a mesma lógica anterior. Sexta de BTC (olha o trocadilho) onde só se fala de criptomoedas pra galera se monetizar. kkkkkk Assim sucessivamente sobre os mais diversos temas. 
Isso poderia ser bimestral, trimestral, sei lá... algo do tipo. Ou semanal se a galera for mais hardcore. hehehe
O que acham?

**Comment by woliveiras** [comment]
Acho uma ideia muito boa!!!!!!!!

**Comment by danilosilvadev** [comment]
Então o intuito é bom, mas o CT tem força pra fazer isso? tipo algo semanalmente com tantas pessoas envolvidas e tals? pq o hipsters.net faz aquele podcast daora mas os caras são mega famosos, divulgam no jovem nerd todo mês e tem muita grana envolvida. Qualidade custa caro e fazer um evento mesmo q online demandaria bastante. Não quero por terra na ideia de ninguém mas eventos precisam de toda uma estrutura pra ocorrer, e precisam de público pra valer a pena. As lives do CT não acumulam muita gente, um podcast faria mais sentido, ou uns vídeos q um evento. Agora se o evento for presencial a história é outra, talvez vá mais gente e role mais como o brazilJS maaaaaas, ae custa mais caro.

**Comment by khaosdoctor** [comment]
Então, pelo que eu entendi o @alfalmeida está dizendo de fazer um vídeo que pode ser transmitido como uma live mas vamos deixar guardado.

Eu acho que é um trabalho bastante complicado justamente pela assiduidade, precisaremos de uma pauta para todos os vídeos de todas as semanas e também um editor, são coisas complicadas que exigiriam um pouco de tempo e recorrência...

No momento atual do CT **eu** acho que é mais válido organizarmos meetups, como já foi discutido no #14, #15, #13, #12, #11 

Assim podemos dividir as equipes e não precisamos de taanta coisa para tirar do papel. Eu acho a ideia **simplesmente sensacional** mas eu acho que ATUALMENTE o CT não tem uma disponibilidade tão assídua para fazer algo do tipo, como o @danilosilvadev disse.

**Comment by ghost** [comment]
Concordo que nesses ultimos 3 dias apareceu umas issues sensacionais kk 

poderia rolar tipo as entrevistas do CT do medium, mas em video pelo youtube mesmo, mas vamos deixar essa ideia mais para frente mesmo, apareceu ideias tops ai que merecem um foco maior.

acho que podemos fechar a issue ? @woliveiras  @khaosdoctor  ?

**Comment by woliveiras** [comment]
Acredito que seja bom manter ela aberta mais um pouquinho por que podem aparecer mais boas ideias, @allysonthales 😬 

Estamos anotando tudo e compilando pra depois discutir com todo mundo como vamos fazer, então é sempre bom um comentário novo aqui.

**Comment by danilosilvadev** [comment]
O próprio hackaton pode ser o evento online, na hora de avaliar os códigos e anunciar os vencedores isso pode ser feito via live online com os juízes avaliando ao vivo num hangout e dando as notas dos critérios. O que acham? assim ensinam, tem o evento online, linka com o hackaton e os participantes entendem o q acertaram ou erraram.

**Comment by woliveiras** [comment]
Eu acredito que o hackathon será online mesmo, @danilosilvadev 

Só que um não substitui o outro. Da pra fazer o hackathon monstro e depois ainda um evento online também! 🙌  🙌  🙌 

Só que um por vez pra galera não enlouquecer na organização da casa. UAHHUAHA

**Comment by khaosdoctor** [comment]
o hackathon estamos tentando ver uma parte online e outra parte presencial @danilosilvadev, vamos ver se dá certo kk

**Comment by danilosilvadev** [comment]
Presencial já n rola pra mim, moro no fim do mundo. Pfvr só online, ou faz 2 hackatons diferentes.

**Comment by khaosdoctor** [comment]
A ideia é ser online mesmo @danilosilvadev, porém quando o vencedor fosse anunciado, se ele fosse de SP, queremos fazer um meetup com todo mundo para explicar as dificuldades do projeto, motivos pra usar a tecnologia e tudo mais, ai vamos fazer uma live para o pessoal que não mora aqui ou não pode vir.

Se não forem daqui, ai vamos criar um meetup local aqui e transmitir como se fosse uma apresentação a distancia.

**Comment by danilosilvadev** [comment]
Ah blz

**Comment by khaosdoctor** [comment]
Fechado por conta do #23
