### ISSUE TITLE
Grupo de estudos CSS

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#2]
Formação de grupo para estudar CSS

**Comment by akfzambrana** [comment]
Posso ajudar :wink:

**Comment by woliveiras** [comment]
Oooopre

**Comment by WendellAdriel** [comment]
To dentro :+1:

**Comment by LarissaAbreu** [comment]
Tamo junto :sunglasses:

**Comment by idlua** [comment]
Prevejo muita coisa boa surgindo daqui!
Tamo junto²

**Comment by roberthlima** [comment]
\o/

**Comment by SoullPower** [comment]
Opa estou dentro \o/

**Comment by thiagorosario** [comment]
Boa, tamo nessa!

**Comment by alannaidon** [comment]
Go!

**Comment by davidasimoes** [comment]
Vamo ae

**Comment by lucasbento** [comment]
Também tô dentro!

**Comment by woliveiras** [comment]
10 PESSOAS!

Já da pra montarem dois grupos com 5 pessoas, nomear esses grupos, abrirem issues com os nomes dos grupos de vocês e discutirem por lá para todo mundo acompanhar como estão se organizando e o andamento de vocês.

Parabéns por estarem na disposição de praticar, galera! \o/

**Comment by idlua** [comment]
Então, os 5 primeiros comentários formam um grupo e os 5 comentários a seguir um segundo grupo, certo?
Alguém já pode definir um nome e criar uma issue no padrão Grupo <tecnologia> <nome-do-grupo>.
Exemplo: **Grupo CSS HUB**.

**Comment by woliveiras** [comment]
Isso ae @idlua
