### ISSUE TITLE
Olá 

### ISSUE THREAD

**Issue by ghost** [training-center/sobre#2]
Boa tarde pessoal.

Estou a procura de um mentor para me aperfeiçoar na área de web designer, eu tenho conhecimento em CSS, HTML, pouco de PHP e pouco de JavaScript, tenho interesse em aprender mais essas linguagens e outras para web, eu também tenho conhecimento em back-end com WordPress mas pouco também gostaria de aperfeiçoar.

Eu moro em Fortaleza e aqui é muito complicados cursos ou estudos mais focados nessas áreas principalmente pra designer desenvolvimentos de Layouts etc.

@Belline gostaria caso você tenha interesse se tornar o meu mentor?

Nome: Esther Sarde
Nivel de conhecimento atual: CSS, HTML, PHP(pouco), JS (pouco), WordPress(mediano).
Contato:
gmail:  esthersarde@gmail.com
linkedin: Esther Sarde
Twitter: @EstherSarde

**Comment by woliveiras** [comment]
Bem vinda Esther!

O processo de conseguir um mentor mudou, agora é só entrar em contato direto com o mentor. Da uma olhada aqui: https://github.com/training-center/mentoria#preciso-de-uma-mentora

As issues sobre isso são fechadas, mas isso não impede que você entre em contato com eles, viu.
