### ISSUE TITLE
Criar uma plataforma para o mentoria

### ISSUE THREAD

**Issue by allangrds** [training-center/sobre#21]
Ficar controlando as coisas pelo GIthub é uma coisa complicado, e acho que os admins do projeto de mentoria estão utilizando o Trello para gerenciar os mentores.

E se houvesse um portal pra gerenciar tudo isso  ?

- Mentores: Fariam o cadastro do perfil, suas skills, "vagas" disponíveis para pupilos, e poderiam dar o match nos pupilos;
- Pupilos; Fariam o cadastro do perfil, skills e receberiam um email/notificação no sistema quando algum mentor desse match;
- Admin: Fariam o controle dessa galera, podendo remover algum desses caras.

**Comment by woliveiras** [comment]
Ideia muito boa, @allangrds 

Vamos levar isso para os envolvidos na moderação e na comunidade.

**Comment by allangrds** [comment]
Dependendo da linguagem, eu topo do fazer o back tbm \o/.

**Comment by brunopulis** [comment]
@allangrds Bem interessante a ideia só a palavra match me lembrou do Tinder :smile: . Acredito que seria bem melhor mesmo, qualquer coisa topo fazer o frontend tb \p/

**Comment by khaosdoctor** [comment]
A gente tinha cogitado algo desse tipo na organização, mas ninguém tinha tempo para fazer e estávamos com muitos projetos para focar, resolvemos postergar no final para deixar mais tempo para focarmos totalmente nisso.

Mas eu acho uma ideia muito bacana! Aprovo totalmente.

@brunopulis O LinkedIn vai lançar uma plataforma de mentoria com esse esquema do Tinder

**Comment by brunopulis** [comment]
@khaosdoctor Interessante, essa ideia é bacana pelo fato ser trazer pessoalidade tanto pro mentor/padawan =)

**Comment by RubensSJunior** [comment]
Opaa Muito legal essa ideia. topo ajudar como back com o @allangrds. Só chamar que tamos ae

**Comment by danilosilvadev** [comment]
Puts bem q podia ser um sistema tipo tinder, dando like nos mentores e ae se der match viramos yoda e luke, anakin e obi-wan, zé mayer e marcos pasquim...

**Comment by kellfluz** [comment]
Adorei a ideia!
Posso tentar ajudar em alguma coisa do front também e claro, na divulgação. ♥

**Comment by allangrds** [comment]
PHPzeiro @Rubensdsj?

**Comment by RubensSJunior** [comment]
@allangrds PHP é oque eu sei mais (não que seja tanto assim).
To aprendendo Python também e sei o básico de Ruby. Mas sempre topo aprende qualquer coisa.

**Comment by khaosdoctor** [comment]
@danilosilvadev O linkedIn vai lançar algo no Canadá e na Austrália, ouvi isso no LoopMatinal esses dias. Seria um esquema mais ou menos igual ao Tinder mesmo. O cara iria passando pra lá e pra cá de acordo com as skills do mentor e/ou vice versa.

Acho que o que o CT precisa mesmo é, além disso tudo, uma plataforma para organizar as coisas. Organizar em PR's não dá mais não kk

**Comment by woliveiras** [comment]
Organizar em PRs está passando dos limites humanos! 😂 

Passou do primeiro release do MVP, agora é partir para a próxima fase da melhora contínua.

**Comment by khaosdoctor** [comment]
Eu acho isso uma ótima ideia pro #23 como tema inicial...

**Comment by allangrds** [comment]
Eu e @Rubensdsj no back, e @brunopulis e @kellfluz no front. Já dá pra fechar uma equipe.

**Comment by caiobertacco** [comment]
Eu tbm topo participar do front

**Comment by allangrds** [comment]
Show de bola @caiobertacco.

@woliveiras Acho que esse tópico já pode ser encerrado, não? É criar o projeto e mandar email pra todo mundo que aceitou participar.

**Comment by khaosdoctor** [comment]
Nós vamos discutir melhor em uma call no sábado agora as 20h, está aqui no #23 as instruções :)

Ai podemos definir todas as ideias e também consolidar tudo para poder mandar o e-mail pro pessoal que quiser participar. Temos que fazer media kits também pra divulgar. Vou fechar esse porque praticamente sabemos qual será o tópico haha

**Comment by allangrds** [comment]
@khaosdoctor Não poderei participar dessa call, mas se puderem me chamar pra outra conversa.
