### ISSUE TITLE
Hackathon Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#23]
Com base na issue #20 diversas ideias surgiram para movimentar nossa comunidade.

Dentre elas surgiu a ideia de um hackathon do Training Center que, talvez, pode ser algo presencial ou online e temos que analisar como faremos.

## Como organizar o hackathon

Eis a grande questão... Será um evento online, um evento presencial, um evento semi presencial, como poderíamos fazer?

Lembrando que a maioria das pessoas só consegue participar de nossas iniciativas justamente por ser online, pois moram afastadas de grandes centros e isso deve ser levado em consideração.

## Prêmios do evento

Como pacotes de prêmios podemos dar camisetas do Training Center, adesivos e até mesmo juntar dinheiro através de doações ou cota de participação e pagar cursos para as pessoas que vencerem.

Eu me comprometo a procurar empresas que possam nos apoiar com doação de cursos e outros prêmios para vencedores da competição.

## Cota de participação

Possivelmente podemos cobrar uma cota simbólica de participação por equipe, onde cada equipe irá entrar com o valor de 10,00 que será revertido nas premiações.

## Quem poderá participar

Qualquer pessoa que se interessar e tiver uma equipe.

## Como montar uma equipe

As pessoas podem se comunicar pelo Slack e outros canais de comunicação para montar suas equipes.

## Quem irá avaliar os vencedores

Devemos formar uma bancada avaliadora com os requisitos bem documentados para avaliação com regras e critérios de desempate.

## Pontos de atenção

Não seria interessante mentores/organizadores/administração e moderação da comunidade participar da competição

**Comment by mathvbarone** [comment]
Opa, eu to dentro!!

**Comment by danilosilvadev** [comment]
## Como organizar o hackathon

Online, usando um fork base do evento onde estará o projeto e tals. Mas as inscrições e formações do grupo serão antes, antes mesmo de saber o q será pedido, vc pode dar uma noção só tipo vai precisar de frontend, backend e designer por exemplo.

## Prêmios do evento

Pode ser dinheiro mas seria melhor se fossem coisas, camisetas, post parabenizando, kits, uns mouse logitech etc, ou até oportunidade numa entrevista de emprego para home office ou etc, chamem as empresas parceiras e tentem algo, nada melhor q dar um emprego aos vencedores!

## Cota de participação

10 temers por pessoa, ou seja, 30 por equipe acho q daria mais grana pra fazer uns preminhos menos mixurucas pra ter até 3º lugar ao menos. rsrs

## Quem poderá participar

Coders juniors, com pouca ou nenhuma experiência mas que tenha o suficiente pra conseguir fazer um projeto com o básico. Aconselho criar um teste pra filtrar no hackerrank ou sei la algo pra n deixar um cara q sabe só fazer um hello world participar. E ninguém com mais de 2 anos de experiência tbm n poderia.

## Como montar uma equipe

As equipes precisam ter líderes, então o CT deve escolher os mentores q serão os padrinhos/líderes das equipes e eles vão criar numa issue do repo as vagas pra equipe, ae nos coments nós vamos lá e colocamos nosso currículo, projetos e falamos sobre o q sabemos etc, e ae o mentor entra em contato caso escolha a pessoa.

## Quem irá avaliar os vencedores

@woliveiras , @lflimeira , @fdaciuk(nem perguntei a ele desculpa, é só uma sugestão rsrs) e alguns outros coders tops q vcs conheçam rsrs
Os critérios devem ser clean code, escabilidade, utilização de framework, design pattern, estrutura do projeto, design etc. Cada um desses pode ser tipo uma nota de 1 a 5 estrelas, quem tiver mais estrelas ganha a competição.

## Pontos de atenção

Mentores poderiam oferecer mentoria no dia da competição as equipes, cada equipe deveria ter um mentor. Que seria tipo uma pessoa pra guiar a equipe e responder dúvidas etc, esse mentor ficaria disponível durante o tempo da equipe, ou mesmo ter um chat com vários mentores online e a gente chega num deles e pergunta algo sei la. O mentor poderia fazer parte da equipe sendo o padrinho dela, n ia programar nem uma linha mas ia avaliar, ajudar, aconselhar, ensinar etc.

**Comment by lflimeira** [comment]
Eu posso ajudar na organização do hackathon :smile:

**Comment by lflimeira** [comment]
Quanto a quem poderá participar, acho que poderia ser livre, desde que respeite as regras que o @woliveiras citou. Tendo em vista que os desenvolvedores do hackathon devem achar a melhor solução para um problema (social, talvez?), sendo mais importante o fato de como o problema foi resolvido, pelos participantes, logo isso vai equilibrar as equipes. E tbm pelo fato de que saber montar uma boa equipe é um requisito importante (afinidade, conhecimento variado e outros pontos importantes).

Concordo que o evento deveria ser totalmente online, poderíamos criar um slack ou um channel para isso, onde teria uma equipe responsável pelo evento que prestaria o suporte para duvidas, e as equipes poderiam se organizar e discutir utilizando apenas um canal.

De resto eu concordo plenamente. :smile:

**Comment by danilosilvadev** [comment]
@lflimeira se for livre já sei q os mentores n vao me escolher affs. O fato de não poder ter truta muito safa é q é bom nivelar o nível dos competidores, ou se n n tem competição rsrs

**Comment by lflimeira** [comment]
Não @danilosilvadev, os mentores não escolheriam nada os projetos seriam desenvolvidos por vcs, vcs montariam as equipes pensando nos requisitos que citei, vcs desenvolveriam a ideia para resolver o problema proposto. Entende? 

E quanto ao nivelamento, como vai se tratar de resolver um problema, todos vão partir do mesmo ponto. A diferença pode ser na hora de desenvolver e aplicar a solução, mas nesse momento que entraria a questão de montar a equipe. Mas a ideia de não deixar alguém com uma certa quantidade de experiencia participar pode ser avaliada, apesar de achar que o mais importante em um hackathon, é pensar em uma solução criativa e funcional. (isso é minha opinião, mas pode ser alinhado para que seja justo e todos tenham um bom aproveitamento do evento).

Seria muito legal que o espirito do evento fosse a participação e a vontade de adquirir conhecimento e não apenas ganhar, que foi como a ideia foi concebida. :smile:

**Comment by danilosilvadev** [comment]
Então, no comment q eu fiz acima eu citei uma ideia de deixar mentores como padrinhos dos times pra poder se organizar, e se criar estes times, cada time teria um padrinho/líder. Uma maneira de organizar e orientar os times mas enfim... sobre o espírito da competição é adquirir conhecimento e etc, esse é o resultado da competição o cerne dela é uma "competição" como a palavra diz, irão competir entre si, ou seja, alguns vencem e outros perdem. Esse é o sentido de se criar algo assim, isso q alimenta eventos como esse. O problema de deixar livre é q se torna uma competição desproporcional, como no boxe, põe um peso pesado com um peso pena e isso não seria muito justo, ou põe um faixa preta contra um faixa laranja e de novo a luta é chata, previsível e injusta. Então sei la, pode ter branchs pra competição dos jrs, dos plenos e dos seniors ou etc. Mas acredito q o hackaton vinha pra incentivar e ajudar justamente os jrs a ter uma experiência profissional com uma equipe e tals, então n vejo o ponto de deixar livre, existem hackatons livres o ano td em vários lugares, o nosso n ser livre n iria impossibilitar um senior de participar de um. Bom é só minha opinião, sei la vcs decidem.

**Comment by lflimeira** [comment]
Entendi seu ponto @danilosilvadev :smile: E faz total sentido, a comissão organizadora poderia pedir links do linkedin e outras redes e validar se o participante tem menos de 2 anos de XP, seria uma forma valida. O que acha @woliveiras ? Acho que pode funcionar.

Quanto a apadrinhar, será que n poderia gerar uma "interferência" @danilosilvadev ? Se tivesse um canal para duvidas, não poderia suprir essa necessidade de um padrinho? Pois na minha opinião, organização poderia ser ponto a ser avaliado, e nesse ponto que eu acho que montar a equipe vai ser um diferencial, quanto mais misturar conhecimento melhor.

**Comment by danilosilvadev** [comment]
@lflimeira pode ser ter um canal em vez de padrinhos, porém seria bom se o próprio CT organizasse os times e deixasse td certinho nas issues, em vez da gente falar random no slack, deixar lá tipo 10 times com nomes e tals e as vagas e ae a gente se candidatava ao time sei la(se tivesse mais gente interessada era só criar mais times), vcs precisam controlar isso o máximo possível pra n virar batata pq vcs sabem, aqui é br fábrica de batata

**Comment by lflimeira** [comment]
Ahhh sim, quanto a isso o TC iria organizar tudo... Vcs iriam apenas se inscrever com o time e desenvolver a solução. Pelo menos é assim que eu penso como deveria ser :smile:

**Comment by alinebastos** [comment]
Pessoal, amei a ideia!
Participei de um hackathon recentemente, e como o foco não foram os premios (foram premios simbólicos) a participação foi maravilhosa! Ninguém estressado, pessoal de um time ajudando gente de outro time. Foi lindo de ver!
Me ofereço pra ajudar a organizar :)

**Comment by khaosdoctor** [comment]
Eu acredito que a gente pode fazer o seguinte:

## Como organizar o Hackathon

Pegamos as inscrições de todo mundo e nivelamos os times para que tenha uma ou duas pessoas com mais experiência e os demais sejam leigos, de uma forma que possamos equilibrar melhor a equipe.

### Equipes

Acho que não deveriam ser 3, mas 5 pessoas. A maioria dos hackathons que participei colocam 5 pessoas como forma de poderem exigir um melhor tema e mais tempo. E eu acho que 5 cabeças são mais fáceis de formar uma equipe do que 3, porque sempre vão haver 2 contra 3 em qualquer decisão.

O @danilosilvadev deu uma ideia legal que é ter um "padrinho" por time, um mentor, seria bem legal ter um cara que pudesse observar, mas nunca intervir na equipe.

## Análise do código

Quem analisaria não seria escolhido pelo público, mas sim seriam 5 pessoas da organização da comunidade (pode ser qualquer um dos owners e organizadores do hackathon) e esse comitê seria auxiliado por uma outra equipe de 2 pessoas de uma dupla de apoio para poder auxiliar na busca e na normalização dos códigos.

## Tema

Acho que podemos definir um tema bem específico, por exemplo: "Desenvolver um MVP para um  portal de mentores para o CT", a equipe ganhadora poderia levar o prêmio de 1º lugar e também poder ir tocando o projeto.

É uma ideia de podermos adicionar novas iniciativas para o CT e novas ferramentas criadas por nós e para nós. De forma que teríamos um senso de desenvolvimento de algo para a própria comunidade.

**Comment by danilosilvadev** [comment]
E então podemos já começar a planejar? eu gostaria de saber se eu poderia fazer o site do hackathon. Gostaria de fazer o site de divulgação dele, n precisa ser inicialmente algo de login, registro de times ou etc. Pensei em uma SPA para a divulgação, os temas do evento, informações de como participar, fotinha dos juízes e etc. Ae num repo a gente organizava inscrição e tals. Pode ser? gostaria de fazer em react esse projeto @woliveiras 

O layout/design eu posso tentar criar uns pra ver se vcs gostam mas n é minha especialidade aviso, então se vcs quiserem me enviar algo tbm agradeço. O intuito é criar um design jovem e bem animado tipo isso:
http://www.hackathon.deloitte.com.br/

**Comment by woliveiras** [comment]
Acho muito interessante você desenvolver o site, @danilosilvadev!

**Comment by woliveiras** [comment]
Galera, como rolaram muitas ideias MONSTRAS, pensamos em marcar uma chamada pra conversar sobre isso.

Pensei em usar o Discord pra tal. O que acham?

Falam muito bem da conexão dele.

Estamos pensando em conversar nesse sábado as 20hs.

Quem quiser participar já me da um toque no Telegram pra que eu adicione na sala na hora da conversa. 

Telegram: `@woliveiras`

**Comment by khaosdoctor** [comment]
O discord tem uma conexão muito boa mesmo, nunca usei ele pra calls, sempre pra jogos kk

**Comment by woliveiras** [comment]
Show de bola, @khaosdoctor

**Comment by woliveiras** [comment]
Pessoal, tudo certo para hoje a noite então?

**Comment by woliveiras** [comment]
Galera, quem for querer participar, entre no nosso grupo no Discord: https://discord.gg/YPFTXf3

**Comment by ericmadureira** [comment]
Legal a discussão da issue. Deveria ser aberto pra todos, mesmo os mais experientes, e sem premiação em dinheiro. Talvez estimule a participação por puro aprendizado. Poderia ter 4 categorias de prêmio: 
- mérito técnico, 
- melhor experiência de usuário, 
- solução mais inovadora 
- e projeto de maior impacto.
Vi essas categorias nesse texto sobre hackathon: https://medium.com/developer-relations/liferay-hackday-2017-7c503d55276b

**Comment by danilosilvadev** [comment]
Sugestão de nome: **HackaCenter2017**

**Comment by khaosdoctor** [comment]
Curti a ideia @danilosilvadev, tu tem umas ideias bem dahoras pra nomes kkk

**Comment by danilosilvadev** [comment]
Sou um nomeador profissional kkkkkk

**Comment by khaosdoctor** [comment]
Que tal **HackaCT2017**

**Comment by danilosilvadev** [comment]
Acho q **HackaCenter2017** soa melhor mas **HackaCT2017** tem as siglas. Podia até ser algo mais tribal e divertido tipo **Hackahacka2017**. Sei lá, votem ae rsrs.

**Comment by woliveiras** [comment]
**HackaTC2017**!!! :+1: 

OBS: `TC` e não `CT`. :joy:

**Comment by woliveiras** [comment]
Mas podemos discutir sobre isso direto no [repositório do hackathon](https://github.com/training-center/hackathon)

**Comment by woliveiras** [comment]
Vamos lá galera: https://github.com/training-center/hackathon/issues/1
