### ISSUE TITLE
Encontro informal do Training Center no [CE]

### ISSUE THREAD

**Issue by rafaelbezerra195** [training-center/sobre#24]
Olá galera,

Vi que já existem algumas pessoas do Ceará, então será que poderíamos marcar um encontro informal? Poderíamos aqui propor idéias e talvez uma pauta pra uma conversa. Pode ser no bar, restaurante, praça de alimentação, onde preferirem . :)

**Comment by danilocandido** [comment]
Olá @rafaelbezerra195 , gostei da idéia, primeiramente pode ser esse encontro informal mesmo, a gente conhece a galera e depois organiza outras.

**Comment by rafaelbezerra195** [comment]
Fala @danilocandido, acho uma boa idéia, podemos definir um local e data por aqui mesmo.

**Comment by eugeniobarrosjr** [comment]
Opa @rafaelbezerra195, pode contar comigo. Muito bacana a ideia.

**Comment by rafaelbezerra195** [comment]
Opa @brcarloseugenio, legal cara, acho q vai da certo. 
@danilocandido e @brcarloseugenio  vcs preferem que marquemos um horario em conjunto só para definir local e horario ? Esse primeiro poderia ser bem informal, para trocar idéias mesmo e até formatar um próximo meetup.

**Comment by raank** [comment]
Opa, curti a ideia, se eu puder estarei no dia. :+1:

**Comment by eugeniobarrosjr** [comment]
Podem marcar o dia e o horário que estarei lá. Aos sábados seria bem melhor.

**Comment by rafaelbezerra195** [comment]
Também acho o sábado um dia mais tranquilo, e o local? Pode ser o benfica? Acho q é um local acessível e tem busão pra todo canto rsrs. Deixem ai suas sugestões que logo a gente entra num consenso.

Agradeço o retorno de vcs, fico muito feliz dessa galera ta por aqui :)

**Comment by danilocandido** [comment]
O Benfica Shopping? Acho shopping muito barulhento ainda mais em praça de alimentação.
Sugiro alguma praça como a Luiza Távora ou a praça da Imprensa.
Sobre local com sala pra usar, tem o centro cultural banco do nordeste, lá tem uma biblioteca cultural muito boa e salas para estudo de graça só chegar lá.

**Comment by rafaelbezerra195** [comment]
kk Verdade @danilocandido, de fato é muito barulhento. Gostei das três opções, dentre elas eu preferiria o centro cultural, vou procurar me informar como funciona, se precisa reservar ou algo do tipo. 
@danilocandido por vc, pode ser no sábado ?

**Comment by rafaelbezerra195** [comment]
Trabalho no centro, então vou da um pulo lá no Centro cultural para ver como funciona. Pelo que vi no link abaixo parece ser legal.
https://www.bnb.gov.br/centro-cultural/biblioteca-ccbnb-fortaleza

**Comment by danilocandido** [comment]
É sim @rafaelbezerra195 , é bem localizado ali no centro, as salas são novas, lá no CCBN sempre tem exposição de arte e música também. Não trabalho lá mas acompanho e sempre vou pra alguma coisa lá. kkkk
Dica: Se quiser alugar livro é bom levar um comprovante de endereço. Tudo de graça também.

**Comment by virginiarcruz** [comment]
Tem também as faculdades daqui gente, tipo a estácio, fa7, unifor. Se alguém tiver contatos acho que eles liberam o espaço.

**Comment by rafaelbezerra195** [comment]
A Sugestão da Virginia é muito boa também, até os espaços abertos de uma dessas faculdades particulares, são mais silenciosos, acho uma opção válida tb. 

Eu vou tentar falar com a Professora Janete, coordenadora da Estácio Moreira Campos, pode ser que consigamos uma sala.

**Comment by rafaelbezerra195** [comment]
Seria legal fecharmos um local e data ainda em setembro, pq poderiamos organizar para ainda em outubro.

**Comment by woliveiras** [comment]
Fala, @rafaelbezerra195 

Bora criar esse Meetup ai!? 

Segue esse esquema: https://github.com/training-center/meetups#como-posso-iniciar-um-meetup

Vou fechar a issue pra gente centralizar tudo o que for de meetups lá no outro repo.
