### ISSUE TITLE
Projetos TC

### ISSUE THREAD

**Issue by reinaldooli** [training-center/sobre#25]
A ideia basicamente é montar times de desenvolvimento, elegendo mentores de diversas áreas técnicas para criar um aplicativo, sistema ou qualquer coisa parecida. Listo abaixo os passos que penso para que isso tome corpo os mesmos podem ser alterados ou podem se adicionar mais passos para um melhor andamento do projeto. O ideal é que isso seja compilado mais tarde para um manual ou algo do tipo.

# Definição do projeto

Brainstorming de ideias onde nada é absurdo. O ideal é que no projeto seja possível envolver várias áreas (DevOps, FrontEnd, BackEnd, Mobile, etc...) quanto mais áreas pudermos envolver, melhor e mais complexo será o projeto e quanto mais complexo maiores as chances de se aprender coisas novas e interagir (interagir e aprender são os objetivos).

# Definição do corpo técnico

Na minha opinião isso deve ser feito entre os mentores.
Os passos para que isso aconteça podem ser gravados/escritos para que após definido o corpo técnico os pupilos envolvidos vejam como chegamos as definições do projeto.

# Definições de Arquitetura

Aqui definimos somente as interações entre as equipes, cada equipe deve ser autogerenciavel e deve conseguir definir qual a arquitetura, tecnologias e metodologias serão utilizadas para desenvolver a sua parte do projeto. As equipes podem conversar entre sí para chegar à melhor solução para um determinado problema, mas uma equipe nunca poderá impor a outra quais métodos ou técnicas serão utilizados para resolver esse problema.

# Definições de Gerenciamento

Como vamos acompanhar o andamento do projeto? Quais ferramentas utilizar? Como medir o comprometimento de cada equipe? Como decidir se é preciso trocar um membro ou a equipe inteira para a saúde do projeto?

# Outas definições

Um projeto ficou legal e alguém quer comprar/investir como vamos lidar com isso? Como lidar com o comprometimento para que os projetos não sejam esquecidos?

**Obs.: Não sei se existe alguma iniciativa parecida com essa no TC, não fui muito a fundo na leitura das issues, se já tiver algo por favor, mencionem aqui com o link.**

**Comment by woliveiras** [comment]
Ideia maneira, @reinaldooli 

Algum desses projetos ajudaria nessa sua ideia?

* https://github.com/training-center/code-review
* https://github.com/training-center/hackathon
* https://github.com/training-center/study-groups
* https://github.com/training-center/dojos

**Comment by reinaldooli** [comment]
Sim @woliveiras 

Esses projetos complementam a minha ideia, pois acredito que regras e metodologias aplicadas podem ser compartilhadas entre os projetos. Seria bacana, por exemplo, que as equipes dos projetos pudessem se encontrar para fazer algo presencialmente num hackathon, ou a partir de um problema encontrado num projeto definir um dojo, etc...

**Comment by khaosdoctor** [comment]
Mas estes projetos são independentes, servem um propósito específico?

**Comment by woliveiras** [comment]
Issue sem interação.
