### ISSUE TITLE
Reorganização dos times

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#27]
## Introdução

Hoje temos a seguinte organização de times dentro da nossa comunidade:

* owners: líderes da comunidade como um todo, as pessoas com poderes administrativos dentro do grupo
* moderators: pessoas com poderes administrativos que ajudam o Código de Conduta ser respeitado em todos os nossos projetos
* mentors: pessoas que fazem parte do Mentoria e, por consequência, tomam decisões e aplicam resoluções no Mentoria
* code-house: pessoas que cuidam do projeto Code House
* hackathon: time responsável pelo nosso Hackathon
* site: pessoal que cuida do desenvolvimento, manutenção e atualizações do nosso site
* slack: pessoas responsáveis pela moderação do nosso grupo no Slack
* women: nossa iniciativa para diversidade dentro da nossa comunidade

**Precisamos repensar esses times**

## Pra que serve essa issue

Essa issue é para levantarmos possíveis times e possíveis contribuidores(as) para a comunidade.

Devemos discutir aqui a importância de cada time, quantidade de pessoas por equipe, a dinâmica de como os times irão funcionar e quais serão os times que serão criados.

## Posso mudar de time ou abandonar o grupo?

Pooooode! Eu ficarei triste, mas pode. :joy: 

Ninguém irá te julgar ou te obrigar a continuar gastando sua energia na comunidade, afinal você dispõe seu tempo para estar conosco e ninguém pode te obrigar a fazer algo que não esteja se sentindo confortável.

Quem não estiver confortável em algum dos times, pode me enviar mensagem (@woliveiras no Telegram ou no Slack) para me avisar e podemos fazer o seguinte:

* mudança de time
* remover do time e continuar como contribuidor(a) externo
* remover do time e da org

O importante é você se sentir confortável com as tarefas que executa e poder ser produtivo(a).

Se você quiser nos ajudar, responda esse formulário: https://trainingcenter2.typeform.com/to/BVViBO

**Comment by woliveiras** [comment]
## Proposta de organização

Eu pensei na seguinte organização:

* owners
  - permanece com as mesmas responsabilidades e com as mesmas pessoas (se elas quiserem continuar sendo owners)
  - pessoas responsáveis por moderar e administrar a comunidade mantendo o código de conduta e auxiliando os times no que precisam
  - pessoas que buscam parcerias para a comunidade como cursos, eventos, etc
  - moderação do Slack
* divulgação (marketing no geral para alcançarmos mais pessoas que buscam ajuda)
  - principalmente social media (Facebook e Twitter)
  - divulgação de notícias sobre a comunidade no Medium
  - divulgação de eventos das comunidades através do Training Center
  - divulgação de cursos através do Training Center
  - será necessário a participação de alguém que manje de design para ajudar aqui (não necessariamente de outro time, mas sendo parte do time de divulgação)
* design (por que sem um time de design a casa vai ficar feia com o tempo)
  - responsáveis por toda a arte da comunidade (em conjunto com designers de outros times)
* site
  - equipe que cuidará da manutenção e evolução do nosso site
* conectividade
  - equipe responsável por ajudar pessoas que organizam Meetups
* conteúdo
  - equipe responsável pelo Medium, YouTube
  - escritores(as) e editores(as)
* projetos
  - equipes que cuidam dos projetos para desenvolvimento profissional das pessoas da nossa comunidade (Mentoria, Study Groups, Code Review)

**Comment by woliveiras** [comment]
Talvez podemos colocar como regra que uma pessoa não pode participar de mais que dois times.

Assim tem mais espaço para outros colaboradores e colaboradoras e não deixa ninguém se sobrecarregar por empolgação.

**Comment by cristiano-pacheco** [comment]
Se tiver uma vaga, eu gostaria de contribuir na equipe de projetos.

**Comment by adeonir** [comment]
Eu posso participar ativamente dos times `design` e `site`.

Vamos ver se tem mais gente chegando!

**Comment by alinebastos** [comment]
Eu me interessei em participar ativamente do time de conteúdo :)

**Comment by alinebastos** [comment]
Lembrando: não é só uma pessoa responsável por time! Pode mais gente se alistar para participar da organização dos times!

**Comment by osmar-vil** [comment]
Eu estou interesado em participar ativamente no time de `divulgação ` `design` e também no time `site` para aprender boas praticas e design pattern, trabalho em equipe

**Comment by mocariz** [comment]
Qual a responsabilidade do time de designer? Ajudar criando layouts maneiros? se esse time for dividido em quem implementa e quem desenha a ideia, queria fazer parte do 1.

Caso não me candidato para o time de site.

**Comment by woliveiras** [comment]
\o/

**Comment by woliveiras** [comment]
Nós iremos discutir melhor como os times irão se organizar também, viu galera. :grin:

**Comment by khaueviana** [comment]
Conectividade e Projetos >D

**Comment by joaodfmota** [comment]
Posso ajudar no `site`  e `projetos`.
**EDIT:**
Alias posso também buscar fazer o seguinte item do time de `owners`:
`pessoas que buscam parcerias para a comunidade como cursos, eventos, etc`

**Comment by woliveiras** [comment]
@joaodfmota, @cristianopacheco, @adeonir, @alinebastos, @khaueviana, @mocariz, @osmar-vil, podem responder esse formulário, por favor: https://trainingcenter2.typeform.com/to/BVViBO

**Comment by alinebastos** [comment]
Feito!

**Comment by miguelzinhe** [comment]
Galera, me inscrevi para cuidar do site, mentorias e o time de inclusão, mas preciso fazer um adendo importante, eu, como pessoa trans e minoria: women é um nome de exclui muita minoria, viu? Não se esqueçam que existem outras minorias e outros problemas dentro de TI, dentre eles: falta de protagonismo de pessoas trans, de pessoas negras, pessoas periféricas e, também, mulheres cis/trans.


Só uma dica a ser avaliada. ;)

**Comment by alinebastos** [comment]
Oi, Miguel!
Pois é, o TC Women surgiu esses tempos, quando notamos que não tem nem 10% de mulheres no TC. Aí esses dias vimos que seria interessante fazer uma ação para os negros também.
Agora tu falando, acho mais interessante mesmo fazermos uma ação para todas minorias.
O que tu acha? Como tu acha que podemos fazer?
Como eu ainda não fiz o TC Women deslanchar ainda daria tempo de criarmos uma coisa mais legal e mais inclusiva :)

**Comment by khaosdoctor** [comment]
Eu me interessei por continuar como `owner` mas participar ativamente na Conectividade (organizar eventos como Hackathon, Meetups) e o conteúdo também como já venho fazendo :)

**Comment by gss-patricia** [comment]
Olá!
Eu me interessei por sites e projetos, caso tenha vaga podem contar comigo o/

**Comment by adeonir** [comment]
@khaosdoctor e @gss-patricia preencham o form https://trainingcenter2.typeform.com/to/BVViBO
Mais adiante vamos organizar cada time!

**Comment by gss-patricia** [comment]
Olá!
Me interessei por projetos!

**Comment by woliveiras** [comment]
Pode preencher nosso form também, @gss-patricia 

:metal: :metal: :metal:

**Comment by khaosdoctor** [comment]
Preenchido :D

**Comment by felipefernandes** [comment]
Não sei se está contemplado em alguma parte, mas eu sugiro haver um grupo (guilda) para discutir coisas relacionado à gestão e agilidade; é um mindset importante para que todos envolvidos terem em mente para que o modelo de gestão descentralizada funcione. Sem contar que esse grupo pode ajudar a (re)colocar o pessoal no eixo de vez enquando. cc: @woliveiras

**Comment by khaueviana** [comment]
Exato @felipefernandes!

**Comment by woliveiras** [comment]
Excelente, @felipefernandes 

O que fazemos hoje é usar o grupo owners pra fazer esse papel do Agile, mas como os grupos ainda não eram tão bem estruturados ainda não dava pra pesar mais em cima dessa cultura.

Um time só pra ajudar os outros times a se organizar e agilizar as tarefas pode ajudar muito mesmo!

**Comment by miguelzinhe** [comment]
Oi @alinebastos, desculpa a demora para responder! 

Então, podemos fazer uma issue só pra discutir isso? É que eu acho que vai ficar super aleatório se tivermos essa conversa aqui e eu queria que mais pessoas participassem! <3

**Comment by alinebastos** [comment]
@oieusouamiguel não consegui te marcar lá na nova issue, não sei pq.
Mas criei, tá lá pra gente :)
https://github.com/training-center/sobre/issues/32

**Comment by woliveiras** [comment]
Boa, @alinebastos!!!

**Comment by felipefernandes** [comment]
@woliveiras pois é meu caro, se vingar, animo de colaborar. ;)

**Comment by woliveiras** [comment]
A estrutura proposta foi aceita pela maioria.

Agora vou dar sequência na #33 e combinar com as pessoas como tudo irá funcionar.

Em seguida essas pessoas serão convidadas para nossos canais privados no Slack.

**Comment by maaryhabad** [comment]
Se for possível queria participar da equipe de site e de conteúdo :)
