### ISSUE TITLE
Canais de comunicação (Slack/Telegram)

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#28]
## Problema

Hoje em dia temos informações desencontradas nos nossos canais de comunicação.

Antigamente estávamos usando o Slack para tudo, comunicação com a comunidade, canal de apoio as pessoas que precisam de dicas de carreira (principal foco do nosso grupo), moderação e administração da comunidade.

Por conta de algumas pessoas (moderação e administração) dizerem que não curtiam o Slack, nos movemos (somente equipe administrativa da comunidade) para o Telegram.

O problema, depois disso, foram as pessoas abandonando o Telegram também.

Precisamos resolver agora alguma maneira efetiva de nos comunicar (organização) para compartilharmos problemas, marcar reuniões, etc.

## Quais canais podemos usar

Podemos usar os seguintes canais para a comunicação interna:

- Telegram
- Slack
- Email

## Regras para o uso da comunicação interna

Todas as pessoas precisam utilizar esse mesmo canal para se comunicar quando formos tratar algo da comunidade. Não podemos espalhar informações em muitos locais e acabar tudo desencontrado quando precisamos resgatar algo.

**Comment by woliveiras** [comment]
Por enquanto vejo que o ideal seria utilizarmos o **Slack**.

Se todos os times estiverem em seus devidos canais e tivermos um canal geral, podemos usar o `@channel` para enviar alertas por email.

Se a pessoa não quiser ver um monte de mensagem de outros canais, pode sair e se manter somente nos canais administrativos.

**Comment by adeonir** [comment]
O ruim do Slack é o tamanho do histórico, com o tempo ele se perde.

O bom é que ficaria tudo centralizado, pois no Telegram temos vários grupos e às vezes não conseguimos acompanhar.

**Comment by woliveiras** [comment]
Siiim, @adeonir.

Essa parte do monte de grupo é embaçado.

Sobre o histórico: a gente acaba nem usando tanto assim. Se usarmos o `@channel` pra mandar email e as issues da maneira correta também teremos o histórico (no nosso email e no GitHub).

O que acha?

**Comment by adeonir** [comment]
Podemos criar canais privados para cada time e reavaliar se vai ser mais produtivo do que o Telegram.

**Comment by raymonsanches** [comment]
Pra mim o melhor mesmo é o Slack, sem dúvida. O Telegram pra mim acaba sendo uma parada mais informal, não sei rola muito engajamento, sei lá. E no telegram você acaba ficando ali "disponível" 24/7 e aí pode gerar um desgaste maior, e as pessoas acabem dropando.

**Comment by woliveiras** [comment]
> E no telegram você acaba ficando ali "disponível" 24/7 

Tem isso mesmo, @raymonsanches!

A galera pode desistir também por nossas conversas paralelas nos canais que deveriam ser só papo sério (no Telegram), enquanto no slack temos o off-topic e todo o resto para nos divertirmos (:joy:).

**Comment by hdamaich** [comment]
@woliveiras concordo com Willian, cada descentralização é mais facil o pessoal se perder e parar de dar atenção para um parte, ou até mesmo acaba dando atenção pra nada. Apenas uma canal de comunicação acho que centraliza e facilita o processo.

**Comment by woliveiras** [comment]
Galera, está quase definido que vamos usar somente o Slack de vez. 

Vou só esperar até amanhã pra ver se não aparece mais ninguém com alguma ideia legal e então parto modificar tudo pelos canais. :metal:

**Comment by khaosdoctor** [comment]
Acho que é melhor o Slack mesmo, até porque ele providencia umas coisas que o Telegram não tem. Podemos criar um canal para cada time que temos hoje no Telegram e ir por lá mesmo...

**Comment by woliveiras** [comment]
Estou planejando criar um canal colocando todo mundo que participa de maneira ativa no TC e um canal para cada time.

No principal iriamos discutir sobre coisas gerais (como esse repositório) e nos dos times coisas específicas.

Ex.:

```
#organizacao
#mentoria
#codereview
#codehouses
```

**Comment by khaosdoctor** [comment]
Acho uma boa, um canal geral para "staff" e um canal para cada time

**Comment by woliveiras** [comment]
**staff** é um nome mais da hora ein!!

![Good Job!](https://media.giphy.com/media/xHMIDAy1qkzNS/giphy.gif)

**Comment by kellfluz** [comment]
Só passando pra dar pitaco haha
Apesar de eu não conseguir usar tanto o Slack quanto eu queria, realmente concordo com o @raymonsanches o telegram é meio informal, apesar de existir grupo de Git por lá por exemplo, mas pro TC, não vejo muito sentido, pois tem muitos canais e pra administrar lá acho que acaba sendo inviável.

**Comment by khaosdoctor** [comment]
Concordo com a @kellfluz, o Telegram foi criado originalmente para ter uma comunicação direta com o pessoal e tal, mas acabou ficando muito grande e o pessoal começou a interagir demais, isso tira um pouco da relevância.

O único que eu ainda vejo um pouco de sentido é o de Owners porque são poucas pessoas e ainda conseguimos entender o que rola nele

**Comment by woliveiras** [comment]
Canais criados no Slack e pessoas sendo movidas para lá.

Qualquer problema abrimos de novo a issue.
