### ISSUE TITLE
Grupo de estudos Angular 2

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/sobre#29]
Formação de grupo para estudar sobre Angular 2.

**Comment by woliveiras** [comment]
Só se for sem TS!!! AUHAUHUAH

Brinks. :+1:

**Comment by WendellAdriel** [comment]
Poxa mano @woliveiras!!!! Kkkkkk
Pior que não gosto muito de TS também não....se o povo animar estudar sem ele mesmo ashusahushuashuashuahusahusa

**Comment by woliveiras** [comment]
Ai é vida cara! 

Eu vejo no TS o mesmo futuro do Coffee... kkkk

**Comment by WendellAdriel** [comment]
Kkkkkkkkkkkkkkkkkkkkkkkk, boa @woliveiras

**Comment by marquinhusgoncalves** [comment]
Tô dentro

**Comment by LarissaAbreu** [comment]
To dentro também :)

**Comment by GuimaP** [comment]
To dentro

**Comment by khaosdoctor** [comment]
Dentro ;)

**Comment by LarissaAbreu** [comment]
Ótimo... Fechamos em 5 pessoas... Estou fechando essa Issue e criando uma para o nosso grupo, juntamente com um canal no slack para o grupo.

Por favor, quem ainda não está no canal do slack é só acessar esse link https://ctgroups.herokuapp.com/ :grin:
