### ISSUE TITLE
Melhorar nossos README's

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#29]
Alguns de nossos README's estão sem informação, outros estão um pouco confusos.

Devemos usar essa issue para planejar um padrão e em seguida criarmos issues específicas para ajustar cada projeto.

**Comment by woliveiras** [comment]
Acho que podemos melhorar o [/sobre](https://github.com/training-center/sobre/blob/master/README.md) e usar ele como base para os demais

**Comment by woliveiras** [comment]
Precisamos reformular todo o README do Mentoria para melhorar a comunicação escrita lá.

Talvez trazer alguém que manje de animação para colocar um vídeo curto explicando como o projeto funciona.

**Comment by khaosdoctor** [comment]
Você sabe quais são os principais pontos de melhoria @woliveiras?

**Comment by woliveiras** [comment]
Ainda não, mano.

Eu estou fazendo uma pesquisa com as pessoas que leem os textos pra levantar os pontos onde temos confusão, ai vamos conseguir montar um plano de ação e sair acertando tudo. :metal:

**Comment by kellfluz** [comment]
@woliveiras quando forem alterar, se precisar de ajuda só chamar, ai eu peço umas dicas pro jornalista em casa :)

**Comment by khaosdoctor** [comment]
@woliveiras Ah beleza, então coloca depois aqui e vamos debatendo esses pontos :D

**Comment by lbighetti** [comment]
que vocês acham de passar pra Wiki do Github ?

**Comment by woliveiras** [comment]
Rapaz, verdade, ein!

Podemos bolar uma ideia pra montar um Wiki dos nossos projetos.

Assim o README fica como ponto de entrada e pra pessoa se inteirar melhor ela entra no Wiki, né @lbighetti?

**Comment by lbighetti** [comment]
@woliveiras isso ai!
É tudo Markdown também então é pouco esforço pra migrar.
E a wiki é um repo git, então continua podendo ser clonada e editada localmente.

### Benefícios:
* Centralização de todos os textos num lugar só, ao invés de vários arquivos markdown espalhados
* Sidebar
* Footer

### Contras
* Perdemos a habilidade de fazer pull requests (mas é facil fazer revert de uma mudança quando não quisermos aceitar)

#### Exemplo

* https://github.com/d3/d3/wiki

----

o que acha ?

**Comment by woliveiras** [comment]
Acho muito fera!

Em alguns repositórios vai ser simples, em outros tem muita coisa pra fazer, em todo caso vou abrir issues em cada repô com as instruções pra fazermos isso.

Vai ajudar bastante.

Até mesmo pra adicionar aquele FAQ do Mentoria e Study Groups vai ser muito bom.

**Comment by lbighetti** [comment]
Fechado então, eu posso começar o do Mentoria :raising_hand:

**Comment by woliveiras** [comment]
Criado a issue, @lbighetti https://github.com/training-center/mentoria/issues/821

**Comment by fernandofleury** [comment]
Eu acho válido termos a wiki pra documentação... mas não pra listagem de mentores/pupilos, porque ambos precisam de atualização/validação constante. Então o processo de issue/pull request auxilia nisso.

**Comment by woliveiras** [comment]
Isso mesmo, @fernandofleury 

A Wiki é só pra ensinar a criar os perfis, etc.

Por que hoje temos tudo espalhado em arquivos .md no repo.

Da uma olhada se está legal esse planejamento na https://github.com/training-center/mentoria/issues/821.

**Comment by fernandofleury** [comment]
Se vocês acham que isso vai melhorar, não sou contra. Mas eu acho que só vamos gastar tempo assim.

Acho mais fácil a gente planejar a construção de uma plataforma, sinceramente.

**Comment by woliveiras** [comment]
A plataforma vai ser criada no nosso hackathon.

Acha legal abortarmos a missão e usar outro tema no hackathon e focarmos em criar a nossa plataforma?

**Comment by lbighetti** [comment]
@fernandofleury @woliveiras Essa plataforma que vai ser criada é pra substituir o que fazemos hoje nos repos do github ?

**Comment by khaosdoctor** [comment]
Sim, basicamente isso, porque o Github não está mais escalando...

**Comment by igorvieira188** [comment]
@khaosdoctor como assim? Poderia explicar melhor?

**Comment by lbighetti** [comment]
Esse issue está desatualizado, acho que poderiamos fechar @woliveiras

**Comment by woliveiras** [comment]
Verdade, mano!
