### ISSUE TITLE
Grupo de estudos JavaScript

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#3]
Formação de grupo para estudar JavaScript

**Comment by akfzambrana** [comment]
eu :raising_hand:

**Comment by woliveiras** [comment]
\o/

**Comment by WendellAdriel** [comment]
To dentro :+1:

**Comment by LarissaAbreu** [comment]
Eu topo xD

**Comment by idlua** [comment]
Necessito!

**Comment by ktquez** [comment]
Vamo nessa

**Comment by lucasaugustofrontend** [comment]
estou dentro

**Comment by thiagorosario** [comment]
Acompanhando também!

**Comment by cvalentefilho** [comment]
Eu

**Comment by joaocarvalhowd** [comment]
Eu

**Comment by gutostroligo** [comment]
topo, topo, pq nao, vamo cai pra dentro

**Comment by lucasbento** [comment]
Também tô dentro!

**Comment by banduka** [comment]
Go

**Comment by woliveiras** [comment]
12 PESSOAS!!!

Já da pra montarem um grupo com os 6 primeiros, nomear esses grupo, abrirem uma issue com o nome dos grupos de vocês e discutirem por lá para todo mundo acompanhar como estão se organizando e o andamento de vocês.

Parabéns por estarem na disposição de praticar, galera! \o/
