### ISSUE TITLE
Grupo de estudos MEAN Stack

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/sobre#30]
Formação de grupo para estudar sobre desenvolvimento de aplicações utilizando a MEAN Stack.

**Comment by fauker** [comment]
Quero! :clap:

**Comment by LarissaAbreu** [comment]
To junto :bowtie:

**Comment by woliveiras** [comment]
Galera, o auto invite no Slack já está OK

**Comment by marquinhusgoncalves** [comment]
Tô dentro

**Comment by heliomsolivas** [comment]
Também topo, terminei o curso da alura sobre MEAN e percebi que não lembro direito AngularJS principalmente :(

**Comment by Cleysonlb** [comment]
Opa to dentro, tava estudando um pouco o Express achei mt daora, agora as outras tecnologias eu não sei tanto, ta ai uma oportunidade de me especializar ;)

**Comment by LarissaAbreu** [comment]
Ótimo... Irei criar um canal no slack pra gente poder se organizar e tacar o pau nos estudos :grin:

**Comment by LarissaAbreu** [comment]
Essa issue será fechada e será aberta uma nova para esse grupo :wink:
