### ISSUE TITLE
Remover Reddit do nosso repo

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#31]
Em alguns locais ainda temos links para o Reddit.

É necessário remover essas referências, pois não iremos mais utilizar a plataforma.

## Como solucionar

Para fazer isso basta entrar em cada repositório nosso, baixar o projeto, utilizar algum editor de texto que consiga fazer uma busca em todos os arquivos e procurar por `reddit`.

Em alguns casos será uma remoção de link, em outros casos será uma remoção de referência textual.

## Checklist

Repositórios a serem analisados:

- [x] mentoria
- [x] code-house
- [x] code-review
- [x] divertidalista
- [x] roadmap
- [x] training-center.github.io
- [x] mentoria-webapp

**Comment by kellfluz** [comment]
@woliveiras aparentemente já foi tudo :D

**Comment by woliveiras** [comment]
Perfeito, @kellfluz 

Mandou muito bem!
