### ISSUE TITLE
Integração do TrainingCenter com Eventos

### ISSUE THREAD

**Issue by ricardogouveia3** [training-center/sobre#34]
Eae pessoal,
Uma das coisas que eu estava pensando aqui era que bastante gente quer palestrar, mas tem medo, acha que não sabe o suficiente (eu), acha que vai desmaiar lá em cima...
A mentoria do trainingcenter melhora o conhecimento técnico, que melhora a confiança (suponho, ainda não sou mentorado), mas também é um aconselhamento de carreira.
Seria legal abrir espaço em eventos como FrontInX (são vários né) e outros para pessoas vindas do trainingcenter, a pessoa ganha visibilidade, o mentor ganha visibilidade, o projeto ganha visibilidade... e tem outros benefícios também.

**Comment by woliveiras** [comment]
Muito bom, @ricardogouveia3 

Eu comecei fazer um trabalho de levantar qual a plataforma que o pessoal mais usa para acompanhar eventos justamente para começarmos algumas parcerias. 

A sua ideia seria conversarmos com organizadores(as) de eventos e pedir espaço para nossos(as) mentorados(as) e mentores(as), né?

**Comment by ricardogouveia3** [comment]
Isso mesmo @woliveiras 
O meu texto focou nos mentorados pq eles precisam e desejam dessa experiência. Não sei se tem algum mentor também querendo esse espaço, mas também seria legal ver em algum evento um mentor falar sobre a experiência de mentorar.
Pra front-end você poderia usar o [Front End Br](https://frontendbr.com.br/eventos/) acho que tem bastante evento cadastrado lá.

**Comment by woliveiras** [comment]
Seria coisa linda!

Nós temos um esquema de call 4 papers: https://github.com/training-center/call-4-papers

Também podemos mandar isso para o pessoal avaliar e colocar nas grades que fizerem sentido.

**Comment by silviorodrigues** [comment]
No [FrontInVale](http://frontinvale.com.br/), além das talks principais, nós separamos espaços no formato de lightning talk (10 minutos) justamente para quem quer dar o pontapé inicial na vida de palestrante. Com o passar dos anos é bem legal de ver o crescimento nas submissões e ver gente que foi em outros anos para assistir criando coragem para subir no palco. Mas ainda é pouco, e eu mesmo conheço muita gente que tem um puta potencial mas esbarra na vergonha/medo.

Acho muito foda esse lance de dar um suporte tanto emocional quanto técnico, além de um repositório de pessoas que querem ter uma chance, não só para os FronIn (creio que mesmo uma LT para um evento com 300 pessoas seja bem apavorante), mas para os inúmeros meetups que existem por ai e acabam morrendo por falta de gente para falar. Aqui no interior já vi vários irem perdendo a força por falta de gente para abordar algum assunto.

**Comment by malaquiasdev** [comment]
Não sou de SP então não sei se esses eventos são meetups.

Mas eu acredito que pra quem subiu poucas vezes pra falar ou já falou um Meetup seja ideal pra começar.

Por causa do tamanho do encontro assustar menos.

**Comment by ricardogouveia3** [comment]
Muito foda esse formato do FrontInVale!
Vejo nos eventos que se fala muito sobre que não há diferença entre quem está no palco e quem está na plateia, mas iniciativas como essa e outras ajudam a demonstrar que essa diferença é só de localização, e que todo mundo pode expor ideias boas.

**Comment by silviorodrigues** [comment]
@mmalaquiasdev exatamente! Os meetups são encontros menores (umas 30 pessoas no máximo) em formatos variados: palestras, debates, etc.

Uma questão: Vocês acham que a procura deve vir dos eventos para novos palestrantes ou dos palestrantes para os eventos que estejam abertos? Seria legal um lugar que concentrasse os dois fornecendo informações como o formato do evento, o nível de experiência do palestrante e até os temas que ele gostaria de falar ou que o evento quer abordar?

**Comment by malaquiasdev** [comment]
@silviorodrigues aqui na Bahia temos um problema grave, dificilmente alguém se arrisca em enviar uma palestra. Então por aqui os eventos vão em busca de novos palestrantes.

**Comment by angeliski** [comment]
Uma coisa que seria legal é uma concentração diferente disso. Hoje os eventos são criados quando tem alguém pra falar sobre um assunto X. É se houvesse a inversão disso, a galera inicia uma votação sobre temas, ai quando chegar em um número X, o evento é fechado. Imagine que na votação, os temas que ganharam foram Vue.js server render e  webpack avançado. Agora nós procuramos palestrantes que estejam afim de falar sobre isso. Meio que um evento sobre demanda...

**Comment by ricardogouveia3** [comment]
@angeliski em um evento que eu ajudava a coordenar nós já pensamos nisso, mas tínhamos 2 problemas:
- Baixa participação na votação
- Probabilidade de não haver palestrante qualificado para o tema
É claro que esses problemas são específicos da nossa realidade (cidade pequena e pouco interesse por evento sem certificado) mas acho que vale compartilhar a experiência.

**Comment by angeliski** [comment]
Realmente, tem essa possibilidade

**Comment by lflimeira** [comment]
Acho que vai sair um projeto para ajudar pessoas a se prepararem para palestras e tbm desenvolver uma ideia de palestra. 👀

**Comment by woliveiras** [comment]
VEM MONSTRO!

![](https://media.giphy.com/media/NT2xg15iceXdu/giphy.gif)

**Comment by maaryhabad** [comment]
Posso fazer uma live sobre didática e oratória pra ajudar essas pessoas :D

**Comment by lflimeira** [comment]
E não é que o projeto saiu mesmo https://github.com/training-center/help4papers :rofl: :rofl: :rofl: :rofl:

**Comment by khaosdoctor** [comment]
Vamos mandar tudo para o Help 4 Papers! Vou fechar essa issue aqui para movermos a discussão pra lá :D 

Falem com a @FernandaBernardo e/ou o @lflimeira que estão guiando mais de perto o projeto (pelo menos do que eu estou sabendo, se esqueci de alguém me desculpa!) e ai podemos derrubar todas as arvores do Ibirapuera.
