### ISSUE TITLE
times[site]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#35]
Baseado na #27 iremos conversar nessa issue sobre como o nosso time **site** irá se organizar.

Foi enviado um email com essa issue para todas as pessoas que desejam fazer parte desse time e essa issue é uma convocação para que elas participem do planejamento da estrutura do time.

## O que precisamos definir nessa issue

- definir uma ou mais pessoas para ser a representante do time
- definir como será a organização do time
- ao finalizar tudo, adicionar as pessoas que aceitaram ser do time site no canal (privado) site no Slack
- adicionar as pessoas no time site na organização no GitHub

## Papel da pessoa representante

* Irá manter a organização do time
* manter a comunicação entre time site e outros times
* vai cuidar para que não entre algo errado em nossos Pull Request's do nosso site
* cuidará para que as pessoas sejam devidamente respondidas nas issues
* vai cuidar para que nenhuma pessoa do time maltrate as demais, por nenhum motivo
* cuidará para que todos do time site sigam o nosso código de conduta

## O que acontece em casos de conflitos dentro do time

A pessoa responsável pelo time pode tomar as decisões ou entrar em contato com o time de owners para decidirem juntos o que pode ser feito em caso de abusos ou ofensas muito graves.

Em todos os casos, a conversa com os envolvidos no conflito deve ser suficiente e se não for, pode-se ser requisitado um comitê (reunião com o time owners) para discutir o caso.

## Sobre a organização do time

Eu recomendo que usem o GitHub para tudo, afinal temos a aba **Projects** que pode ser muito bem utilizada para organização.

O GitHub também é importante para que pessoas fora da nossa comunidade possam se espelhar no que fazemos para também fazerem suas comunidades crescerem.

Não é legal descentralizar as informações, pois se temos issues abertas outras pessoas podem ajudar (e é essa a intenção geral dos projetos do Training Center serem mais inclusivos: movimentar pessoas).

**Comunicação**

Usaremos o Slack para comunicação geral, portanto centralizem suas conversas no canal **site** e outras conversas no canal **staff**.

## Precisamos movimentar nossa comunidade

Ao invés de fazerem tudo o que precisamos fazer no site, tentem sempre criar alguma issue de tarefas mais simples para que as pessoas mais iniciantes da nossa comunidade interajam com os nossos projetos.

Nessas issues coloquem a descrição do problema e uma maneira de se resolver esse problema, assim qualquer pessoa pode pegar e resolver isso.

Ex.: #31 

Isso motiva as pessoas da nossa comunidade e anima quem é mais iniciante.

**Comment by osmar-vil** [comment]
eu estou interesado em participar deste time ☝️ 😄

**Comment by kellfluz** [comment]
@osmar-vil você já preencheu esse formulário aqui? [Training Center Typeform](https://trainingcenter2.typeform.com/to/BVViBO)
Ele é justamente pra se candidatar a qual time você quiser (no máximo 2). 😄

**Comment by leonantvrs** [comment]
tenho interesse em participar do time do site

**Comment by kellfluz** [comment]
Fala @leonantvrs 
Você já preencheu esse formulário aqui? [Training Center Typeform](https://trainingcenter2.typeform.com/to/BVViBO)
Com ele você pode colocar no que tem interesse em ajudar (no máximo 2 itens)

**Comment by osmar-vil** [comment]
Bom dia @kellfluz, sim já tinha preenchido um formulario da issue #27 acredito que seja o mesmo _porem seu link esta quebrado_ não pude conferir.

**ps:** me candidatei pra mas de dois, mas posso re-definir as minhas prioridades para melhor atender as necessidades do time 😄 . na empolgação acabei pegando mais do que o recomendado! 😬  sorry!

**Comment by tjoaquini** [comment]
Como indicado no email que o @woliveiras enviou, estou declarando aqui meu interesse em fazer parte do time.

**Comment by kellfluz** [comment]
Ahh obrigada por avisar! postei na correria e nem vi, já corrigi XD

**Comment by woliveiras** [comment]
Valeu, @kellfluz!!!

Eu vou mandar outro email para o pessoal que se candidatou nos times pra galera movimentar aqui e vamos conseguir definir mais como tudo vai funcionar. 

O pessoal precisa aparecer aqui pra ao menos dizer um "quero mesmo participar dessa bagaceira". :joy:

**Comment by joaodfmota** [comment]
quero mesmo participar dessa bagaceira 😂😂😂

**Comment by leonantvrs** [comment]
quero mesmo participar dessa bagaceira :joy::joy::joy:

**Comment by mocariz** [comment]
quero participar do time :smile:

**Comment by adeonir** [comment]
Ae, ficando bom isso aqui... vamos aguardar tudo ficar organizado e ir definindo tarefas

**Comment by kellfluz** [comment]
Agora sim! E só pra deixar claro, eu também quero participar dessa bagaceira hahahaha

**Comment by oliveiraev** [comment]
O Fluxo então é preencher o typeform e depois confirmar por aqui??

> "quero mesmo participar dessa bagaceira". ￼

:+1:

**Comment by gss-patricia** [comment]
Eu gostaria de participar desse time! Já tinha preenchido antes o form. tks

**Comment by woliveiras** [comment]
Pessoal, me perdoem pela demora.

Estão rolando muitas coisas em paralelo e por isso a agilidade em responder caiu. 

Continuando nossa conversa aqui, precisamos do seguinte: 

- definir uma pessoa responsável por esse grupo (essa pessoa será responsável por agilizar o trabalho de todo mundo, puxar o carro pra frente e caso precise de ajuda para aprender a fazer isso pode contar comigo pra organizar tudo)
- adicionar todo mundo no canal #site no Slack onde discutiremos os próximos passos do time :metal: 

Assim que definirmos uma pessoa responsável, fecharemos a issue e trataremos todo o resto no Slack.

**Comment by adeonir** [comment]
William, também estou com muitas coisas em paralelo, mas estou disposto a ser ensinado a puxar o carro.
Mas caso alguém com mais tempo queira assumir, tá de boas.

**Comment by rodrigogregorioneri** [comment]
Estou interessado já preenchi o formulário!!

**Comment by leonantvrs** [comment]
Responsável do time: @adeonir :joy: :joy: :joy: :joy:

falta criar o canal no slack...

**Comment by woliveiras** [comment]
Show de bola, @adeonir!

Vou criar o canal e lá iremos discutir os próximos passos. \o/

**Comment by Marcelosilva10** [comment]
Eu quero!

**Comment by woliveiras** [comment]
Fala, galera! 

Estou começando montar os times um por vez para não nos atarefarmos demais até que os times estejam se comunicando bem.

Logo logo eu vou criar os outros. :heart: :heart: :heart:

**Comment by tjoaquini** [comment]
Gostaria de participar também.

**Comment by Diego-Brocanelli** [comment]
@woliveiras tenho interesse em participar, continuando tocando o php-studies :)

**Comment by WendellAdriel** [comment]
Como está esse time e o projeto do site?
Alguma coisa em desenvolvimento?

**Comment by woliveiras** [comment]
A organização foi reformulada e essa issue não faz mais sentido.

Obrigado pela participação, galera.
