### ISSUE TITLE
Grupo de estudos SCRUM

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/sobre#38]
Formação de grupo para estudar sobre gerenciamento de projetos utilizando o SCRUM.

**Comment by MetalWingsWeb** [comment]
Pensei nisso, ainda bem que criou :laughing: 
Estou dentro!

**Comment by LarissaAbreu** [comment]
Opa, to dentro também xD

**Comment by davidasimoes** [comment]
To dentro

**Comment by Stoque** [comment]
to dentro ;)

**Comment by alannaidon** [comment]
Count me in!

**Comment by cvalentefilho** [comment]
Dentro

**Comment by WendellAdriel** [comment]
Beleza, estamos já com 7 pessoas, já dá pra formar um grupo legal de estudos!!!

Irei fechar a issue, criar uma nova para o grupo com nome e criar o canal no Slack daqui a pouco oks pessoal!?!?!?!?
