### ISSUE TITLE
times[conteudo]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#39]
Baseado na #27 iremos conversar nessa issue sobre como o nosso time **conteudo** irá se organizar.

Foi enviado um email com essa issue para todas as pessoas que desejam fazer parte desse time e essa issue é uma convocação para que elas participem do planejamento da estrutura do time.

## O que precisamos definir nessa issue

- definir uma ou mais pessoas para ser a representante do time
- definir como será a organização do time
- ao finalizar tudo, adicionar as pessoas que aceitaram ser do time no canal (privado) no Slack
- adicionar as pessoas no respectivo time na organização no GitHub

## Papel da pessoa representante

* Irá manter a organização do time
* manter a comunicação entre time divulgacao e outros times
* cuidará para que as pessoas sejam devidamente respondidas nas issues
* vai cuidar para que nenhuma pessoa do time maltrate as demais, por nenhum motivo
* cuidará para que todos do time sigam o nosso código de conduta

## O que acontece em casos de conflitos dentro do time

A pessoa responsável pelo time pode tomar as decisões ou entrar em contato com o time de owners para decidirem juntos o que pode ser feito em caso de abusos ou ofensas muito graves.

Em todos os casos, a conversa com os envolvidos no conflito deve ser suficiente e se não for, pode-se ser requisitado um comitê (reunião com o time owners) para discutir o caso.

## Sobre a organização do time

Esse time também deve possuir um repositório na nossa org explicando como trabalham e como tudo funciona, pois novas pessoas não precisarão de muito para entender como trabalhar se tiver a documentação bem descritiva.

Já temos um post explicando como funciona a organização no nosso [medium](https://medium.com/trainingcenter/guia-de-editores-as-da-publicação-no-medium-do-training-center-d88aabf57cb2).

O GitHub também é importante para que pessoas fora da nossa comunidade possam se espelhar no que fazemos para também fazerem suas comunidades crescerem.

Eu recomendo que usem o GitHub para tudo, afinal temos a aba **Projects** que pode ser muito bem utilizada para organização.

Não é legal descentralizar as informações, pois se temos issues abertas outras pessoas podem ajudar (e é essa a intenção geral dos projetos do Training Center serem mais inclusivos: movimentar pessoas).

**Comunicação**

Usaremos o Slack para comunicação geral, portanto centralizem suas conversas no canal **conteudo** e outras conversas no canal **staff**.

Precisaremos da seguinte organização, podendo ser subtimes ou não, nesse time:

* redacao (equipe do Medium)
* videos (equipe do YouTube)
* parcerias (gente que tenta divulgar nosso conteúdo em outros canais)

Sendo que já possuímos o time/canal **redacao**.

## Precisamos movimentar nossa comunidade

Ao invés de fazerem tudo o que precisamos fazer no site, tentem sempre criar alguma issue de tarefas mais simples para que as pessoas mais iniciantes da nossa comunidade interajam com os nossos projetos.

Nessas issues coloquem a descrição do problema e uma maneira de se resolver esse problema, assim qualquer pessoa pode pegar e resolver isso.

Ex.: #31 

Isso motiva as pessoas da nossa comunidade e anima quem é mais iniciante.

**Comment by hdamaich** [comment]
Ainda tenho algumas duvidas sobre quais os objetivos da equipe de conteúdo.

Tenho algumas ideias, mas não se realmente se aplicam ao grupo e se são o objetivo da comunidade em si.
Qual seria a responsabilidade desse time, gerar conteúdo ou apenas fazer a curadoria do conteúdo possivelmente gerado pelo membros da comunidade?

**Comment by khaosdoctor** [comment]
Acho que os dois @hdamaich, tanto gerar o conteúdo quanto curar o que for enviado... Que é basicamente o que já é feito hoje, mas por uma equipe menor e mais restrita

**Comment by khaueviana** [comment]
Por enquanto, escolho esse aqui :)

**Comment by woliveiras** [comment]
Exatamente como o @khaosdoctor comentou, @hdamaich 

Hoje em dia nós escrevemos artigos, temos um Board onde as pessoas pedem artigos, fazemos vídeos e temos um lugar onde as pessoas podem sugerir pautas ou se candidatar a fazer algo.

O que acontece é: esses canais de conteúdo precisam de uma melhor gestão, por que está ficando pequeno pra o tanto de coisas que queremos fazer :joy: 

Basicamente as pessoas de conteúdo não vão só curar conteúdo que chega, mas vão ajudara a trazer mais gente, a incentivar as pessoas da nossa comunidade a começar fazer algo :metal:

**Comment by thmendes** [comment]
Opa, confirmo o meu interesse!

**Comment by woliveiras** [comment]
Pessoal, me perdoem pela demora.

Estão rolando muitas coisas em paralelo e por isso a agilidade em responder caiu. 

Continuando nossa conversa aqui, precisamos do seguinte: 

- definir uma pessoa responsável por esse grupo (essa pessoa será responsável por agilizar o trabalho de todo mundo, puxar o carro pra frente e caso precise de ajuda para aprender a fazer isso pode contar comigo pra organizar tudo)
- adicionar todo mundo no canal #conteudo no Slack onde discutiremos os próximos passos do time :metal: 

Assim que definirmos uma pessoa responsável, fecharemos a issue e trataremos todo o resto no Slack.

**Comment by khaosdoctor** [comment]
Eu posso ser o responsável do conteúdo, mas preciso saber exatamente qual seria a definição de "puxar o carro pra frente" kkkk

**Comment by woliveiras** [comment]
Você topa ficar responsável somente pelo time de conteúdo e mais um outro projeto, não mais por outras tarefas que você tem, @khaosdoctor? 

Você já está cuidando do hackathon, por exemplo.

Só seria interessante cuidar de dois ao mesmo tempo e você também faz parte do corpo moderador. Não acha que vai se sobrecarregar? 

Se não for se sobrecarregar, OK. Se achar que pode se sobrecarregar, recomendo que deixe livre pra outra pessoa, viu. :+1:

**Comment by khaosdoctor** [comment]
Se colocar todos os projetos lado a lado realmente não vai dar, acabei de receber uma outra demanda aqui e realmente vai ficar complicado. Vou passar essa e deixar para alguém com mais tempo :D

**Comment by hdamaich** [comment]
Se não tiver ninguém mais experiente ou que já participe da parte de conteúdo que deseje liderar, eu posso assumir.

**Comment by thmendes** [comment]
Não tenho experiência pra encabeçar o projeto, mas quem for pode contar comigo sempre. Estou começando um projeto de IoT e quero muito gerar conteúdo através dele.

**Comment by woliveiras** [comment]
Fala, pessoal! 

Estou começando montar os times um por vez para não nos atarefarmos demais até que os times estejam se comunicando bem.

Logo logo eu vou criar o de conteúdo pra vocês. :heart: :heart: :heart:

**Comment by woliveiras** [comment]
O time foi criado, quem ainda não estiver no canal de conteúdo da um salve pra gente lá no Slack.

Valeu pela participação de todos(as)! :heart:
