### ISSUE TITLE
Criar os times para organizarem o Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#4]
Depois de uma conversa com os Mentores e Moderadores do Training Center encontramos a necessidade de criar times para organizar as diversas iniciativas dessa comunidade.

Visando a criação desses times eu vou listar nessa issue as iniciativas da comunidade para discutirmos como melhor organiza-las.

Devemos discutir se os projetos devem ser descontinuados ou se fazem sentido continuarem existindo e também montar os times para organização de cada coisa.

Os times serão responsáveis por cada projeto em questão, porém uns podem ajudar aos outros nos demais projetos. Quando alguém (externo aos times) quiser reportar um problema, qualquer time pode ser acionado e um se comunica com o outro sobre o que foi reportado. Desse modo os times são separados para cuidar cada um de seus projetos, mas não deixam de ser unidos para cuidar da comunidade em si.

Projetos do Training Center, por ordem de mais movimentados:

* [x] [Slack](https://ctgroups.slack.com)
* [x] [Blog](https://medium.com/trainingcenter)
* [x] [Mentoria](https://github.com/training-center/mentoria) / talvez para a criação de uma plataforma para centralizar a busca de mentores
* [x] [Study Groups](https://github.com/training-center/study-groups)
* [x] [Site](https://github.com/training-center/training-center.github.io)

Nós podemos montar nossos times com os moderadores e mentores e também chamar os pupilos e membros da comunidade que são mais ativos para nos ajudar.

**Comment by khaosdoctor** [comment]
@woliveiras Acho que dá pra dar uma limpada nos projetos ou juntar as coisas em uma só, tipo colocar materials junto com projects e etc, pra ficar mais clean

**Comment by felipeorlando** [comment]
@woliveiras acho que o ideal seria termos um site pra centralizar tudo isso. Mais interessante ainda, uma app que relaciona mentores, pupilos, tecnologias, blogs, discussões... Ahhh, dá pra fazer tanta coisa! KKKKK

**Comment by woliveiras** [comment]
@khaosdoctor, rapaz, pode fazer isso não. kkkkkk

Tipo, Materials são materiais de estudos, Projects são projetos dos pupilos... São coisas distintas.

Mas o Materials eu gostaria de excluir, pois já temos muito material disponível na Web, que é o que compartilhamos com os pupilos, sempre. 😄

**Comment by woliveiras** [comment]
@felipeorlando , o site vai sair esse ano ainda ein! kkkkk

Um dos times vai ficar responsável pela criação do site, depois podemos até juntar umas pessoas pra fazer um App de celular.

Seria maneiro, ein! :D

**Comment by felipeorlando** [comment]
@woliveiras sobre o app, apoio 100%. Podemos desenvolver com React Native. 😃

**Comment by woliveiras** [comment]
Seria sucesso demais ein @felipeorlando

**Comment by woliveiras** [comment]
O @baltazarparra falou que gostaria de construir nosso site em conjunto com o @danilovaz.

Acho super válido, uma vez que o Baltazar criou o Layout e o Danilo está conosco desde o começo do projeto.

Ambos podem ajudar muito!

Nesse caso temos o time do site começando a se formar. 😄 

Vocês (@baltazarparra e @danilovaz) tem mais alguém pra indicar para o time?

No Slack temos muita gente querendo ajudar, seria legal chegar junto e chamar eles também.

**Comment by woliveiras** [comment]
O time de moderadores do Slack está quase montado, contando com o @patota, @adeonir e o @MarianoJhuninhu.

**Comment by woliveiras** [comment]
O time de moderadores dos repositórios aqui no GitHub está contando com @alinebastos, @danilovaz, @JamileLima, @raymonsanches, @ftonato, @ogilvieira e @luizbills

**Comment by woliveiras** [comment]
No time do Mentoria acho que podemos manter os Moderadores + Mentores mantendo o projeto (que é o que acontece hoje), pois os moderadores tem uma visão do Training Center como um todo e podem ajudar o Mentoria continuar caminhando para um futuro grande junto com os demais projetos e os Mentores sabem tudo sobre o que está acontecendo entre pupilos e tudo mais. 

O que acham?

**Comment by MarianoJhuninhu** [comment]
@woliveiras , tbm estou aqui Manim... 😀

**Comment by woliveiras** [comment]
Acho que é importante colocar a @JamileLima na moderação do Slack também, pois ela cuida das iniciativas para mulheres do grupo (iniciativas que podem ser apoiadas pela @alinebastos e @akfzambrana ein... 😄)

**Comment by baltazarparra** [comment]
Cara, vou envolver a @KarolinedeAlencar no desenvolvimento também, porque ela estava pilhando a um tempo atrás pra gente seguir com isso.

**Comment by karolinedealencar** [comment]
Olá galere! Quero ajudar no desenvolvimento =D

**Comment by adeonir** [comment]
Se precisar de mais alguém... :raised_hand_with_fingers_splayed:

**Comment by woliveiras** [comment]
Show de bola!

Já entrem aqui então galera: https://github.com/training-center/training-center.github.io/issues

Essa aqui está com um ponto importante que eu levantei sobre qual será o "back end" do site: https://github.com/training-center/training-center.github.io/issues/5

Bora pra lá discutir então @baltazarparra, @danilovaz, @felipeorlando, @KarolinedeAlencar, @adeonir e quem mais quiser colar nesse site aeeeee \o/

**Comment by alinebastos** [comment]
Tb quero colaborar no front do site o/

**Comment by lflimeira** [comment]
O que precisarem do Back-end eu ajudo tbm galera, acho valido, pensando em app, pensar sobre PWA. E pensando em projetos como comentado em outra issue, acho valido dar continuidade no Dojo, talvez pensar em criar meetups ou lives voltados para o Dojo.

**Comment by khaosdoctor** [comment]
No momento eu estou tão cheio de coisas que não vou ter tempo então eu nem vou me indicar pra ajudar constantemente, mas eu estou disponível aqui se precisarem de algo de front/back/ops sem problemas 😄

**Comment by woliveiras** [comment]
Galera, o time do Slack está formado: https://github.com/training-center/slack#moderadores-do-slack

**Comment by woliveiras** [comment]
O time de moderação da organização no GitHub está formado: https://github.com/training-center/sobre/blob/master/CONDUCT.md#moderadores

**Comment by alinebastos** [comment]
@woliveiras Me coloca na moderação do Slack tb, é bom ter mulheres lá :)

**Comment by woliveiras** [comment]
Agora mesmo @alinebastos!!

**Comment by woliveiras** [comment]
Galera, essa issue pode ser fechada uma vez que montamos os times e estamos tocando.

Qualquer coisa podemos reabrir se acharem importante ou estiver faltando algo.
