### ISSUE TITLE
Grupo de estudos Python

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#4]
Formação de grupo para estudar Python

**Comment by WendellAdriel** [comment]
To dentro :+1:

**Comment by LarissaAbreu** [comment]
Simbora :)

**Comment by zalvesnatan** [comment]
Vamos nessa!

**Comment by NokhyPlemun** [comment]
+1

**Comment by Josue23** [comment]
+1

**Comment by Z4yon** [comment]
+1

**Comment by OtavioRMachado** [comment]
+1

**Comment by woliveiras** [comment]
Aqui já deu 7 pessoas.

Já da pra montarem um grupo com os 5 primeiros, nomear esse grupo, abrirem uma issue com o nome do grupo de vocês e discutirem por lá para todo mundo acompanhar como estão se organizando e o andamento de vocês.

Parabéns por estarem na disposição de praticar, galera! \o/
