### ISSUE TITLE
times[study-groups]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#40]
Baseado na #27 iremos conversar nessa issue sobre como o nosso time **study-groups** irá se organizar.

Foi enviado um email com essa issue para todas as pessoas que desejam fazer parte desse time e essa issue é uma convocação para que elas participem do planejamento da estrutura do time.

## O que precisamos definir nessa issue

- definir uma ou mais pessoas para ser a representante do time
- definir como será a organização do time
- ao finalizar tudo, adicionar as pessoas que aceitaram ser do time no canal (privado) no Slack
- adicionar as pessoas no respectivo time na organização no GitHub

## Papel da pessoa representante

* Irá manter a organização do time
* manter a comunicação entre time divulgacao e outros times
* cuidará para que as pessoas sejam devidamente respondidas nas issues
* vai cuidar para que nenhuma pessoa do time maltrate as demais, por nenhum motivo
* cuidará para que todos do time sigam o nosso código de conduta

## O que acontece em casos de conflitos dentro do time

A pessoa responsável pelo time pode tomar as decisões ou entrar em contato com o time de owners para decidirem juntos o que pode ser feito em caso de abusos ou ofensas muito graves.

Em todos os casos, a conversa com os envolvidos no conflito deve ser suficiente e se não for, pode-se ser requisitado um comitê (reunião com o time owners) para discutir o caso.

## Sobre a organização do time

**OBS: Esse é um dos maiores projetos da nossa comunidade junto ao Mentoria. Precisaremos de gente muito ativa para conseguir dar conta dessa responsabilidade.**

Esse time também deve possuir um repositório na nossa org explicando como trabalham e como tudo funciona, pois novas pessoas não precisarão de muito para entender como trabalhar se tiver a documentação bem descritiva. Então usaremos o repositório study-groups para centralizar tudo.

O GitHub também é importante para que pessoas fora da nossa comunidade possam se espelhar no que fazemos para também fazerem suas comunidades crescerem.

Eu recomendo que usem o GitHub para tudo, afinal temos a aba **Projects** que pode ser muito bem utilizada para organização.

Não é legal descentralizar as informações, pois se temos issues abertas outras pessoas podem ajudar (e é essa a intenção geral dos projetos do Training Center serem mais inclusivos: movimentar pessoas).

**Comunicação**

Usaremos o Slack para comunicação geral, portanto centralizem suas conversas no canal **study-groups** e outras conversas no canal **staff**.

## Precisamos movimentar nossa comunidade

Ao invés de fazerem tudo o que precisamos fazer no site, tentem sempre criar alguma issue de tarefas mais simples para que as pessoas mais iniciantes da nossa comunidade interajam com os nossos projetos.

Nessas issues coloquem a descrição do problema e uma maneira de se resolver esse problema, assim qualquer pessoa pode pegar e resolver isso.

Ex.: #31 

Isso motiva as pessoas da nossa comunidade e anima quem é mais iniciante.

**Comment by woliveiras** [comment]
@Diego-Brocanelli

**Comment by Diego-Brocanelli** [comment]
Excelente, vou ler com mais calma o documento, para que assim possamos conduzir da melhor maneira :)

**Comment by Rarfael** [comment]
Tenho interesse aqui. 
Não sei se me candidataria para representante, pois conheci o Training Center a pouco tempo e ainda estou me adaptando, mas me prontifico a ajudar no que for preciso.

**Comment by cristiano-pacheco** [comment]
Contem comigo aqui!

**Comment by woliveiras** [comment]
Pessoal, me perdoem pela demora.

Estão rolando muitas coisas em paralelo e por isso a agilidade em responder caiu. 

Continuando nossa conversa aqui, precisamos do seguinte: 

- definir uma pessoa responsável por esse grupo (essa pessoa será responsável por agilizar o trabalho de todo mundo, puxar o carro pra frente e caso precise de ajuda para aprender a fazer isso pode contar comigo pra organizar tudo)
- adicionar todo mundo no canal #study-groups no Slack onde discutiremos os próximos passos do time :metal: 

Assim que definirmos uma pessoa responsável, fecharemos a issue e trataremos todo o resto no Slack.

**Comment by woliveiras** [comment]
Fala, galera! 

Estou começando montar os times um por vez para não nos atarefarmos demais até que os times estejam se comunicando bem.

Logo logo eu vou criar os outros. :heart: :heart: :heart:

**Comment by lflimeira** [comment]
Pessoas, podem contar comigo aqui tbm :D

**Comment by lbighetti** [comment]
Acho que esse tá caminhando bem galera, quem tiver interesse e não tá ainda:
* https://github.com/training-center/study-groups
* Slack: `#study-groups-admin` - quem quiser ajudar me pinga que convido lá!

vou fechar aqui o issue!

**Comment by woliveiras** [comment]
Perfeito, @lbighetti
