### ISSUE TITLE
times[code-review]

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#41]
Baseado na #27 iremos conversar nessa issue sobre como o nosso time **code-review** irá se organizar.

Foi enviado um email com essa issue para todas as pessoas que desejam fazer parte desse time e essa issue é uma convocação para que elas participem do planejamento da estrutura do time.

**Precisamos de gente para fazer esse projeto começar a crescer, pois está bem fraco apesar dos benefícios que trás para as pessoas que estão aprendendo.**

## O que precisamos definir nessa issue

- definir uma ou mais pessoas para ser a representante do time
- definir como será a organização do time
- ao finalizar tudo, adicionar as pessoas que aceitaram ser do time no canal (privado) no Slack
- adicionar as pessoas no respectivo time na organização no GitHub

## Papel da pessoa representante

* Irá manter a organização do time
* manter a comunicação entre time divulgacao e outros times
* cuidará para que as pessoas sejam devidamente respondidas nas issues
* vai cuidar para que nenhuma pessoa do time maltrate as demais, por nenhum motivo
* cuidará para que todos do time sigam o nosso código de conduta

## O que acontece em casos de conflitos dentro do time

A pessoa responsável pelo time pode tomar as decisões ou entrar em contato com o time de owners para decidirem juntos o que pode ser feito em caso de abusos ou ofensas muito graves.

Em todos os casos, a conversa com os envolvidos no conflito deve ser suficiente e se não for, pode-se ser requisitado um comitê (reunião com o time owners) para discutir o caso.

## Sobre a organização do time

Esse time também deve possuir um repositório na nossa org explicando como trabalham e como tudo funciona, pois novas pessoas não precisarão de muito para entender como trabalhar se tiver a documentação bem descritiva. Então usaremos o repositório code-review para centralizar tudo.

O GitHub também é importante para que pessoas fora da nossa comunidade possam se espelhar no que fazemos para também fazerem suas comunidades crescerem.

Eu recomendo que usem o GitHub para tudo, afinal temos a aba **Projects** que pode ser muito bem utilizada para organização.

Não é legal descentralizar as informações, pois se temos issues abertas outras pessoas podem ajudar (e é essa a intenção geral dos projetos do Training Center serem mais inclusivos: movimentar pessoas).

**Comunicação**

Usaremos o Slack para comunicação geral, portanto centralizem suas conversas no canal **code-review** e outras conversas no canal **staff**.

## Precisamos movimentar nossa comunidade

Ao invés de fazerem tudo o que precisamos fazer no site, tentem sempre criar alguma issue de tarefas mais simples para que as pessoas mais iniciantes da nossa comunidade interajam com os nossos projetos.

Nessas issues coloquem a descrição do problema e uma maneira de se resolver esse problema, assim qualquer pessoa pode pegar e resolver isso.

Ex.: #31 

Isso motiva as pessoas da nossa comunidade e anima quem é mais iniciante.

**Comment by oliveiraev** [comment]
Não tenho pretensão (provavelmente nem tempo) de ser representante. Mas me interessou bastante a tarefa de *code-reviewer*. Contem comigo!

Edit: Não tinha visto o https://github.com/training-center/sobre/issues/33#issuecomment-332294686
Minha preferência é pelo time do site. Se, posteriormente, abrirem para participação em múltiplas equipes eu me prontifico por aqui.

**Comment by woliveiras** [comment]
Fala, @oliveiraev! 

Estou começando montar os times um por vez para não nos atarefarmos demais até que os times estejam se comunicando bem.

Logo logo eu vou criar os outros. :heart: :heart: :heart:

**Comment by WendellAdriel** [comment]
Como está o status desse projeto???

**Comment by adeonir** [comment]
O time de design está trabalhando no layout do site.

**Comment by woliveiras** [comment]
A organização foi reformulada e essa issue não faz mais sentido.

Obrigado pela participação, galera.
