### ISSUE TITLE
E ai, como andam as coisas?

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#42]
Fala galera!

Venho só observando as coisas acontecendo e tentando ajudar por fora.

Como andam as coisas, estão conseguindo se organizar, já começaram a estudar, precisam de ajuda?

**Comment by alannaidon** [comment]
A ideia é incrível, e tem um pessoal já se juntando, criando grupo no slack. Mas, nos grupos que EU me inscrevi, ainda não começamos a por a mão na massa ainda. :P

**Comment by woliveiras** [comment]
Show @alannaidon. Tomara que comecem logo a tacar pau! Se puderem documentar como estão fazendo, compartilhar o conhecimento de vocês de alguma maneira, será sucesso! \o/
