### ISSUE TITLE
ONG busca ajuda para automatizar e informatizar seus processos

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#42]
Recentemente tive uma conversa com a Emori Souza, uma voluntária no projeto TETO.

Pra quem não conhece o grupo, este é [o site](http://www.techo.org/paises/brasil/).

Esse vídeo mostra um pouco do trabalho desse pessoal: https://www.youtube.com/watch?v=HsL46mqdCAc

Eles precisam de desenvolvedores de software que possam ajudar a melhorar seus processos através de sistemas e estão necessitando, recentemente, de ajuda para montar um aplicativo iOS.

Essa issue serve para tentar levantar ajuda para esse pessoal movimentando as pessoas de nossa comunidade que desejam contribuir em algum projeto de software.

Quem possuir disponibilidade pode entrar em contato com a Emori através desse email: emorilizz@gmail.com

**Comment by Fraanco** [comment]
hahahaha que loucura! Eu estudei com a Emori na graduação!

**Comment by Fraanco** [comment]
Qual é o melhor approach agora? Cada um entra em contato individualmente com ela, ou a gente se organiza por aqui pra fazer algum grupinho?

**Comment by pedromneto** [comment]
Interessante. A Microsoft tem alguns benefícios para ONGS que são bem interessantes. Como por exemplo Office 365. E por ter Offfice 365 tem SharePoint que é muito utilizado para intranets. Ele tem, por exemplo: Gerenciamento de documentos, fluxos de trabalho, formulários customizados, notificações, controle de permissões, integração com sistemas externos, etc.

**Comment by felipefernandes** [comment]
Me candidato a receber ajuda da tuma do TC também no Code Club ^^ hahaha

**Comment by woliveiras** [comment]
Aeeeeee, @felipefernandes

**Comment by israelcena** [comment]
Show ! O que eu puder ajudar...estou aí

**Comment by lflimeira** [comment]
Em que pé está esse projeto pessoal?

**Comment by woliveiras** [comment]
Opa! Eu esqueci de fechar a issue, @lflimeira 

Foi mal. :stuck_out_tongue_closed_eyes:
