### ISSUE TITLE
Criação de um logo para o CT

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#47]
Como parte da criação de uma identidade visual, será necessário a criação de um logo para o projeto.

**Comment by baltazarparra** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/7395304/14407231/a8fd1d78-fe97-11e5-95e6-2f43d69d4e54.png)

**Comment by baltazarparra** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/7395304/14407292/1528a8d6-fe99-11e5-8893-1af8a86a478e.png)

**Comment by baltazarparra** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/7395304/14407318/5fb167fc-fe9a-11e5-8e0a-73e4125b93c4.png)

**Comment by baltazarparra** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/7395304/14407337/45c59132-fe9b-11e5-8bb6-648e0efb4dc3.png)

**Comment by baltazarparra** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/7395304/14407347/c75eac9c-fe9b-11e5-86d2-f0af6e835174.png)

**Comment by jlamim** [comment]
Faz uma dessa com as cores mais escuras, como as ultimas enviadas.

Em sábado, 9 de abril de 2016, Baltazar Parra <notifications@github.com>
escreveu:

> [image: screenshot_2]
> <https://cloud.githubusercontent.com/assets/7395304/14407292/1528a8d6-fe99-11e5-8893-1af8a86a478e.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/training-center/sobre/issues/47#issuecomment-207890334>
>


-- 

*Jonathan Lamim Antunes*


*Desenvolvedor Web/Mobile & Palestrante*
*Tel: *+55 27 3082-4437 | 27 995 125 164

www.jlamim.com.br
www.github.com/jlamim
www.facebook.com/jlamim.projetos

**Comment by woliveiras** [comment]
@baltazarparra, cara, parabéns! Sem nenhum briefing está fazendo um barato muito foda só com base no projeto!
Monstro!

Por email, tinha essa imagem aqui: 

![ct_logo_nome_no_centro](https://cloud.githubusercontent.com/assets/4243601/14409382/cdec2eee-fee7-11e5-8abb-f3620f2b5b39.png)

Achei da hora o logo com o nome no centro.

Que tal fazer um mix das cores que o @jlamim falou com o nome no centro?

**Comment by baltazarparra** [comment]
Mano @woliveiras eu achei ele muito pesado com o texto ao centro, a marca em si ficou muito "carregada" por isso optei por diminuir um pouco a marca, pra balancear a logo inteira.

Sobre a paleta de cor, vou procurar outros tons e posto aqui.

**Comment by baltazarparra** [comment]
![screenshot_12](https://cloud.githubusercontent.com/assets/7395304/14409995/5f40ddca-fef9-11e5-96f0-af26bd504792.png)

**Comment by baltazarparra** [comment]
Amigos, gostei muito dessa paleta. Oque acham?

**Comment by baltazarparra** [comment]
![screenshot_13](https://cloud.githubusercontent.com/assets/7395304/14410063/29dd4978-fefb-11e5-9a08-e71f7faf2f43.png)

**Comment by baltazarparra** [comment]
Olha oque você curtiu @woliveiras na paleta que eu gostei.
Mas ainda acho que esse ficou muito "carregado" de informação, o de cima está mais leve.

**Comment by baltazarparra** [comment]
Decidindo o logo, já vou começar a desenhar o site, ai vamos discutindo oque vamos usar no desenvolvimento, vamos fazer um projeto bem foda.

**Comment by woliveiras** [comment]
Cara, ta tudo muito da hora. Curti demais!

Essa paleta acho que ficou show.

Se der rotacionar o ícone (os carinhas) um pouco pra cima e para a direita, sem deixar o carinha de baixo maior que os outros pra tudo ficar centralizado, acha que fica legal?

Uma referência pra o que eu estou pensando seria o ícone do Ubuntu, mas com o nome do projeto no meio.

Se não só vamos precisar do seguinte, pra eu tacar pau e mudar tudo aqui no repo:

* Um ícone somente com os carinhas, poderia ser um circulo completo com eles, acho que ficaria foda, pra colocar como imagem do repo (essa que fica no perfil: https://github.com/training-center).
* O logo completo

Ambos em SVG pra poder esticar a vontade aqui no perfil e na descrição do projeto.

Parabéns cara, está ficando muito foda.

**Comment by baltazarparra** [comment]
Valeu mano =]
Já to pilhando o layout do site, mobile-first e pa... quase pronto kkkk

**Comment by woliveiras** [comment]
Eita lasquera!

**Comment by baltazarparra** [comment]
![screenshot_14](https://cloud.githubusercontent.com/assets/7395304/14410317/3f1ca15a-ff03-11e5-9ffb-5738d64a766f.png)

**Comment by baltazarparra** [comment]
Acho que com a perspectiva ficou melhor que esse mano, oque vc acha? esse ficou muito "certinho" kkkk.

**Comment by baltazarparra** [comment]
Sinceramente, oque eu curti mais foi esse.
![screenshot_12](https://cloud.githubusercontent.com/assets/7395304/14410327/77319668-ff03-11e5-8949-bb96e0445d0e.png)

**Comment by baltazarparra** [comment]
posso tacar pau no svg?

**Comment by woliveiras** [comment]
Não pow, eu quis dizer nesse cara aqui: https://github.com/training-center/sobre/issues/47#issuecomment-207971337 kkkk

**Comment by baltazarparra** [comment]
Ah, saquei... vamos ver.

**Comment by baltazarparra** [comment]
ficou um pouco sem 'perspectiva'
![screenshot_15](https://cloud.githubusercontent.com/assets/7395304/14410620/18fb2aa8-ff0a-11e5-9658-b4c2bd9863f4.png)

**Comment by baltazarparra** [comment]
![screenshot_16](https://cloud.githubusercontent.com/assets/7395304/14410661/c8a84c10-ff0a-11e5-8a88-c53d2300e7b5.png)

**Comment by baltazarparra** [comment]
Diminui um pouco o tamanho dos cabeçudinhos pra deixar um pouco de perspectiva ainda, se eu deixasse todos do mesmo tamanho ia ficar zuado...

**Comment by woliveiras** [comment]
Entendi mano, pow, eu curti, mas você é o cara que da a palavra em Design!

O que achar mais da hora, taca pau, pois todos estão legais ein.

**Comment by baltazarparra** [comment]
Obrigado pelo voto de confiança mano @woliveiras!
[Svg's e Png's](https://github.com/baltazarparra/sobre/tree/layout/logo)

**Comment by woliveiras** [comment]
É nozes mano! Tem como fazer um somente com os bonequinhos pra colocar no perfil?

**Comment by baltazarparra** [comment]
Mano, acho que a composição ficou bem equilibrada, tirando a necessidade de ter uma versão só com os cabeçudinhos. Mas joguei uma versão lá sem o texto, teste as duas e diga qual curtiu mais.

**Comment by woliveiras** [comment]
Show de bola cara! \o/

**Comment by woliveiras** [comment]
Bem foda cara, quando quiser é só mandar o PR que é nozes

**Comment by baltazarparra** [comment]
Cria um branch 'layout'

**Comment by woliveiras** [comment]
Pro site a gente cria um repo chamado site mano.

Esse aqui deixamos pras issues de formações de grupos de estudo. :)

**Comment by woliveiras** [comment]
Ou um **training-center.github.io**

**Comment by baltazarparra** [comment]
Não seria legal criarmos juntos com a galera? Tipo oque o pessoal fez aqui [brainstorm](https://github.com/frontendbr/eventos/issues/3)

**Comment by woliveiras** [comment]
Oorra, já tem até a issue pow. kkkk

Aqui, https://github.com/training-center/sobre/issues/46

Podemos até fechar essa do Logo e partir pro site.

Seria somente o repositório pro site mesmo pra que depois não fiquem issues de criação de grupo misturadas com coisas do site. Como algum bug que pode aparecer, por exemplo. :)

**Comment by baltazarparra** [comment]
Demoro mano. Partiu site então...
