### ISSUE TITLE
Criar um PodCast como iniciativa do Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#5]
O @giovannicruz97 iniciou a ideia de criar um PodCast para ajudar os iniciantes.

Vamos usar essa issue para discutir como tudo funcionará.

## Passo a passo para criação do projeto

- [ ] nome do podcast
- [ ] como serão postados os episódios
- [ ] onde serão listados os episódios

**Comment by woliveiras** [comment]
Os episódios podem ser postados no [Soundcloud](https://soundcloud.com/), pois facilita embutir em qualquer lugar.

Se for interessante podemos usar o Medium para listar os episódios dentro da [publicação do Training Center](https://medium.com/trainingcenter)

**Comment by giovannicruz97** [comment]
## A ideia
Queremos fazer um podcast inspirado no DNE, Hipsters.tech, NerdTech e afins. O propósito é compartilhar conhecimentos, discutir pautas e ter entrevistados notórios da comunidade de programação do Training Center e importantes no mundo da tecnologia.

## Nomes
Estamos trabalhando nisso, porém já recebemos algumas indicações e esperamos receber muito mais. Segue abaixo alguns nomes sugeridos

* PupiloCast
* TCast
* Training Cast
* Training Center Cast
* Junior Dev Cast
* ...

## Postagem dos Episódios
Uma ideia seria popular a página do (Medium)[https://medium.com/@trainingcentr] com conteúdo feito pela nossa comunidade. Acho uma boa ideia, usarmos essa plataforma como "QG" das nossas produções, além das nossas redes sociais. A utilização do soundcloud para a postagem é uma ótima ideia. Enquanto não temos nosso domínio próprio, podemos utilizar esse mix muito bem.

## Como participar?
Se você se interessa por participar desse projeto, fale comigo em qualquer rede social, seja aqui no GitHub, no Telegram, no Slack ou até mesmo nessa Thread, iremos precisar de pessoas que gostem não só de falar, mas como pessoas que gostem de edição de áudio, sugestões de pauta e pessoas que gostem de colher informações sobre artigos e textos que possam ajudar no Podcast. Todos são bem vindos!

> May the force be with you!

**Comment by woliveiras** [comment]
Boa, @giovannicruz97 

Sobre o nome, eu voto por `Training Casts`, por que remete legal ao Training Center.

O logo do cast pode até ser esse `TCast` sitado na sua reposta ein, que tal?

**Comment by 88patota** [comment]
TCast +1

**Comment by kvnol** [comment]
Eu curto o nome `Training Center Cast` porque remete, diretamente, ao Training Center e não tão amplo para qualquer coisa como o `Training Casts`.

**Comment by giovannicruz97** [comment]
@woliveiras, acho bacana a ideia do Training Casts com a logo TCast, junto com o logo do TRex haha. @kvnol a ideia do Training Casts parece ser boa, pois mantém o "ambiente" do Training Center e (mais pra frente) podemos ter Training Blogs e assim vai. Vamos deixar essa thread aberta até sexta para ver se novas ideias aparecem. Obrigado pela colaboração de todos!

**Comment by woliveiras** [comment]
O milestone dessa issue está até dia 23, @giovannicruz97 😬

**Comment by felipeorlando** [comment]
TCast +1

Precisando de um tapa buraco, tamo ae haha

**Comment by MarianoJhuninhu** [comment]
Training Casts com a logo TCas ++ 😄

**Comment by cleisoncarlos** [comment]
DevCast

**Comment by kellfluz** [comment]
Alô pessoal, vou dar pitaco também! 
Gostei muito do Traning Cast com a logo TCast como disse o @giovannicruz97. Em último caso (mas só em último mesmo!), também gostei do PupiloCast haha

Sobre a postagem, enquanto eu lia já pensei logo de cara no Soundcloud e a ideia de publicar no Medium também vai ajudar a divulgar bastante. 

Poderíamos procurar também futuramente de cadastrar o podcast naqueles apps de celular que organiza/linka com o feed e baixa automático (não sei bem como funciona, mas posso procurar). Só uma ideia. =)

**Comment by 88patota** [comment]
concordo com você @kellfluz com o lance de deixar tipo no app de posdcast do ios por exemplo. isso seria top demais :1st_place_medal:

**Comment by manzoliric** [comment]
Training Casts com a logo TCast 👍

**Comment by adeonir** [comment]
Porque não `TCast` como nome e logo?

**Comment by nandumoura** [comment]
TCast logo e nome acho legal

**Comment by khaosdoctor** [comment]
Training casts acho que remete algo mais a aulas, mas é um nome bacana

**Comment by hjdesigner** [comment]
Meu voto de nome vai para Training Casts.

**Comment by marciosancho** [comment]
Training Casts +1

**Comment by ogilvieira** [comment]
TrainingCast tudo junto e sem plural

**Comment by anaebastos** [comment]
Olá... Então, vou fazer de advogado do diabo:
Training tem a ver com treino, pode confundir com atividade física...

Agora vms pensar em algumas coisas técnicas:
- Qual o tema central?
- Quem será (ão) host(s)?
- Qual a duração em média de um episódio?
- Qual a periodicidade (é mto interessante colocar na rotina das pessoas)?
- Como será gravado (presencialmente ou remoto)?
- Será gravado um áudio único com todos ou áudio separado?
- Quem irá editar? Qual programa usará para edição? (Podcasts de podcast: Alô Ténica, Papo Editado, Os Comentadores, Metacast)
- Site para introduzir (www.mundopodcast.com.br)
- Grupo no Telegram de Podcasters Ouvintes e Editores (https://t.me/podcasters)

**Comment by adeonir** [comment]
> Training tem a ver com treino, pode confundir com atividade física...

Realmente, por isso achei `TCast` um bom nome.

Já trabalhei com audio/video, mas faz um tempinho que não mexo com isso. Nada que umas dicas não reavivem a memória.

Posso dar uma mão com isso.

**Comment by allangrds** [comment]
Concordo com o @adeonir, sem contar que `Training Casts` eu acho um nome mto grande. Eu não iria me referir ao casta falando com amigos "Ow, vc ouviu o Training Casts #13 ?". Voto em `TCast`.

Gostaria de participar @giovannicruz97. Não sou monstro da edição, mas acho que dá pro gasto :P.

**Comment by ronaiza-cardoso** [comment]
separei alguns links que podem ser interessantes aos criadodes: 

- https://mundopodcast.com.br/podcasteando/amper/

- https://mundopodcast.com.br/podcasteando/obs-studio-gravador-skype/

- https://mundopodcast.com.br/podcasteando/podtools/

**Comment by allangrds** [comment]
Aqui também tem uma material bom pra consulta:

- https://mundopodcast.com.br/podcasteando/

**Comment by adeonir** [comment]
Massa esse PodTools

**Comment by khaosdoctor** [comment]
Pode ser algo como CTCasts, porque ai podemos abreviar pra CTC (tipo DNE) e fica meio que uma alusão já ao canal

**Comment by kellfluz** [comment]
> Training tem a ver com treino, pode confundir com atividade física...

Realmente, pensando por esse lado. Para nós não tem problema porque vivemos nesse mundo, pra quem é de fora, pode realmente confundir.

**Comment by khaosdoctor** [comment]
> Para nós não tem problema porque vivemos nesse mundo

A gente já não faz muita atividade física mesmo ai não tem como confundir 🤣

**Comment by 88patota** [comment]
> Pode ser algo como CTCasts, porque ai podemos abreviar pra CTC (tipo DNE) e fica meio que uma alusão já ao canal

Mudamos os nomes para Training Center. Por isso estamos indo para a linha de TC ou TCC e etc.. :)

**Comment by giovannicruz97** [comment]
> Para nós não tem problema porque vivemos nesse mundo
> > A gente já não faz muita atividade física mesmo ai não tem como confundir 🤣

Eu faço poxa hahaha

**Comment by anaebastos** [comment]
Já pensaram em sair do "Pod" o do "Cast"? 
"Bora Programar"
"Papo de Desenvolvedor"
"Codando"

**Comment by 88patota** [comment]
> Já pensaram em sair do "Pod" o do "Cast"?
Acho bacana sair um pouco disso. Mas tb focar em algo direcionado a dev/programar fica pouco abrangente. Podemos falar de infra, qa, seo e etc...

**Comment by khaosdoctor** [comment]
> Já pensaram em sair do "Pod" o do "Cast"?
"Bora Programar"
"Papo de Desenvolvedor"
"Codando"

É que sair do cast não da a entender que é de fato um podcast 😕 

Se bem que, temos DNE ai né

**Comment by woliveiras** [comment]
Papo de Dev seria show também, ein!

**Comment by 88patota** [comment]
Agora que vi que misturei meu comentário com o quote da

**Comment by lflimeira** [comment]
Acho que seria legal deixar claro que está relacionado com tecnologia/desenvolvimento... Acho que Papo de Dev seria legal tbm ou algo como TechForAll, sei la só uma ideia kkk

**Comment by kvnol** [comment]
`Training Dev Cast` ou só `Training Dev` seria legal também, para não desfocar muito do Training Center.

**Comment by khaosdoctor** [comment]
Voto em Papo de Dev

**Comment by allangrds** [comment]
Já temos bastantes nomes. Acho que podiam abrir uma votação geral.

**Comment by woliveiras** [comment]
Bem observado @allangrds 

Vou agilizar isso PRA JAAA!

**Comment by woliveiras** [comment]
Galera, criei o form para votarmos no nome para o Podcast: https://goo.gl/forms/5TrY6VWLXDlMDV7A2

**Comment by woliveiras** [comment]
@giovannicruz97 tudo bem se deixarmos o formulário até dia 01/05?

**Comment by ranosi** [comment]
Uma coisa que poderia ser agregado ao programa seria falar sobre tecnologias que algumas empresas usam, tipo a Netflix utiliza tal coisa de tal forma. Isso poderia expandir pra metodologia que usam e assim por diante.
Poderia ser um quadro no podcast. Não vejo muita gente falando sobre isso e acho que seria legal pra se conhecer.

**Comment by khaosdoctor** [comment]
Eu acho a ideia do @ranosi bem dahora, poderiam ser casts especiais ao longo do mês (tipo, toda ultima sexta sei lá) pra gente chamar alguém que trampa nessas empresas e falar sobre a stack

**Comment by allangrds** [comment]
@woliveiras A votação já acabou ? Qual o nome vencedor ?

**Comment by woliveiras** [comment]
Fala @allangrds!

Seguramos um pouco por que estávamos fazendo várias mudanças ao mesmo tempo e um assunto estava atrapalhando o outro.

Assim que terminarmos o site vamos cair matando nessa ideia aqui. \o/

**Comment by FeelipePM** [comment]
O nome do cast poderia ser training conect cast 
Sigla  TCC

**Comment by danilosilvadev** [comment]
Vou dar mais umas ideias aqui:

### Programas a se usar pra gravar com qualidade e editar:

- Audacity(grava áudio local(host) com qualidade e edita áudios)
-  Atube(Grava áudio recebido, ou seja, dos convidados)

### Formato

O formato pode ser de no máximo 4 pessoas por cast. 2 fixos e 2 convidados, sendo feito um programa a cada 15 dias inicialmente pra não fazer demais. As calls podem ser via discord que tem a melhor qualidade e com duração máxima de 1 hora, na edição o programa ficará em torno de 40 min.

Todo programa necessita de uma pauta, que são tipo uns tópicos onde o host vai coordenar os participantes para não ficar demorando muito em um assunto ou pouco em outro.

Cada programa necessita ter descrição(resumida) e os contatos dos participantes por escrito nos posts.

### Onde exportar

- Soundcloud
- Podcastaddict
- Itunes
- Spotify

### Nomes

Os nomes não precisam ser necessariamente haver com o training center, afinal o nome trainning center não remete a código ou programação, pode ser qualquer coisa. E quando pesquisarem o podcast não vão achar a menos q já conheçam o CT então acho uma limitação isso. Abaixo umas dicas:

- Devsbr
- OpenSourcebr
- Cleandevs
- façoprogramacast (esse seria muita zoeira)
- funcastbr (de function js manja?)
- bugcast
- codando

etc

**Comment by FeelipePM** [comment]
Audacity da para criar a gravação geral
Edição pra para usar o reaper, antes de tudo da para passar o áudio no levelator, posso criar um passos pra galera, acho bacana um cast não muito grande 1 host sempre trazendo convidados é bacana 

Sent using the free mail.com iPhone App

**Comment by khaosdoctor** [comment]
Eu não sou muito bom de edição, mas usava o Audition antes, pena que é pago.

Acho que **CodandoCast** é bem bacana!

Topa parceria comigo no host ai @woliveiras? kkkkk

**Comment by FeelipePM** [comment]
Woliveras de host eu apoio

Sent using the free mail.com iPhone App

**Comment by woliveiras** [comment]
Topo, sim, @khaosdoctor 

:grimacing: 

Eu só não vou conseguir ajudar muito em toda a organização.

O @danilosilvadev já disse que ajuda na edição e sei que ele manja disso, então já temos uma equipe se formando:

Editores:

- @danilosilvadev 

Hosts:

- @khaosdoctor 
- @woliveiras
- @giovannicruz97 

A social media pra divulgação do projeto pode ser o nosso Twitter mesmo e o site pode ser hospedado no GitHub Pages.

Se o nome tiver muito a ver com open source, se chamarmos uma galera que trabalha com tecnologias proprietárias o pessoal que escuta pode achar ruim. Então tem que ser algo mais voltado a desenvolvimento no geral, mas não limitando a código, por que temos iniciativas de design e até gestão de projetos também.

Existe um cast bem louco que se chama Front End Happy Hour. Poderíamos criar um nome desse estilo.

`Training Center Coffee Break`. - Só uma sugestão bem tosca por que eu sou ruim de nomear as coisas gente.

**Comment by khaosdoctor** [comment]
Ai temos que invocar o @danilosilvadev para nomear as coisas kkk

**Comment by giovannicruz97** [comment]
@woliveiras eu n sou host tbm? :broken_heart:

**Comment by danilosilvadev** [comment]
Meu voto é para **FaçoProgramaCast** e pode ser apelidado de **FPcast**. Tem tudo haver com a nossa profissão e ainda uma inside joke. hehe agora que percebi q FPCast poderia se torna **FAPCast** mds kkkkkkk 2 inside jokes em um só nome, inception. aff aposto q n vao escolher esse nome kkk

**Comment by danilosilvadev** [comment]
@giovannicruz97 é bom ter 2 hosts e ae nos programas chama 2 convidados pra ir alternando gentes. Porém se tiver 3 hosts só vai poder chamar 1 convidado, se ficar mais de 4 na call fica meio bagunçado. Menas gentes, fica mais clean o programa, áudio e tempo distribuído pra cada um falar.

**Comment by danilosilvadev** [comment]
lembrando da entrevista do @woliveiras pode ser **PastelCast**, que tem haver com o q ele falou do dia-a-dia do coder q é q nem fritar pastel.

**Comment by woliveiras** [comment]
OOOOOOO, DANADO! 

Verdade, gente... O @giovannicruz97 quem teve toda a ideia. Como iríamos deixar o cara fora dessa? 

Pode não.

**Comment by khaosdoctor** [comment]
__PastelCast__ aprovado haha pena que não remete muito a desenvolvimento.

Quando a ideia dos hosts, isso varia, o NerdCast por exemplo tem sempre mais de 5 caras, o Hipsters também tem mais as vezes. Depende do assunto :)

Mas podemos revezar os co-hosts haha

**Comment by danilosilvadev** [comment]
revezar co-hosts acho ideal pq vcs vao testando combinações e tds se divertem. **PastelCast** não remete mas acho q é isso ae, é ideal pq é diferente, engraçado, tem haver com programação pra quem ta na área.A divulgação é só trabalhar um pouquinho e tals, mas é original e acho q só nós seremos o **PastelCast** hehe Lembrando q hipster tbm n remete a tecnologia e fizeram mesmo assim

**Comment by woliveiras** [comment]
Pastel na veia! Se ninguém tiver objeção, acredito que podemos até criar o repositório. 😂😂😂

**Comment by kivervinicius** [comment]
PastelCast, da hora!!

**Comment by giovannicruz97** [comment]
Eu queria mto participar. Não tenho problema em ser co-host, até prefiro ser co-host, mas gostaria de ter participação ativa

**Comment by danilosilvadev** [comment]
**Recadinho do editor**

- No começo dos programas é bom q tds se apresentem começando pelo @woliveiras, e digam uma frase ou jargão ou qualquer coisa q os diferencie, pelo amor...
- Quando for fazer @woliveiras crie tópicos e quando for trocando eles, fale em voz alta tópico 2, tópico 3 etc... eu vou retirar isso e adicionar uma transição sonora. Ok?
- Os programas devem demorar no máximo 1 hora de gravação, se puder bem menos tá? ae eu na edição vou reduzir mais, não vão dar uma de nerdcast logo de cara, poucos(raríssimos) tem moral pra fazer um programa de 2 horas interessante, e facilitem a vida do editor please.
- @woliveiras vc é o único host, os outros são da bancada. Alguns fixos e alguns q revezam. Vc tem q organizar o programa, trazer os calados pra falarem mais no programa e mediar os q falarem muito pra n tomar td o espaço. Claro, sem ditadura, só to falando q vc precisa se preocupar com o equilíbrio, e tbm com o foco pra n começarem falando de react e terminarem metade do programa falando de DBZ.
- Ouvi falar q o programa OBS é bom pra gravação, se for mesmo show q ae grava os audios separadamente e sincroniza direto nele. Se n for vai ter q usar 2 programas pq o áudio do host tem q estar perfeito e n gravado da call.

Dúvidas?

**Comment by woliveiras** [comment]
Opa, eu tenho um problema mano: eu não posso ser o host.

Por que da maneira que estávamos levando, seria o @giovannicruz97 e o @khaosdoctor os caras e eu um cara que ajuda.

Eu não vou conseguir tirar o tempo direto pra gravar, ai eu ferraria todo o rolê. Já os meninos estão se planejando para isso.

Como podemos fazer?

**Comment by woliveiras** [comment]
A partir de já podemos seguir para o repositório do [PastelCast](https://github.com/training-center/pastelcast)?

Lembrando que temos que fazer o podcast em um formato que pode ser copiado. Uma vez open source, temos que criar algo que pode ser "forkado". :grimacing:

**Comment by woliveiras** [comment]
Podemos fechar essa issue?

**Comment by danilosilvadev** [comment]
Então @woliveiras é só um programa a cada 15 dias, tem ctz q n rola vc de host n? se n for vc manda quem for falar comigo pra acertar o q eu vou precisar.

Sobre ser forcado, o lance é escrever lá o formato, temas, regras, dicas e programas usados na edição, técnicas e etc. Se quiser vai criando os arquivos md q vemos como preencher.

**Comment by danilosilvadev** [comment]
Pode fechar se quiser.

**Comment by FeelipePM** [comment]
Precisando de ajuda com alguns software de edição i tal. Tenho um cronograma de um cast aqui com um projeção de gravação até a edição 

Sent using the free mail.com iPhone App

**Comment by woliveiras** [comment]
Infelizmente não consigo me comprometer, @danilosilvadev.

Por que senão posso falhar miseravelmente com a galera. :cry:

**Comment by danilosilvadev** [comment]
ok, e sobre  o @FeelipePM é só me mandar o link do repo ou do q vc tiver pra eu dar uma lida e ver se me ajuda nos esquemas

**Comment by FeelipePM** [comment]
Danilo, vou editar aqui certinho e te mando por aqui o arquivo anexado pode ser?

Sent using the free mail.com iPhone App

**Comment by danilosilvadev** [comment]
ok

**Comment by giovannicruz97** [comment]
Eu to ai pra ajudar, como será quinzenal podemos nos organizar. Se @woliveiras não puder, seria uma pena :broken_heart: haha

**Comment by khaosdoctor** [comment]
@giovannicruz97 Topa ser o host cara? Eu tenho alguns problemas em me comprometer 100% do tempo com a coisa toda, mas eu posso estar presente em pelo menos 80% deles (infelizmente vão ter algumas coisas que eu não vou conseguir participar...) ai podemos ter um host mais fixo, e você já falou que queria ter uma participação ativa :D 

Ai podemos revezar eu e o @woliveiras ou ambos em alguns podcasts para poder ter coisas legais pra falar e fazer! O que acha?

**Comment by woliveiras** [comment]
O @giovannicruz97 já ia ser host, gente...

Nós que vacilamos e começamos tomar frente, mas quem a pessoa que deu a ideia e se comprometeu em fazer foi ele. :grimacing: 

Somos acelerados pa garai! UHAUHHUAA

Eu vou querer participar sempre que tiver um tempo, véi. Curto demais! :smile:

**Comment by khaosdoctor** [comment]
Estou a favor do @woliveiras também, acho que o @giovannicruz97 deveria ser o host e vamos alternando quem quiser participar 😄

**Comment by 88patota** [comment]
podemos fazer uma votação em algum canal do Slack mesmo. para um host novo a cada X tempo tb!

**Comment by giovannicruz97** [comment]
Gente, qualquer ajuda é bem vinda, eu sou a favor de quanto mais gente melhor! haha

**Comment by khaosdoctor** [comment]
@patota Sim! Seria bem legal, acho que é mais interessante trocar os cohosts de tempos em tempos, mas o host é a cara do podcast sabe? Então não sei se é uma boa ideia

**Comment by thmendes** [comment]
Pode ser no formato do Lambda3, onde existem vários hosts. =)

**Comment by ericmadureira** [comment]
Caramba, que vacilo eu não ter visto essa iniciativa antes. Quero participar! Posso representar os devs iniciantes no meio dos hosts já tão experientes. Tenho disponibilidade pra participar de episódios, ajudar na edição, o que precisar!

Ahh, e gostei do estilo de nome sem "cast" ou "pod", só precisa ser único :grin:
Gostei de PastelCast xD

**Comment by FeelipePM** [comment]
O nome também poderia ser papo dev

**Comment by woliveiras** [comment]
Galera, vou fechar essa issue para discutirmos a partir do repositório do projeto e ficar tudo centralizado no local certo. :grimacing: 

Bora pra lá!
https://github.com/training-center/pastelcast/issues/1
