### ISSUE TITLE
Grupo de estudos Nodejs

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#5]
Formação de grupo para estudar Nodejs

**Comment by WendellAdriel** [comment]
To dentro :+1:

**Comment by LarissaAbreu** [comment]
Opaa topo também :neckbeard:

**Comment by fauker** [comment]
Tô dentro. :+1:

**Comment by VictorVoid** [comment]
Tô dentro o/

**Comment by lucasbento** [comment]
Também tô dentro!

**Comment by woliveiras** [comment]
Aqui já deu 5 peões! Vocês já podem criar um nome pro grupo de vocês e abrirem uma nova issue para discutirem horários e tudo mais. :smile:
