### ISSUE TITLE
Como levar o Training Center para as escolas e faculdades

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#56]
Como parte da nossa missão de ajudar a sociedade, visamos chegar nas escolas e faculdades públicas e privadas para disseminar conhecimento.

Temos alguns planos para executar essa ação, porém gostaríamos de pedir sugestões de vocês (comunidade).

## Objetivo

**Em escolas**

Principalmente em escolas pulicas, pois nas escolas particulares já temos casos em que é ensinado programação no ensino médio.

- ensinar programação para adolescents em fase final da escola (2 e 3 ano do ensino médio)
- mostrar algumas carreiras que esses adolescentes podem seguir ao se envolver com desenvolvimento de software (front, back, mobile, ux, ui, agile, gerencia, etc)

**Em faculdades**

Sabemos que as faculdades não conseguem trazer conteúdo do mais atualizado para os alunos por n motivos, por isso queremos levar workshops e palestras para as faculdades para nivelar o conhecimento dessas pessoas com o que é pedido no mercado de trabalho.

## O que precisamos discutir nessa issue

Aqui precisamos **somente levantar ideias** do que podemos fazer. Não devemos discutir cada ideia dentro dessa issue, pois ficaria perdido entre sugestões e planejamentos. Assim que tivermos diversas ideias serão abertas outras issues para discutir como executar cada uma.

**Comment by vicenthy** [comment]
Acho que um sistema de parceria seria legal e tbm acho que  a partir do 7°/8° ano já seria legal iniciar os estudos visto que nessa fase seria legal mostrar mais utilidades da matemática.

**Comment by alinebastos** [comment]
É verdade! Lá pelo 7º/8º ano o pessoal já começa a perguntar "mas pra que eu vou usar isso???" haha. Aí a gente explica :D

**Comment by vspedr** [comment]
Na faculdade onde estudei, todo ano tem uma semana dedicada a palestras, workshops e minicursos em diversas áreas de tecnologia, que podiam ser oferecidos por alunos ou pessoas externas, era só combinar com a organização. 
Seria legal ter uma forma de centralizar:
- pessoas que oferecem esse tipo de conteúdo, de forma que um organizador de evento pode consultar e entrar em contato com essas pessoas.
*e/ou*
- eventos abertos a receber novos conteúdos, e os palestrantes poderiam consultar e se inscrever nesses eventos.

Não sei se já existe alguma iniciativa desse tipo, mas é o que me veio em mente pro caso das faculdades

**Comment by vsanrocha** [comment]
Acho legal organizar uns meetups em escolas.

**Comment by giovannicruz97** [comment]
Aqui no **IFSP Campus Campos do Jordão**, se eu conversar direitinho com a diretoria, podemos fazer uma **Semana da Programação by Training Center** ou coisa do tipo. Caso tenhamos sucesso em trazer mentores, pupilos e o pessoal da comunidade (não só do TC), podemos expandir o modelo para outras faculdades.

**Comment by macchico** [comment]
Tambem acho que nas faculdades, seria interessante algo ligado ao TCC(TG) dos alunos. Como todos tem que passar pelo temido trabalho final de graduacao, os alunos ficariam mais dispostos e curiosos ao estudar e ou conhecer algo que poderiam ajuda-los a desenvolver, por estarem mais preparados, o seu TCC de forma mais agil, natural e facil. Desculpem a falta de acentuacao, esse meu teclado e alemao... :(

**Comment by tjoaquini** [comment]
Gostei da ideia! Estudo Banco de Dados na FATEC de Bauru e pelo que pude perceber até agora, tem um gap muito grande entre o que eles ensinam aos alunos e o que o mercado está exigindo. Vejo algumas possibilidades do TC atuando diretamente com faculdades:

- Palestras diversas de membros do TC (principalmente sobre carreiras, como buscar informações por conta própria - assuntos que diariamente discutimos na comunidade);
- Incentivar Grupos de Estudos local e integrando com grupos de temas relacionados de outras faculdades;
- Embaixador TC (algum membro da comunidade que esteja interessado em divulga-la na faculdade que estuda);

Essas são algumas iniciativas que me vem em mente agora.

**Comment by giovannicruz97** [comment]
@tjoaquini Pefeito! O *gap* realmente é MUITO grande. Eu sempre falo isso p meus colegas de sala que não trabalham. Aliás, existem alguns lugares como Campos do Jordão que não possuem grandes empresas ou áreas, até então, não exploradas em TI. Com a chegada do Training Center nesses locais de maneira mais ativa, podemos garantir networking p essas pessoas e até oportunidades em projetos open - source ou oportunidades de emprego.

**Comment by woliveiras** [comment]
Muitas ideias legais, galera! 

Eu vou fechar essa issue, pois coletei as ideias de vocês e vamos compilar e depois montar um plano para começar a fazer isso.

Vocês são feras!

Valeu demais pela participação.
