### ISSUE TITLE
Adicionar informações organizacionais do Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#58]
Possuímos informações organizacionais que deveriam estar em algum lugar.

Acredito que o melhor lugar seria aqui no `/sobre` através de uma documentação de como tudo funciona.

## Objetivo(s) desta issue

- discutirmos como organizar as informações de administração da nossa comunidade
- concentrar o máximo de informação organizacional possível para passarmos para a documentação

### Times

Hoje possuímos times separados por canais ou projetos, onde:

- design: cuida de todo o design do Training Center, gerido pelo @adeonir 
- conteúdo: revisam posts e vídeos e facilitam para pessoas enviarem seus conteúdos para o Training Center, o Medium é gerido pelo @khaosdoctor e o YouTube pelo @lbighetti 
- divulgação: cuidam das redes sociais e buscam parcerias em canais de divulgação exeternos, gerido por mim
- mentoria: cuida do repositório e facilita a vida de pessoas que entram como mentores(as) e mentorados(as), gerido pelo @hdamaich 
- study-groups: cuida do repositório do grupos de estudos e facilita a vida de quem deseja criar grupos de estudos, gerido pelo @lbighetti 
- spreading-code: projeto novo, ainda em fase de construção, gerido por mim
- dojos: cuida do repositório de dojos e ajuda as pessoas a fazerem dojos online junto com nossa comunidade, gerido pelo @lflimeira 
- hackathon: cuida do repositório do hackathon e organiza os eventos desse tipo da nossa comunidade, gerido pelo @danilosilvadev 
- core: time responsável pelo Training Center que cuida do Slack, moderação de toda a comunidade e facilita a vida de outros times, gerido por mim

Dentre os times, temos canais no Slack que são times, porém não oficializados ou que não são específicos de um projeto ou canal externo ao Training Center:

- canal de mulheres: gerido pela @alinebastos, ajuda as mulheres a se sentirem mais confortáveis dentro da nossa comunidade e as empodera para novas iniciativas e maior movimentação feminina em nossos projetos
- canal staff: onde estão todas as pessoas que fazem parte de algum time dentro da comunidade

Fora esses times, temos projetos sem responsáveis direto, ainda:

- meetups: cuida do repositório de meetups e ajuda pessoas a criarem novos meetups pelo Brasil afora
- weekly: cuida do repositório da weekly e é responsável por coletar as novidades e notícias importantes **do Training Center** para postarmos no Medium
- primeiro-trampo: cuida do repositório e facilita para quem deseja colocar suas descriçẽos no nosso repositório, divulga a lista de pessoas que busca vagas no nosso LinkedIn e em grupos de vagas de trabalho
- forum: cuida do nosso repositório, ajuda pessoas a melhorarem suas descrições, modera as respostas
- code-review: cuida do nosso repositório, ajuda pessoas a melhorarem suas descrições, modera as respostas
- code-house: cuida do nosso repositório, ajuda pessoas a melhorarem suas descrições, modera as respostas

O modelo de times atual já não é efetivo e devemos rediscutir isso. Caso não faça sentido guardarmos essa informação em nenhum lugar, podemos desconsiderar este tópico.

### Onboarding nos Times

Quando entra alguma nova pessoa nos times, essas pessoas devem ser convidadas ao respectivo time no GitHub e no canal do Slack xxx-team, onde xxx é o nome do time.

Essa pessoa também deve ser convidada a olhar nosso [onboarding](https://trello.com/b/EDYHi1E3/onboard-training-center), caso ainda não tenha visto.

Também deve ser adicionada no canal `#staff`, onde estão todas as pessoas que participam de maneira ativa nos projetos do Trainining Center.

Se você souber de alguma outra informação organizacional, comente aqui. :) 

## Importante

Caso tenha algum comentário fora dos objetivos da issue, abra outra issue para não saírmos do foco. :heart:

**Comment by khaosdoctor** [comment]
Cara eu acho que está muito bom, ta bem conciso e muito explicado

**Comment by woliveiras** [comment]
Tudo foi reformulado (novamente) e essa issue não faz mais sentido. 

Amo vocês! :heart:
