### ISSUE TITLE
Unir boards do Trello em um documento

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#59]
Possuímos diversos boards no Trello onde as pessoas devem ser convidadas a participar.

Hoje não temos isso centralizado em algum lugar.

Devemos criar um documento aqui e colocar links para esses boards.

## Boards

- blog: https://trello.com/b/mREvfMxR/blog
- redacao: https://trello.com/b/uQPN3frF/redacao
- onboarding: https://trello.com/b/EDYHi1E3/onboard-training-center
- conteudo: https://trello.com/b/i3KqFY8a/conteudo
- hackathon: https://trello.com/b/8ad5yI81/hackathon
- site: https://trello.com/b/KAf1zyhL/site

Pode ser um arquivo `boards.md` dentro da pasta **admin**.

**Comment by khaosdoctor** [comment]
Acho que dentro de pastas fica meio perdido se as pessoas não souberem aonde achar, se tiver um link pra isso no README seria mais fácil

**Comment by lflimeira** [comment]
Concordo com o @khaosdoctor, temos que deixar as informações com fácil acesso.

**Comment by woliveiras** [comment]
Isso. Seria isso mess. :)

**Comment by woliveiras** [comment]
Removemos os boards, então essa issue não faz mais sentido.

Amo vocês! :heart:
