### ISSUE TITLE
Melhorar os projetos do Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#6]
Visando entregar uma comunidade mais forte e projetos mais efetivos para as pessoas que nos acompanham precisamos melhorar alguns pontos nos nossos projetos.

Nessa issue vou listar as necessidades individuais de cada projeto para discutirmos sobre o que precisamos e até possíveis maneiras de solucionar os problemas.

Necessidades individuais de cada projeto:

## [Slack](https://ctgroups.slack.com)

- precisamos de moderadores para manter a organização no chat
- precisamos criar iniciativas para movimentar mais as discussões no chat
- precisamos centralizar os links postados pelas pessoas em algum lugar de fácil acesso depois

## [Blog](https://medium.com/trainingcenter)

- precisamos de escritores para trazer mais conteúdo sobre carreira
- precisamos de pessoas ativas para compartilhar os posts nas demais comunidades de desenvolvimento de software

## [Mentoria](https://github.com/training-center/mentoria)

- precisamos de mais mentores ou planejar um tempo limite de mentoria por pessoa para liberar os mentores e mentoras para pegarem mais pupilos
- precisaremos de ajuda para fazer a triagem de pupilos quando isso for implementado

## [Site](https://github.com/training-center/training-center.github.io)

- precisamos de um time para codificar o layout proposto e depois para manter o projeto

## Alguns projetos que estão sem movimentação

Esses projetos podem ser descontinuados dependendo da conversa na issue #4.

* [Study Groups](https://github.com/training-center/study-groups)
* [Projects](https://github.com/training-center/projects)
* [Materials](https://github.com/training-center/materials)

**Comment by felipeorlando** [comment]
Acredito que precisamos de um lugar para conexão dos mentores com pupilos. Um pequeno sistema dá conta disso, ein! 😄  

Se acharem uma boa ideia, podemos começar a falar siobre e colocar isso num wire. 👍

**Comment by woliveiras** [comment]
Opa, essa discussão vai entrar em pauta nessa outra issue aqui: #4.

Vamos montar um time para cuidar do projeto Mentoria e esse time vai ficar responsável por criar essa plataforma, @felipeorlando. 😄 

Agora vai ficar bem da hora!

**Comment by 88patota** [comment]
Posso ajudar com a parte do blog - conteúdo.

**Comment by irwing-max** [comment]
Nâo deixem o dojo morrer...acho que podemos melhorá-lo também

**Comment by woliveiras** [comment]
Bem lembrado @irwing-max

**Comment by khaosdoctor** [comment]
Eu posso ajudar no Blog também, acho que vale a pena criarmos uma plataforma legal de conteúdo, até para poder colocar no site, ou então montar um blog mesmo dentro do site para produzir conteúdo próprio.

Quanto aos mentores e pupilos, acho que vale a gente montar uma organização em um sisteminha pra galera se cadastrar e ver quais são os mentores disponíveis para poder pegar e quais são as áreas de interesse e etc, podemos usar o [repl.it](https://repl.it/teacher) porque ele tem uma parte de classrooms que dá pra fazer um dojo bem legal, também passar umas atividades bem bacanas de mentor pra pupilo

**Comment by woliveiras** [comment]
Achei o repl.it muito maneiro, @khaosdoctor 

O Blog que falamos é a nossa publicação no Medium :)

**Comment by khaosdoctor** [comment]
Sim eu acho que consigo ajudar com conteúdo @woliveiras

**Comment by woliveiras** [comment]
@khaosdoctor 

https://youtu.be/y-dWO3L_y4g?t=3s

**Comment by woliveiras** [comment]
Galera, alguns repositórios serão deletados como consta nessas issues: 

https://github.com/training-center/projects/issues/2
https://github.com/training-center/materials/issues/3
https://github.com/training-center/questoes-para-entrevistas-front-end-dev-pt-br/issues/2

Pensei em unir o projects e materials dentro do Study Groups se assim fizer sentido.

Acho que não precisamos do materials, pois o material de estudos que usamos é a internet e acredito que o projects não está fazendo sentido uma vez que quase não foi atualizado, o mesmo acontece para o questões de entrevistas front end.

**Comment by woliveiras** [comment]
Galera, essa issue já pode ser fechada uma vez que foram definidas as moderações dos projetos e organização geral.
