### ISSUE TITLE
Grupo de estudos PHP

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/sobre#6]
Formação de grupo para estudar PHP

**Comment by fabricio1soares** [comment]
Alguma ideia para desenvolver?

**Comment by alannaidon** [comment]
Se tiver vaga, eu topo õ/

**Comment by WendellAdriel** [comment]
@fabricio1soares ainda estamos formando o grupo pra começarmos os estudos!!! :wink:

@alannaidon tem vaga sim, junta aew

**Comment by SoullPower** [comment]
Opa estou dentro :D

**Comment by cvalentefilho** [comment]
To dentro

**Comment by davidasimoes** [comment]
Quero participar tbm, mas não sei usar github ainda, paciência cmg. :)

**Comment by ValdirCamargo** [comment]
Tô dentro

**Comment by diasEduardo** [comment]
faz um tempo que vi php, bora praticar -q

**Comment by andreamant** [comment]
Bora estudar :D hehe

**Comment by woliveiras** [comment]
Caramba, deu 9 caras nesse aqui! \o/

Já da pra separar essa issue.

Peguem os 5 primeiros pra um grupo e os outros abrem uma nova issue, esperando mais um pra equipe.

Seria interessante o @cvalentefilho e o @WendellAdriel ficarem em equipes separadas, pois sei que os dois já manjam, então podem ajudar mais quem tiver menos experiência.

Que tal?

Parabéns a galera interessada em praticar! \o/
