### ISSUE TITLE
Devemos unir os boards de conteudo, redacao e blog?

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#60]
Possuímos alguns boards no Trello que parecem não ter propósito devido a mudarmos um pouco a maneira de agir.

blog: https://trello.com/b/mREvfMxR/blog
redacao: https://trello.com/b/uQPN3frF/redacao
conteudo: https://trello.com/b/i3KqFY8a/conteudo

Hoje temos um canal `#conteudo` onde mandamos os posts para revisão e usamos threads para discutir sobre o post, então o board **redacao** já não faz mais sentido.

O board **blog** ainda parece fazer sentido visto que as pessoas podem pedir posts, mas será que não devemos unir tudo dentro do board **conteudo**?

*related to #59*

**Comment by khaosdoctor** [comment]
Eu acho que sim. Tudo é conteúdo, youtube, redação, blog e etc

**Comment by lbighetti** [comment]
@woliveiras fez isso hoje mandou muito, fechando!
