### ISSUE TITLE
Time de tradução

### ISSUE THREAD

**Issue by maaryhabad** [training-center/sobre#64]
Eu fiz esses dias a tradução de um tutorial de Angular e achei SUPER divertido de fazer. O que acham da gente criar um time que traduz tutoriais pra deixar dentro do Training Center?

**Comment by maaryhabad** [comment]
Só completando a proposta, as pessoas mandariam links de artigos, e nós faríamos a tradução e disponibilizaríamos o material por aqui mesmo.

**Comment by alinebastos** [comment]
Mariana, foi do NgGirls? Eu traduzi esse tb :D 
Eu acho ótima a ideia!

**Comment by maaryhabad** [comment]
Foi sim!

**Comment by lbighetti** [comment]
Acho top!

**Comment by maaryhabad** [comment]
Então, só precisaríamos ver como ficaria o repositório... Se alguém puder colaborar com essa parte (sei bem pouco de como é organizada a informação aqui no Git, talvez seria ideal a gente fazer um novo repositório pra controlar as traduções e depois postar no medium), aceitando sugestões

**Comment by marrcelo** [comment]
Também gostei da ideia e posso ajudar a traduzir.

**Comment by khaosdoctor** [comment]
Galera, eu acho que podemos nos juntar a Larissa no https://github.com/devtranslate que é um projeto muito bacana que eu já ajudei e continuo ajudando. Não sei se ela está aqui, mas podemos ver se conseguimos conversar para unir as duas coisas ao invés de segregar :smile: 

(Será que eu consigo chamar a @larismourullo aqui?)

**EDIT**: CONSIGO!

**Comment by larismourullo** [comment]
@khaosdoctor chamou e eu apareci 😄 
Realmente podemos juntar em vez de segregar, sem contar o retrabalho. Se tem coisa feita, melhor que recriar é ajudar, e implementar <3

**OBS:** Eu tenho uma lista com diversos artigos muito bons de Front (pois estou lendo muito sobre atualmente) e tenho enviado sempre propostas pra tentar realizar a tradução. Um deles até já ta no medium do Devtranslate e atualmente estou fazendo o segundo. E também eu verifico sempre se não já existe alguma tradução pro mesmo, já que se já existe não tem motivo de realizar novamente outra tradução.

**Comment by alinebastos** [comment]
@larismourullo que maravilha, vamos juntar as forças, então :D

**Comment by khaosdoctor** [comment]
Aeee vamos então começar assim: 

- @larismourullo você aceitaria entrar no nosso Slack para podermos criar um canal de traduções? Assim colocamos todo mundo do time lá dentro e podemos ter uma comunicação mais eficiente

Como o DevTranslate é OSS então já podemos começar a fazer as PR's sem problemas e sem se preocupar com o modelo porque ele já está pronto, então é só mandar brasa!

**Comment by maaryhabad** [comment]
Massa! Vou dar uma olhada no DevTranslate

**Comment by maaryhabad** [comment]
Só é bom deixar Issues meio preparadas pro pessoal ir resolvendo...

**Comment by larismourullo** [comment]
@khaosdoctor já estou no slack, só não entro muito, mas vou começar a estar mais frequente lá.
E só tem uma coisa, as traduções de artigo são pelo medium (pois pode atingir uma quantidade maior de pessoas por lá), caso seja algo maior como documentações ou um site específico precisamos criar um repositório (pois é um conteúdo maior). 

Quem quiser já ir postando as traduções lá toda informação ta aqui: https://github.com/devtranslate/medium

**Comment by khaosdoctor** [comment]
Criei o canal já como #traduções no Slack, ai @larismourullo acho que é uma boa ideia a gente adicionar todo mundo que quer participar, mas se vc puder, colocar um guideline lá de contribuição porque você tem mais experiência haha ai dá uma explicada geral pra galera lá que vai ficar legal!

Vou fechar a issue aqui 😄
