### ISSUE TITLE
Proposta: Training Center Advocacy

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#67]
No mundo da tecnologia existem diversas pessoas que trabalham como developer advocate de empresas grandes, como Google, Facebook, Liferay, etc.

Essas pessoas fazem um importante trabalho que é a divulgação das marcas e reforço positivo de suas causas. Isso se chama **advocacy**.

> Advocacy, na atualidade, é utilizado como sinônimo de defesa e argumentação em favor de uma causa.

[O que é advocacy](http://www.politize.com.br/advocacy-o-que-e/)

Um exemplo que foi citado em uma conversa com o @felipefernandes e o Mauro é o [Docker Capitains](https://www.docker.com/community/docker-captains).

> Docker Captain is a distinction that Docker awards select members of the community that are both experts in their field and are passionate about sharing their Docker knowledge with others. 

Temos também [Google Developer Experts](https://developers.google.com/experts/), [Microsoft MVP](https://mvp.microsoft.com/) ou [Mozilla Reps](https://reps.mozilla.org/)

**GDEs**

> Google Developers Experts (GDEs) are a global network of experienced product strategists, designers, developers and marketing professionals actively supporting developers, startups and companies changing the world through web and mobile applications.

**MVPs**

> Microsoft Most Valuable Professionals, or MVPs, are technology experts who passionately share their knowledge with the community. They are always on the "bleeding edge" and have an unstoppable urge to get their hands on new, exciting technologies. They have very deep knowledge of Microsoft products and services, while also being able to bring together diverse platforms, products and solutions, to solve real world problems.

**Moz Reps**

> The Mozilla Reps program aims to empower and support volunteer Mozillians who want to become official representatives of Mozilla in their region/locale.

---

Nós precisamos de um sistema desses, pois já temos pessoas que fazem esse papel, porém não tem um reconhecimento por parte da nossa comunidade.

Temos pessoas do core team que palestram e falam da comunidade, como eu, @khaosdoctor, @akfzambrana, @lbighetti, @FernandaBernardo, mas também temos pessoas participam da nossa comunidade de maneira muito ativa e falam dela por aí e não tem um cargo no grupo.

Eu gostaria de propor um esquema de advocacy para nossa comunidade, onde reconhecemos:

- pessoas que escreveram ao menos 10 tutoriais para a nossa publicação no Medium
- pessoas que já foram mentores e mentoras e hoje não podem mais contribuir dessa maneira, mas continuam divulgando nossa comunidade
- pessoas que divulgam a comunidade em palestras de eventos e meetups
- pessoas que estão em escolas e faculdades falando da nossa comunidade
- pessoas que estão sempre ajudando de maneira ativa nos repositórios de nossos projetos

Teríamos, então, divulgadores(as), escritores(as) e commiters com o título de advocate.

---

Esta issue é para avaliar essa proposta e se ela for uma proposta legal, seguirmos com ela.

Os passos para finalizar essa issue são:

- validar se esta proposta é realmente legal para nosso contexto
- definir o nome do programa de advocacy
- definir como as pessoas conseguem os títulos

Os próximos passos, caso essa proposta seja aprovada:

- criar uma página de exibição dessas pessoas, bem próxima a do Google, pois é a que achei mais organizada em questão de divulgação das pessoas e informação para quem deseja se tornar expert: https://developers.google.com/experts/

**Comment by WendellAdriel** [comment]
Eu creio que seja muito válido fazer isso, pois dessa forma teremos como "prestigiar" pessoas que estão a ajudar a comunidade não só do Training Center, mas como um todo.

Quanto à definição de como conseguir esses títulos, gostei das ideias dadas pelo @woliveiras e apenas fazendo algumas alterações acho que os títulos podem ser dados com os seguintes critérios (quanto ao nome dos títulos, eu não sou muito bom nessas questões, então teríamos de ver alguém melhor para escolher os nomes dos títulos, então vou usar nomes genéricos), mas além dos critérios definidos a pessoa deve ser aprovada pela **Core Team** para avaliar outros aspectos como atitude da pessoa na comunidade, etc:

- **Escritor(a):** Quem escrever pelo menos 10 artigos para a publicação no **Medium**

- **Mentor(a):** Quem já foi mentor de pelo menos três pessoas e que no mínimo uma das pessoas tenha se tornado um Mentor

- **Divulgador(a):** Quem faz divulgação do projeto em eventos, conferências, faculdades,  etc

- **Coordenador(a):** Quem participa ativamente no Slack e no Github ajudando a administrar e organizar grupos, criar novos projetos e ideias, etc

Nesse caso o projeto de **advocacy** seria dividido em quatro categorias, onde cada pessoa pode ter apenas um título (para não virar bagunça). Se a pessoa se "classificar" para mais de um título ela deve escolher qual deles deseja que seja o ativo e o que será divulgado.

**Comment by khaosdoctor** [comment]
Nossa cara sensacional a ideia, eu tinha pensado algo do tipo um tempo atrás mas acabei não tocando a frente, mas essa questão de "advogados da marca" é uma coisa que dá muito retorno tanto para os membros quanto para a comunidade em si. Concordo totalmente com os pontos que o @WendellAdriel colocou aqui acima.

A minha única ressalva é como vamos conseguir manter o nível, teremos sempre que estar verificando e checando se o pessoal ainda está ativo.

**Comment by woliveiras** [comment]
> além dos critérios definidos a pessoa deve ser aprovada pela Core Team para avaliar outros aspectos como atitude da pessoa na comunidade

Siiiiim! \o/

Só precisamos definir aqui nessa issue quais são os critérios que o Core irá avaliar também.

Essa parte eu não concordo:

> no mínimo uma das pessoas tenha se tornado um Mentor

Não podemos obrigar outras pessoas a serem mentoras. Isso parte de cada um, sabe?

> Coordenador

Acho um título muito formal que denota muita autoridade dentro do grupo, sendo que nós mesmos evitamos autoridade ilegítima.

**Comment by woliveiras** [comment]
@WendellAdriel 

Ficaria algo como "Training Center Advocacy Writer", "Training Center Advocacy Mentor", etc.?

**Comment by woliveiras** [comment]
> A minha única ressalva é como vamos conseguir manter o nível, teremos sempre que estar verificando e checando se o pessoal ainda está ativo.

Teria que ter um critério de atividade?

Acho que isso não é importante, pois o próprio GDE não acompanha isso, sabe?

A pessoa ganhou a badge e se ela continuar ajudando, show, senão continuar ela não perde o título.

Isso não seria burocracia demais?

**Comment by WendellAdriel** [comment]
@woliveiras pensando bem concordo com tirar essa parte
> no mínimo uma das pessoas tenha se tornado um Mentor

Mas colocar tipo:
>Ter mentorado no mínimo três pessoas e ter sido mentor por pelo menos 3 ou 6 meses, o que acham?

Sobre os títulos seria algo tipo:

- **TCWA:** Training Center Writer Advocate
- **TCMA:** Training Center Mentor Advocate
- **TCPA:** Training Center Promoter Advocate
- **TCOA:** Training Center Organizer Advocate (no lugar de "Coordenador")

@khaosdoctor concordo com o @woliveiras nessa questão. A pessoa fez algo e mereceu a **badge**, creio que ficar depois analisando e monitorando isso seria muito burocrático, muito trabalho e algo que não seja totalmente necessário, pois a pessoa pode ter ajudado muito a comunidade por um período e decidido se afastar (seja por questões de falta de tempo, saúde, etc) e acho que não merece perder o seu "mérito" anterior.

**Comment by jaqueventurim** [comment]
>TCWA: Training Center Writer Advocate
>TCMA: Training Center Mentor Advocate
>TCPA: Training Center Promoter Advocate
>TCOA: Training Center Organizer Advocate

meu inglês infelizmente não é perfeito, então queria saber se esses títulos tem gênero neutro .-.

>A pessoa ganhou a badge e se ela continuar ajudando, show, senão continuar ela não perde o título.

concordo com esse ponto também

**Comment by WendellAdriel** [comment]
@jaqueventurim sim, escolhi esses até pelo fato de todos serem neutros com relação ao gênero!!! xD

**Comment by khaosdoctor** [comment]
> meu inglês infelizmente não é perfeito, então queria saber se esses títulos tem gênero neutro .-.

Tem sim @jaqueventurim, no ingles a maioria das palavras como Writer, Mentor, Promoter e Organizer não dependem de genero porque o que define o genero delas é o sujeito que vem em uma frase :smile:, por isso que eu amo essa lingua!

> @khaosdoctor concordo com o @woliveiras nessa questão. A pessoa fez algo e mereceu a badge, creio que ficar depois analisando e monitorando isso seria muito burocrático, muito trabalho e algo que não seja totalmente necessário, pois a pessoa pode ter ajudado muito a comunidade por um período e decidido se afastar (seja por questões de falta de tempo, saúde, etc) e acho que não merece perder o seu "mérito" anterior.

Não tinha pensado por este lado, concordo também.

> 
    TCWA: Training Center Writer Advocate
    TCMA: Training Center Mentor Advocate
    TCPA: Training Center Promoter Advocate
    TCOA: Training Center Organizer Advocate (no lugar de "Coordenador")

Muito bons os nomes, eu gostei bastante, poderíamos pedir a nosso time de designers para fazer uma badge né :D

**Comment by WendellAdriel** [comment]
Também amo o inglês por esse motivo e por muitos outros em que a gramática é muito mais simples que o português @khaosdoctor!!!

Sobre as badges, realmente seria muito interessante cada badge ter um design próprio!!! xD

**Comment by jaqueventurim** [comment]
acho show!
vocês tem referências de bagdes que acham legais?

**Comment by khaosdoctor** [comment]
Eu até tinha, mas formatei meu PC ai perdi tudo, eu acho que podemos fazer umas badges parecidas com a gamificação do StackOverflow mesmo, nada muito complicado nem muito intrincado.

Vou chamar o @adeonir aqui porque é quem eu conheço que está no time de design, eu realmente preciso me inteirar dos times do CT :(

**Comment by jaqueventurim** [comment]
eu também estou, por isso perguntei rs.

**Comment by khaosdoctor** [comment]
Ai ó T_T eu vou ficar quietinho hahaha

**Comment by WendellAdriel** [comment]
Então os nomes vão ficar aqueles mesmo???
E concordo com o @khaosdoctor, as badges tipo do StackOverflow seriam bem bacana!!!

**Comment by woliveiras** [comment]
Acho só o nome de organizer ou coordinator ruins porque se a pessoa está organizando algo, ela já tem o título de organizadora ou contributor.

Teríamos que pensar num título que parabeniza ela por ser excepcional.

O que acham?

Estou moscando? :joy:

**Comment by WendellAdriel** [comment]
Como eu disse eu não sou muito bom em nomes, mas vejo que a **diferença** de todas as badges acima é ser um **advocate**. No TC temos diversos mentores, mas só alguns serão um **Mentor Advocate**, assim como os outros.

Mas não é que eu esteja a defender o uso do nome organizer nem coordinator, eu é que não tive nada mais em mente 😂

**Comment by woliveiras** [comment]
Acho que ao invés de darmos nome assim, poderíamos copiar (de fato) o Google :joy: 

O que acham?

Lá é todo mundo GDE, porém quando você entra no site, pode procurar por uma pessoa que é GDE em x, y ou z:

Tecnologia

![selection_022](https://user-images.githubusercontent.com/4243601/35324724-bb0df7f4-00d8-11e8-9c33-23f4cdc05c4e.png)

Marketing

![selection_023](https://user-images.githubusercontent.com/4243601/35324735-c4263112-00d8-11e8-96d4-b29ad8a58978.png)

Design

![selection_024](https://user-images.githubusercontent.com/4243601/35324739-c91b6994-00d8-11e8-99e2-85b004a960cd.png)

Localização

![selection_025](https://user-images.githubusercontent.com/4243601/35324743-ce10eeb0-00d8-11e8-814b-8dce0e774d48.png)

Acho que isso da menos trabalho de definição do que nós criarmos nomes. O que acham?

**Comment by woliveiras** [comment]
A pessoa é TCA, mas se procurar por ela será como:

TCA na aba de mentoria
TCA na aba de writers
TCA na aba de open source commiter
etc

Não com esses nomes, porque eu só estou dando exemplos, ainda teria que entrar a definição :joy:

**Comment by WendellAdriel** [comment]
Outra coisa que queria ver com vocês é o seguinte ponto:

Quando falamos de **advocates** como "cargo" em uma empresa, o trabalho de um **developer advocate** é ser a voz dos devs junto à empresa e tecnologia.

O nosso programa de **advocacy** vai ser apenas para **reconhecimento** ou será também por exemplo um **Mentor Advocate** será tipo o porta-voz dos mentores no TC???

**Comment by WendellAdriel** [comment]
Eu concordo com o @woliveiras em utilizar um nome geral como **TCA - Training Center Advocate** e depois apenas separar por áreas, fica mais fácil e mais simples de gerir, pois se não teríamos que começar a criar diversos nomes ao passar do tempo como: TCDA (Training Center Design Advocate), etc.

**Comment by woliveiras** [comment]
> pois se não teríamos que começar a criar diversos nomes ao passar do tempo 

Exaaaato, mano!

> um Mentor Advocate será tipo o porta-voz dos mentores no TC???

Iiiiiisso! É exatamente essa a proposta, mano :raised_hands: 

A pessoa que ganha esse título vira referência nesse assunto, então, quando alguém tiver dúvida, por exemplo, do mentoria, então pode entra em contato com quem for TCA do mentoria.

Seria quem divulga o mentoria, quem fala sobre o mentoria e quem domina o assunto mentoria.

Assim como quem é GDE de web... São pessoas que falam sobre web pelo mundão. São referências em web.

**Comment by WendellAdriel** [comment]
Lindo @woliveiras!!!
Por mim fica definido assim apenas como TCA, falamos com o time de design pra criar uma badge monstra e começamos a definir quatro pontos:

- **Requisitos** para se tornar um **TCA**
- Pontos a serem analisados pela **Core Team** para dar o título de **TCA** a alguém
- Verificar quais pessoas já estão aptas para receber o título
- Divulgação do programa de **advocacy**

**Comment by WendellAdriel** [comment]
Então pessoal, o que devemos fazer para seguir para frente com a proposta???

**Comment by jaqueventurim** [comment]
Sobre o nome, ok **concordo**.

Mas sobre as badges, como ficaria isso? Uma pra cada área?

**Comment by WendellAdriel** [comment]
Creio que poderia ser apenas uma badge como **TCA - Training Center Advocate** mesmo.

**Comment by woliveiras** [comment]
Isso

A badge é uma só: TCA. Como GDE.

Mas na pesquisa no site onde vamos listar essas pessoas colocaremos filtros para dizer quem faz o que.

**Comment by woliveiras** [comment]
Acho que além desses:

> Requisitos para se tornar um TCA
>  Pontos a serem analisados pela Core Team para dar o título de TCA a alguém
> Verificar quais pessoas já estão aptas para receber o título
> Divulgação do programa de advocacy

Ainda estamos devendo as separações por áreas.

O que acham de: 

- **mentors**: pessoas que, além de fazer parte do mentoria, ensinam outras pessoas a serem mentoras, divulgam o mentoria e fazem onboarding de novos mentores e mentoras
- **writers**: pessoas que já escreveram ao menos 10 tutoriais para o nosso medium
- **speakers**: pessoas da nossa comunidade que aceitam palestrar divulgando nosso projeto
- **commiters**: pessoas que contribuem de maneira ativa em nossos repositórios
- **spreaders**: pessoas que divulgam nossa comunidade e projetos em suas comunidades ou iniciativas

**Comment by WendellAdriel** [comment]
Achei muito boa a separação proposta @woliveiras. Pensei em acrescentar mais duas separações, o que acham de:

- **TCA (Designer):** pessoas que ajudam sempre com os materiais do TC (criação de artes, layouts, definição de uso de cores, etc - pois não sei listar tudo que um designer faz 😅 , me desculpem designers)

- **TCA (Diversity):** pessoas que ajudam na inclusão de todo e qualquer grupo em atividades e eventos, ajudam na conscientização sobre assuntos relacionados, etc

**Comment by woliveiras** [comment]
CARAMBA!

Mandou foi muito bem nessas! :+1: :+1: :+1: :+1: :+1:

**Comment by khaosdoctor** [comment]
Gostei das divisões e dos nomes, ficaram muito bons mesmo. Vamos começar fazendo os designs das badges?

**Comment by khaosdoctor** [comment]
Gostei das divisões e dos nomes, ficaram muito bons mesmo. Vamos começar fazendo os designs das badges?

Destes pontos aqui:

- [X] Requisitos para se tornar um TCA
- [ ] Pontos a serem analisados pela Core Team para dar o título de TCA a alguém
- [ ] Verificar quais pessoas já estão aptas para receber o título
- [ ] Divulgação do programa de advocacy
- [ ] Confecção das badges

Acho que matamos o primeiro e adicionamos mais um

**Comment by WendellAdriel** [comment]
Um ponto que acho importante destacar no processo é que **ninguém se candidata** para ganhar o título de **TCA**, o `Core Team` juntamente com demais grupos que devem escolher e nomear as pessoas :wink:

**Comment by woliveiras** [comment]
Podemos usar um sistema de indicação, ao invés de candidatura.

O que acham?

Alguém do Staff ou Core indicam a pessoa e mostra os pontos pelos quais ela deve ser aceita como TCA.

Só teríamos que ter critérios muito bem definidos pra que não ocorra a brotheragem nas indicações. :joy:

**Comment by WendellAdriel** [comment]
Concordo @woliveiras!!!
Por isso agora creio que temos que ir pro segundo ponto da lista que o @khaosdoctor montou!!! 👍

**Comment by khaosdoctor** [comment]
Eu não sei se indicação só do Core ou staff... Eu acho que poderia ser que nem o Google mesmo, tipo, as pessoas que são TCA poderiam indicar outras para serem TCA, mas essas pessoas deveriam mostrar o porquê se encaixam como TCA's, então ela teria que fazer uma apresentação para o Core.

Ai a gente poderia ter mais gente indicando cada vez mais gente, mas teríamos um critério fixo para seguir

**Comment by WendellAdriel** [comment]
Por isso concordei com o esquema de indicações que o @woliveiras propôs @khaosdoctor

**Comment by WendellAdriel** [comment]
Se ampliarmos ele para outros TCAs poderem indicar fica melhor ainda

**Comment by woliveiras** [comment]
> Eu não sei se indicação só do Core ou staff... Eu acho que poderia ser que nem o Google mesmo, tipo, as pessoas que são TCA poderiam indicar outras para serem TCA, mas essas pessoas deveriam mostrar o porquê se encaixam como TCA's, então ela teria que fazer uma apresentação para o Core.

Sim, pô... Não seria indicação para entrar, mas para passar pela triagem. Senão fica, como falei acima, fácil acontecer a brotheragem e qualquer pessoa ir entrando porque pessoa x indicou :joy: 

> Só teríamos que ter critérios muito bem definidos pra que não ocorra a brotheragem nas indicações.(https://github.com/training-center/sobre/issues/67#issuecomment-360856970)

**Comment by woliveiras** [comment]
Se concordamos com o esquema de indicações, devemos pensar nos critérios da avaliação.

O que o time de avaliação teria que analisar?

**Comment by WendellAdriel** [comment]
Creio que além dos pontos mencionados aqui:
- https://github.com/training-center/sobre/issues/67#issuecomment-360788755
- https://github.com/training-center/sobre/issues/67#issuecomment-360794600

O time de avaliação deve avaliar:
- Se a pessoa é uma pessoa ativa na comunidade, ou seja, contribui/participa do TC pelo menos duas ou três vezes na semana (devemos definir um número), seja com perguntas, respostas, commits, etc.
- Avaliar a forma como a pessoa interage com outras pessoas na comunidade e fora da comunidade (nas redes sociais por exemplo), ou seja, se ela trata as pessoas com respeito, se a pessoa não discrimina nem posta coisas preconceituosas nas redes sociais, etc.

Até o momento esses foram os pontos que eu pensei...

**Comment by lbighetti** [comment]
Proponho pra áreas do __TCA__ adicionalmente a área de __youtube__ para criadores frequentes de conteúdo dessa plataforma ao invés de por exemplo o medium.

**Comment by woliveiras** [comment]
Opa! 

Verdade, @lbighetti 

Será que ao invés de writers, chamar de algo relacionado a conteúdo, tutorial, algo relacionado a compartilhar experiência?

**Comment by woliveiras** [comment]
Concordo, @WendellAdriel

**Comment by WendellAdriel** [comment]
Podemos usar algo tipo **TCA (Content Maker)** @woliveiras e @lbighetti

**Comment by lbighetti** [comment]
Boa, talvez __TCA (Content Creator)__ ?

**Comment by WendellAdriel** [comment]
Tanto faz @lbighetti, é o mesmo sentido mesmo ahhhaahahah, o que acharem melhor!!! 🙃 
Eu pensei nos dois mas coloquei só um porque tem o mesmo sentido 😂

**Comment by woliveiras** [comment]
Também acho os dois como títulos legais.

Só acho que **creator** é mais legal neste contexto porque quando falamos maker na cultura hacker é aquela pessoa que mexe com os arduinos da vida. (em maker spaces)

**Comment by WendellAdriel** [comment]
Fica decidido como **Content Creator** então!!!

Agora voltando ao assunto dos pontos a serem avaliados, mais alguém tem algo a acrescentar além do que foi definido aqui: https://github.com/training-center/sobre/issues/67#issuecomment-361286360 ???

Ou podemos colocar esse ponto como concluído e passar ao próximo ponto?
Acho que já seria interessante conversar com o time de design para já ir pensando nas badges não acham?

**Comment by woliveiras** [comment]
Acredito que podemos passar para os próximos pontos.

Depois vamos voltar nos requisitos só pra escrever um documento sobre como avaliar cada tópico, mas isso vai ser na hora da criação do projeto mesmo. :grimacing:

**Comment by WendellAdriel** [comment]
Qual dos pontos restantes devemos discutir primeiro???

- Verificação de pessoas aptas para o título 
- Divulgação do advocacy
- Confecção das badges

**Comment by woliveiras** [comment]
>  Verificar quais pessoas já estão aptas para receber o título

Acho que isso só deve ser discutido quando o programa começar a rodar, pois podemos desvirtuar a conversa. Ao invés de conversar sobre o projeto começar a executar ele sem nem ter ele implementado, saca? :joy:

**Comment by woliveiras** [comment]
Acho que podemos discutir sobre como implementar isso, pois tendo a implementação teremos como divulgar e até mesmo confeccionar essas badges 

Não sei se estamos indo muito pra frente com badges. Será que isso é realmente útil?

Só ter um local onde listamos as pessoas não é mais efetivo a curto prazo?

**Comment by woliveiras** [comment]
O que eu tenho em mente seria um site estático hospedado no GitHub onde listamos as pessoas que são TCA.

O que acham?

No GitHub porque outras pessoas podem contribuir com o site, podemos usar o projeto para ensinar pessoas, etc.

A hospedagem pode ser na Umbler, pois possuímos uma conta lá rodando uma aplicação em Express que serve nosso site: https://trainingcenter.io/

Poderia ser uma sub page: https://trainingcenter.io/tca

O que acham?

**Comment by WendellAdriel** [comment]
Eu apenas dei essas opções, pois foram as que estavam listadas aqui: https://github.com/training-center/sobre/issues/67#issuecomment-360806269 @woliveiras

**Comment by WendellAdriel** [comment]
Sobre o site, creio que um site estático no Github é o melhor caminho mesmo!!!
Sobre a hospedagem, pode ser na Umbler sem problemas algum e a página creio que poderia ser num subdomain: https://tca.trainingcenter.io

**Comment by WendellAdriel** [comment]
Sobre as badges, creio que pode ser algo para ser pensado/implementado mais pra frente mesmo!!! Devemos focar agora na implementação e definição formal de como vai funcionar para conseguirmos lançar uma versão "beta".

Sobre o site estático, já pensou em algum layout ou algo @woliveiras??? Posso iniciar/ajudar na criação do mesmo!!!

**Comment by woliveiras** [comment]
Ainda não, mano...

Acho que daí poderíamos ver com a equipe de @training-center/designers, pois o pessoal já está montando um layout novo até pro nosso site. \o/

**Comment by WendellAdriel** [comment]
Então sucesso!!!
Com isso já temos quase o nosso programa de **Advocacy** definido!!!
A única coisa que acho que precisamos definir é como vai ser feito a indicação.

Eu creio que pode ser feita através de um form simples:
- Nome da pessoa indicada
- Para qual das categorias de TCA quer indicar
- Explicação de porque está indicando a pessoa
- Redes sociais da pessoa indicada

**Comment by woliveiras** [comment]
@WendellAdriel acho que é só isso mesmo, mano :raised_hands: 

Até então temos a seguinte definição:

- um programa de reconhecimento do Training Center chamado TCA
- as pessoas são indicadas para o programa
- temos as seguintes áreas:
    - mentors
    - writers
    - speakers
    - commiters
    - spreaders
    - designers
    - diversity
- o Core Team analisa a indicação
- os dados que precisamos na indicação são:
    - nome da pessoa
    - categoria
    - porque a pessoa está sendo indicada
    - redes sociais da pessoa

Acho que as primeiras pessoas poderiam ser indicadas pela staff no Slack

Próximos passos:

- especificar bem detalhado cada título
- especificar o que o Core Team precisa conferir na indicação e nos perfis da pessoa indicada
- criação do site
- divulgação

A partir de agora podemos partir direto para este repositório: https://github.com/training-center/advocacy

Lá vamos discutir tudo e depois ele vai ser convertido para o site do programa TCA.
