### ISSUE TITLE
Coffee Break do Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#7]
Algumas pessoas da nossa comunidade moram próximas umas das outras e vivem falando de se encontrar pessoalmente.

Visando esse contato pessoal, poderíamos criar uma espécie de Meetup do TC. Chamei de Coffee Break do Training Center, porém podemos discutir o nome aqui.

Para que isso dê certo precisaremos de líderes regionais/locais para que esses encontros sejam organizados e nosso código de conduta seja seguido também nos encontros presenciais.

## Tópicos que devem ser discutidos nessa issue

- [ ] nome do meetup
- [ ] regras
- [ ] esquema de região (se fazemos por estado ou por cidades)
- [ ] como organizar os encontros

**Comment by woliveiras** [comment]
Para o esquema de organização dos encontros eu pensei em criarmos um repositório aqui no GitHub e usarmos issues para marcar os meetups.

Assim evitamos o uso de uma plataforma paga como o Meetup.com e podemos ver uma boa maneira de organizar tudo.

Inicialmente pensei em criarmos um template para criação dos encontros e termos labels sobre as regiões. Assim que o encontro acontecer, fechamos a issue.

Esse repositório ficaria na responsabilidade dos moderadores do Training Center em conjunto com os responsáveis pelos encontros locais.

**Comment by MarianoJhuninhu** [comment]
sobre as regiões acredito que pode ser um meio termo entre Cidade e Estado...

**Comment by ftonato** [comment]
**Sobre o nome:**  Coffee Break TC - {{ cidadeOrEstado }}

**Regras:** Não acho que seja necessário nada muito além de um [código de conduta](https://github.com/ftonato/meetup/blob/master/codigo-de-conduta.md).
Obviamente, dependendo do espaço onde será organizado, algumas regras serão adicionadas...

**Estados ou Cidades:** Acho que vai daquilo que é mais acessível aos interessados da região.

**Como organizar:**

1. Os responsáveis por cada região/local entram em contato com alguma empresa/instituição bacada da região que irá ceder o espaço.
2. Limita-se o número de participantes.
3. Defini-se a frequência dos encontros.

**Comment by khaosdoctor** [comment]
**O Nome**: Acho que Coffee Break TC que nem o @ftonato disse é bem legal (até porque podemos abreviar pra CBTC - {{local}}) e fica bem fácil de lembrar

**Regras**: O código de conduta já supre as regras... Além das regras do local mesmo

**Estados ou cidades**: Acho que poderia ser um esquema hierarquico, então você teria os líderes regionais, de cada cidade, e um comite por estado que teria autonomia para organizar esses meetups

**Organização:**

- Líder regional expressa vontade de organizar o meetup para o comite do estado (para não ter conflito de datas)
- Comite organiza as datas de todos os meetups no estado de forma que todos possam fazer meetups específicos sem interferencia de outros eventos
- É definido um tema (Pelo organizador do meetup)
- Definido o local (pelo organizador do meetup)
- Convites enviados

Só fiquei em dúvida mais ou menos sobre os temas desses meetups

**Comment by lflimeira** [comment]
Dando opinião, acho a ideia muito legal, e acho que um modelo mais "informal" como rodas de discussão ao invés de palestras seria um modelo mais agradável para o publico do TC (um publico que está iniciando na área) e tbm possibilita uma maior interação/aproximação entre o pessoal mais experiente e quem está começando.

Quanto a ideia do @woliveiras acho legal a maneira de organizar pelo github, mas seria legal ter outras formas de divulgação desses meetups, pois muitas pessoas que estão começando ainda não utilizam tanto o github ou as vezes não com tanta frequência. (Por ser novo por aqui, talvez já exista essas outras maneiras de divulgar, nesse caso, por favor ignorem kkk)

**Comment by khaosdoctor** [comment]
> Dando opinião, acho a ideia muito legal, e acho que um modelo mais "informal" como rodas de discussão ao invés de palestras seria um modelo mais agradável para o publico do TC (um publico que está iniciando na área) e tbm possibilita uma maior interação/aproximação entre o pessoal mais experiente e quem está começando.

Acho que isso é necessário, tem que ser algo informal, não pode ser formal.

> Quanto a ideia do @woliveiras acho legal a maneira de organizar pelo github, mas seria legal ter outras formas de divulgação desses meetups, pois muitas pessoas que estão começando ainda não utilizam tanto o github ou as vezes não com tanta frequência. (Por ser novo por aqui, talvez já exista essas outras maneiras de divulgar, nesse caso, por favor ignorem kkk)

Acho que a divulgação por um site próprio (o próprio site do TC) ou blog, além dos slacks e grupos seria bacana.

---

Muito antigamente (uns 4 anos atrás) eu editava alguns podcasts de amigos então se precisarem eu posso ver de editar o audio se for necessário viu @woliveiras.

**Comment by woliveiras** [comment]
Galera, essa issue pode ser fechada visto que estamos organizando meetups locais onde temos issues para cada região.
