### ISSUE TITLE
Grupo de estudos MongoDB

### ISSUE THREAD

**Issue by WendellAdriel** [training-center/sobre#7]
Formação de grupo para estudar MongoDB

**Comment by Z4yon** [comment]
To nessa o/

**Comment by VictorVoid** [comment]
Vamos nessa!! Também estou

**Comment by clarabatt** [comment]
Eu :raising_hand:

**Comment by WendellAdriel** [comment]
Opa, ta quase dando 5 pessoas pra gente começar a discutir as paradas galera!!! :wink:

**Comment by clarabatt** [comment]
Como vamos fazer? Podemos usar o slack pra discutir e depois criar um repositório pra algum projeto, o que acham?

**Comment by WendellAdriel** [comment]
@clarabatt Isso mesmo que estou pensando, vou falar com o mano @woliveiras pra ver se ele cria um canal do Slack pro CT e divide os grupos em channels!!! :wink: e depois vamos começar com alguns exercícios e um projeto pra gente aprender!!!! :wink:

**Comment by WendellAdriel** [comment]
Galera, o @woliveiras vai criar uma Team no Slack e criar um channel pra cada grupo, aí deixaremos de utilizar essa issue igual um fórum ashusahushuahusa e vamos passar a utilizar o channel no Slack como principal meio de comunicação do grupo oks?!?!?!?!

**Comment by LarissaAbreu** [comment]
Eeeeu xD :grin:

**Comment by WendellAdriel** [comment]
Uuurrrruuullll, fechamos os 5 agora!!!! :wink:

**Comment by woliveiras** [comment]
Lembrando que tem de criar um nome pro Grupo pra separar em uma issue aqui e nos canais lá ein... :)

**Comment by WendellAdriel** [comment]
Oks oks @woliveiras

**Comment by woliveiras** [comment]
Ta lá galera! https://ctgroups.herokuapp.com/

**Comment by WendellAdriel** [comment]
Beleza, já dá pra fechar um grupo aqui!!!! :wink:

**Comment by WendellAdriel** [comment]
@Z4yon, @VictorVoid @clarabatt e @LarissaAbreu o nosso grupo de MongoDB é esse: #19

**Comment by WendellAdriel** [comment]
@Z4yon, @VictorVoid @clarabatt e @LarissaAbreu se vocês não tiverem entrado no Slack, coloca o email aqui pra eu adicionar vocês lá.

**Comment by clarabatt** [comment]
clarabattesini@gmail.com
