### ISSUE TITLE
Projeto de experiência de mercado (ainda sem nome)

### ISSUE THREAD

**Issue by Rachc** [training-center/sobre#71]
# Idéia de Projeto - Experiência de mercado
Olá Devas e Devs (:

Vim aqui sugerir um projeto pra tocarmos aqui no Training Center que visa oferecer experiência de mercado para quem não possui, e experiência de gestão de pessoas para pessoas desenvolvedoras mais pleno ou senior.
A idéia é criar projetos e formar equipes para fazer esse projeto acontecer.

Inicialmente os projetos seriam criado por nós, e caso dê certo, a idéia é de pegar projetos de ongs, ou receber sugestões de projetos open sources para fazer/contribuir.
No ultimo caso, a própria pessoa dona do projeto poderia ser a pessoa que coordena a sua equipe.

O projeto seria submetido ao TC e nós escolheriamos as melhores propostas para aceitação de curriculo.

A idéia é que o projeto seja feito em sprints, com scrum e/ou kanban, pois é o que o mercado costuma a usar, e é uma experiência importante a ser adquirida.

O TC funcionaria como a empresa. nós do TC seriamos uma especie de RH/Diretoria, e cada projeto teria o seu gerente de projeto.

Os projetos criados seriam todos Open Sources, hospedados no git, e a autoria deles seria atribuida ao coordenador do projeto.

Precisariamos também pedir para cada participante do projeto se comprometer com uma carga horária (minima de 5h/semana e máxima de 20h/semana)

### Critérios de seleção de curriculo
- Idealmente escolheriamos pessoas sem experiência de trabalho mas que já fizeram cursos na área. Caso a pessoa não possua experiência de trabalho **E** seja parte de um grupo de minoria, ela teria prioridade.
- É preciso que a pessoa já saiba lógica de programação, e tenha começado e terminado algum curso referente ao que o projeto pede (sejam cursos livres tipo udemy ou técnico/superior).
- É possivel também que pessoas desenvolvedoras mais experientes se candidatarem ao projeto. Nesse caso a prioridade são pessoas que querem usar a linguagem/tecnologia utilizada no projeto mas não possuem essa experiencia.
- A ordem de prioridade na seleção é: Minorias que não tem experiência de trabalho > Demais pessoas que não possuem experiência de trabalho > Pessoas que possuem experiencia mas não utilizaram aquela tecnologia > Pessoas com experiência na área e experiência nas tecnologias utilizadas
- Inicialmente os curriculos serão enviados através de formulários no TC.

## Critérios de seleção de projeto
- A solicitação de projeto será feita através de um formulário a ser disponibilizado pelo TC. Perguntaremos sobre experiencia prévia na área e com as linguagens utilizadas pela coordenação, bem como algumas perguntas sobre ferramentas e padrões de organização do projeto
- O projeto deve ser sem fins lucrativos, e a preferencia será para aqueles que gerarem impacto positivo na sociedade/comunidade.
- Caso haja demanda de projetos, a preferencia é para aqueles que usem linguagens mais comuns no mercado.

### Criação de projetos
- [ ] Pessoa tem uma idéia de projeto
- [ ] Pessoa envia a idéia pro training center
- [ ] Sendo aprovada, a organização do TC vai, junto com a pessoa, tentar levantar as necessidades de pessoas/papeis no projeto
- [ ] O TC vai pedir curriculos
- [ ] Junto com a organização do projeto, o TC vai selecionar curriculos

### Andamento do projeto
- [ ] A coordenção do projeto vai fazer o seu planejamento e criar as tasks.
- [ ] A coordenção do projeto vai definir o que vai na sprint - 10 dias uteis.
- [ ] A coordenção vai definir junto a equipe a pontuação de cada sprint em uma reunião de planejamento.
- [ ] Durante a sprint, as pessoas vão precisar deixar o resumo diárioa de atividades no grupo de trabalho (uma espécie de daily)
- [ ] Ao final de cada task, será exigido que a equipe faça code review (fica a cargo da equipe definir quantas aprovações são necessárias para aprovação do projeto)
- [ ] Ao final da sprint, o ideal é ter uma reunião de planejamento da próxima, que as pessoas falarão suas opiniões sobre a sprint passada e o que pode ser melhorado. Para que isso ande melhor, é importante abraçar a idéia que nem todo mundo vai conseguir estar presente, mas ela devera ser feita no melhor horário para a maioria.

### Toda a equipe
- [ ] Se comprometer com a carga horária definida no começo do projeto (5h/semana minimo e 20h/semana maximo)
- [ ] Enviar um resumo das tarefas do dia e do planejamento do próximo para o grupo
- [ ] Avisar qualquer imprevisto no grupo
- [ ] Fazer code review.
- [ ] No caso de precisar sair do projeto, avisar com pelo menos 1 semana de antecedencia

### Responsabilidades específicas do Coordenador do projeto
- [ ] Definir os tickets do projeto
- [ ] tirar dúvidas a respeito do projeto
- [ ] Fazer code review **em todos os PR**
- [ ] O tempo de aviso para sair do projeto sobe de 1 semana pra 15 dias
- [ ] Auxiliar os colaboradores na elaboração do curriculo, junto com o TC, ao final do projeto.
- [ ] Passar para o TC as regras extras de cada projeto (ex: commits apenas em inglês, padrão de código seguido, ferramentas utilizadas)

### Responsabilidades do TC
 - [ ] Escolher os projetos que participarão desse esquema
 - [ ] Dar suporte mínimo para a pessoa que está coordenando o projeto
 - [ ] Sugerir ferramentas para que o projeto ande
 - [ ] Ouvir reclamações, seja da coordenação ou da equipe
 - [ ] Caso solicitado, fornecer um certificado de participação do projeto

## Critérios de desligamento do projeto:
- [ ] Não cumprimento do COD do TC.
- [ ] Não cumprometimento com as horas minimas exigidas
- [ ] Não cumprimento das responsabilidades exigidas

O desligamento deve ocorrer apenas com a aprovação do TC

## Algumas outras regras
 - O projeto será desenvolvido no github do TC e, ao final do projeto, passariamos para o github da pessoa coordenadora do projeto (caso seja esse o caso).
 - Em cada grupo do slack terá uma pessoa do TC, embora ela não tenha obrigação de ajudar no desenvolvimento do projeto.
 - No começo de cada projeto será feito um grupo privado no slack do TC para comunicação das equipes

**Comment by adrianoavelino** [comment]
Ótima ideia, achei muito interessante isso e é um projeto bem grande e complexo. Não sei se é o objetivo, mas tem algum projeto do training center sobre entrevistas e tal, e não como está o andamento desse projeto. Seria interessante esse projeto ser integrado nesse  projeto (experiência de mercado)?

**Comment by alinebastos** [comment]
O outro projeto é o hiring center. O pessoal acabou ficando ocupado com outras coisas, mas vai sair.
Não seria interessante integrar os dois pq este é só para estágio mesmo, pra quem não tem experiência, o outro é pra qualquer nivel, só pra praticar entrevistas mesmo. Ficaria muito complexo integrando, precisaria de mais pessoas em um projeto só.

**Comment by khaosdoctor** [comment]
Essa ideia parece ser uma versão mais especificada desses dois projetos #22 #25.

Eu gostei bastante da ideia, o problema é encontrar pessoas que tocariam esta iniciativa constantemente. Um bom projeto de inicio seria a plataforma para o mentoria, que chegou a começar mas não sei como estão os avanços nessa parte.

Acho que podemos fazer um compilado de todas as ideias e juntar tudo em uma issue só para, ao invés de ter vários projetos diferentes que diferem em poucas coisas, como o Hiring Center que a Aline disse, e essas duas issues, tenhamos um único projeto mais abrangente.

**Comment by leonardovilarinho** [comment]
Muito legal a ideia, sobre os pontos de dúvidas, acho que teríamos de ter uma organização própria no github para ter os repositórios, por exemplo tc-projects.

O canal poderia ser no Slack do TC, porém privado para os membros do projeto, e sobre currículo seria melhor fazer um formulário perguntando as coisas para a pessoa. 

O ponto que temos de  ficar mais atentos seria o comprometimento, para que não seja mais um daqueles projetos abertos  que são deixados pelos devs.

Por fim, uma coisa que não curto muito é que às vezes esses projetos ficam limitados apenas para pessoas que tem estruturas para participar, com máquina potente, comunicação por vídeo, etc.

Seria legal também fazer contato com algumas empresas pra ver se rola uma pareceria de realizar projetos para elas, mesmo que código aberto, ou então se topam ficarem olhando  para quem sabe encontrar profissionais.

Parabéns pela ideia, adoraria participar, se precisarem de qualquer ajuda contém comigo!

**Comment by luizbills** [comment]
Meu receio também é dos projetos iniciarem e serem largados pelos responsáveis. Para isso acredito que deveriamos limitar as tecnologias dos projetos para apenas as tecnologias que são mais utilizadas (React, WordPress, Rails ect) e **obrigar** a seguir a risca os requesitos do projeto (pois é assim que funciona no mercado). Sugiro assim para evitar que chegue pessoas querendo usar alguma tecnologia *muito nova/pouco utilizada/"modinha"*. Até para evitar que o povo sem experiência perca tempo estudando/praticando algo que ele não vai utilizar provavelmente.

Sobre os projetos, acho que nós do CT deveriamos criar apenas o *briefing* dos projetos listando coisas como:

- descrição completa do produto final.
- minimo de número de pessoas necessárias.
- tecnologias permitidas.
- links da documentação e artigos que possam ajudar no projeto. 

Acredito também que seria legal dividir os projetos em tipos como: **simples, intermediário e complexo.**

Assim pessoas do CT se uniriam para formar um grupo, pegariam um projeto, procurariam um dev(a) experiente para coordenar a equipe deles e desenvolveriam um produto final. Esse produto final seria liberado como open-source pelos desenvolvedores no perfil de um dos colaboradores, listando o nome de todos aqueles que colaboraram. Ou podiamos criar uma org do CT só para publicar esses projetos informando os responsáveis pelo projeto.

Sobre o coordenador penso que poderia ser qualquer no CT que diga ter experiência comprovada, apenas uma pessoa para ficar de olho e ver se o projeto está andando. E em caso de alguma dificuldade da equipe ou desânimo, o coordenador estaria lá para ajudar nesses obstáculos. Seria legal também o coordenador fazer um mini-relatório ao final, dando seu feedback do produto final e da equipe.

**Comment by Rachc** [comment]
@khaosdoctor Acho que o problema de juntar esses projetos todos em uma issue só é que pra gerenciar tudo é meio tenso.  
Acho que poderiamos talvez interligar uma coisa com a outra, pedir pra equipe que está organizando o treinamento de entrevista nos dar uma mão na hora de entrevistar os candidatos

@leonardovilarinho Gosto da idéia de ter um github próprio. Se a idéia realmente for pra frente, o github do TC vai ficar só cheio das coisas 

@luizbills O que eu penso é que o TC seria o intermediário entre alguém com idéia de projeto, e pessoas que não possuem experiencia de estágio
Quase um RH.

Acho que parar pra pensar nas tecnologias utilizadas, e priorizar as mais usadas no mercado é um bom ponto a se pensar, e talvez valha a pena pensar em priorizar essas linguagens na hora de escolher um projeto?
porém acho que se tiver gente interessada em usar linguagens algumas linguagens "da moda" (Alô elixir) e gente interessada em trabalhar com isso, why not?

O primeiro projeto de teste provavelmente vai ter que ser tocado por nós,
mas a idéia é atrair alguém mais senior ou pleno com vontade de aprender sobre gerenciamento de pessoas, com alguma boa idéia de projeto pra tocar isso.
É bem trabalhoso, mas não tanto quanto parece. O projeto não precisa ser nosso (do TC) (:

**Comment by lbighetti** [comment]
Qual o valor de encontrar problemas, dificuldades e possíveis falhas na idéia dela ?
No que ajuda apontar porque não vai dar certo ?

Os comentários negativos não são úteis.

@Rachc Sua idéia é incrível.
Se der certo, você vai ajudar muita gente que precisa muito dessa ajuda.
Se der errado, você vai ter ganhado muita experiência e ter feito conexões valiosas.

Eu sugiro você fechar esse issue e iniciar o projeto.

**Comment by alinebastos** [comment]
@lbighetti assino embaixo <3

**Comment by passocacornio** [comment]
\o/ Vamo colocar esse projeto funcionando, porque tá cheio de gente boa aqui no CT que tá desempregada por motivos bem estranhos!

**Comment by alinebastos** [comment]
Não é pq outros projetos ficaram parados que esse não pode acontecer. Os outros projetos foram ideias de outras pessoas, que provavelmente tiveram problemas pessoais, coisas da vida, e podem voltar ou não. E misturar projetos só dificulta esse de acontecer.
Sugiro usarmos esta issue pra criamos um nome bem legal, criamos um repositório e mandamos brasa no projeto \o/

**Comment by jorginhodev** [comment]
Acho a ideia sensacional.
Inclusive eu poderia ser um dos beneficiados por ela, pois estou nessa lista aí - dos desempregados e dos que querem ingressar na área - e posso ajudar no que for possível.
Vou sugerir um nome, já que ninguém sugeriu ainda hehehe.
**firstep** - seria uma abreviação de first step (primeiro passo)

**Comment by jtlimo** [comment]
Adorei a ideia, e no que puder ajudar pra tocar o projeto tamos aew \o/

**Comment by silvamateus** [comment]
\o/ Vamo colocar esse projeto funcionando, porque tá cheio de gente boa aqui no CT que tá desempregada por motivos bem estranhos!

**Comment by gabbianiiii** [comment]
Eu adorei essa ideia. Ela vai acabar trazendo níveis de experiências muito boas para todos os envolvidos. Também voto para o encerramento desta issue, pois ao meu ver as idéias aqui colocadas estão bastante completas e se for o caso reabre-se este como uma atualização.

**Comment by Rachc** [comment]
Fiz atualizações no documento.
Quem tiver interesse em ajudar a tocar o projeto, é só me achar no slack (: como `rachc`
Fechando a issue agora
