### ISSUE TITLE
Utilizar mais o nosso canal no YouTube

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#72]
Nós temos um canal, da comunidade, no YouTube e estamos planejando como ativar mais as coisas por lá.

[Nosso canal](https://www.youtube.com/c/TrainingCenterChannel).

## Objetivo dessa issue

Documentar o que estamos planejando para nossos vídeos e os próximos passos.

## O que já temos

Inicialmente pensamos em:

- cobrir os eventos que formos
- voltar a fazer nossas lives
- fazer mais séries de vídeos para iniciantes

Já tem, também, a iniciativa do meetup online que já está rodando.

## O que precisamos

Precisamos de uma documentação para servir de guia para quem deseja enviar conteúdo para o nosso canal.

**O que abordar nessa documentação**

- softwares para gravação
- dicas de gravação
- dicas de edição
- formato de output do vídeo

## Outros detalhes

Precisamos de uma imagem padrão para utilizarmos como capa dos vídeos para que as pessoas utilizem em seu conteúdo.

Precisaremos de uma capa para:

- vídeos de meetups
- lives
- séries

**Comment by rafaels88** [comment]
Eu confesso que me sinto um pouco perdido sobre qual tipo de conteúdo contribuir. Sei que as diretrizes dizem que seriam vídeos para iniciantes, mas isso ainda é muito abrangente na minha mente. Que tal se a gente tivesse umas sugestões iniciais (pra qualquer um pegar e fazer) e a gente começar a ter um caminho mais explícito do que queremos pros próximos vídeos? Faz sentido?

**Comment by woliveiras** [comment]
Acho interessante, @rafaels88.

Qualquer coisa que ajude as pessoas a entenderem nosso propósito com o canal e que guie elas, é ótimo.

**Comment by rafaels88** [comment]
A gente já usa o Trello de conteúdo (Medium) pra vídeos do Youtube? Se não, acha que faz sentido usá-lo?

**Comment by lbighetti** [comment]
@rafaels88 eu concordo mano
Acho que um planejamento de próximos tópicos e também uma agenda com datas dos próximos vídeos são ótimos próximos passos.

Sugeri pro @woliveiras criarmos um repo dedicado pra isso, porque acho que tem complexidade e conteúdo suficiente pra isso.
Dai podemos usar issues pra gerenciar os pedidos de conteúdo.

Atualmente tá lá também, mas eu pessoalmente acho confuso misturar conteúdo escrito com vídeo. Pra mim o workflow e o foco de cada é bem diferente.

Acho que é legal ter a visão isolada do youtube do medium, pra por exemplo termos uma frequência constante lançando vídeos no YouTube.

O que acham ?

**Comment by rafaels88** [comment]
Acho ótima a ideia! E se não der certo a gente muda pra outra, o negócio é começar.

**Comment by woliveiras** [comment]
A ideia era que sim, mano... Mas a galera não abraçou a ideia dele pra conteúdo em vídeo e continuou usando só pra texto. :joy:

**Comment by rafaels88** [comment]
Bem, bora criar a repo então, ou ela já existe e não tá sendo usada?

**Comment by woliveiras** [comment]
Opa! Acabamos de começar a ideia!

ihIAHIHAIHAI

Podemos vir pra cá conversar sobre conteúdo então, mano: https://github.com/training-center/channel/issues/1

**Comment by khaosdoctor** [comment]
Eu acho que todo o conteúdo dessa issue pode ir pro training-center/channel, ai fechamos aqui e colocamos só a referência
