### ISSUE TITLE
Chamada para reorganização do Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/sobre#74]
Olá, pessoal!

Eu removi os times do Training Center com qualquer poder administrativo em nossos repositórios pois temos alguns problemas:

- pessoas ficam inativas por muito tempo, não se atualizam com as novas regras e podem errar em algo
- pessoas somem e não avisam se desejam continuar contribuindo

Seria muito mais complicado entrar em contato com cada pessoa, afinal temos muitos membros na comunidade e também aqui no GitHub.

![selection_110](https://user-images.githubusercontent.com/4243601/41387644-63f003fa-6f5e-11e8-8fe4-3d9771c1033a.png)

Precisamos fazer essa reorganização para:

- reativar nossa comunicação para voltarmos a dar mais atenção aos nossos projetos
- termos pessoas realmente ativas no grupo (ou pelo menos pessoas que comunicam quando precisam se ausentar por algum motivo)

Eu sei de algumas pessoas que são ativas, mas não queria ficar atrás de cada um senão seria um trabalho malígno!

Se você deseja continuar contribuindo com a comunidade, por favor, responda essa issue e diga onde você participa seja no slack (moderação), mentoria, grupos de estudos, Medium, YouTube ou meetups.

Ex.:

```
Will, eu quero continuar contribuindo no YouTube
```

Ou:

```
Will, quero continuar ajudando a manter o Mentoria
```

Também serão removidos projetos que precisam de constante interação, mas que não foram pra frente, como o [spreading code](https://github.com/training-center/spreading-code).

Essa reorganização é muito importante para a comunidade, apesar de ser algo "dolorido" e trabalhoso, pois estamos muito jogados as traças. Precisamos nos unir novamente e fazer nossas iniciativas darem certo! \o/

**SOMENTE QUEM RESPONDER ESSA ISSUE CONTINUARÁ COM PODERES ADMINISTRATIVOS NO TRAINING CENTER**

**Comment by Diego-Brocanelli** [comment]
Will, eu quero continuar contribuindo e ajudando no Slack, Github e grupo de estudos.

**Comment by anegrelli** [comment]
André, gostaria de poder contribuir mais no Mentoria porém dentro da minha área de conhecimento. Ou em alguma área que não envolva somente linha de código...

**Comment by liviagabos** [comment]
Will, eu quero continuar contribuindo no Github, mentoria, medium, youtube e grupos de estudo.
Eu não estou nos grupos de estudo, mas estou conversando com o Roberto Achar sobre umas ideias de contribuição na comunidade.

**Comment by alinebastos** [comment]
Quero continuar na moderação do slack, na organização do Meetup de Poa, escrevendo no Medium, ajudando no Youtube e no GitHub.

**Comment by gustavocardoso** [comment]
Will, quero continuar ajudando na moderação doe Slack e aonde mais eu puder contrubuir!

:*

**Comment by larien** [comment]
Ainda não comecei, mas quero continuar no Medium e na mentoria. AOGHAODJSGHS

**Comment by vinidf** [comment]
Quero continuar ajudando na organização do Meetup de BH!

**Comment by guilhermeoa07** [comment]
Will, eu quero continuar contribuindo e ajudando no Slack e grupo de estudos

**Comment by imbrn** [comment]
Will, eu ainda não ajudo, mas gostaria de poder ajudar na moderação slack, grupos de estudos, mentoria e o que mais precisar.

**Comment by mibsbalsante** [comment]
Quero continuar contribuindo com o Slack (mesmo sem os poderes de adm) e se possível, levantar uns meetups aqui em Floripa. Ao que forem surgindo mais coisas que eu possa fazer e tempo, posso tentar ajudar.

**Comment by lasombra** [comment]
Quero continuar contribuindo para o Mentoria

**Comment by ohgosch** [comment]
Will, quero continuar ajudando a manter o Slack, Meetup de Poa e GitHub.

**Comment by mahenrique94** [comment]
Will, eu quero continuar ajudando no Medium e mentoria, ainda não ajudo, mas gostaria e poderia ajudar também em grupo de estudos e youtube.

**Comment by rafaels88** [comment]
Will, quero continuar ajudando no Slack (moderação) e começar a ajudar no Github e Medium.

Ps.: sou seu fã!

**Comment by matepaiva** [comment]
Will, atualmente ajudo a organizar um meetup, e gostaria de ajudar com mentoria.

**Comment by adeonir** [comment]
Ae Will, quero continuar ajudando no Slack, no Meetup de Poa, no Github e talvez começar a escrever no Medium.

**Comment by lbighetti** [comment]
@woliveiras Wallace, quero continuar no admin do Slack e do YouTube.

**Comment by khaosdoctor** [comment]
@woliveiras Quero continuar como editor do Medium e no TCTalks SP

**Comment by viniciusalonso** [comment]
Will, quero continuar contribuindo no Medium, no slack, no github e como mentor.

**Comment by geanfelipe** [comment]
Quero continuar contribuindo para a Mentoria

**Comment by kivervinicius** [comment]
Quero continuar contribuindo para a Mentoria e iniciar como editor do Medium

**Comment by AlexsandroSA** [comment]
Will, eu quero continuar contribuindo e ajudando no Slack, grupo de estudos e em breve escrevendo no Medium.

**Comment by FelipeSGAndrade** [comment]
Will, eu quero continuar ajudando no Meetup de Poa

**Comment by WendellAdriel** [comment]
@woliveiras eu vou continuar ajudando com o Meetup do TC aqui em Lisboa, mas quero ajudar com mais alguma coisa, o problema como eu disse é que não uso mais o Slack do TC porque não consigo lidar com o grande fluxo de mensagens. Estou tentando lidar com problemas de ansiedade e stress, então ficou inviável para mim acompanhar o Slack, peço desculpas desde já por isso, mas se tiver algo que eu possa ajudar, estou aqui pra isso!!! xD

**Comment by Marcelosilva10** [comment]
Eu quero tbm contribuir.

**Comment by diemoritat** [comment]
Quero continuar contribuindo na moderação do slack

**Comment by woliveiras** [comment]
Show de bola, galera!

Obrigado pela participação de todos. :heart: 

Eu reformulei os times no GitHub.

Só deixei nos times a galera que trata da administração dos projetos e moderação. As demais pessoas são `outside collaborators` e podem pedir permissão de acesso a algo se forem ajudar ativamente.

Alguns times, como os de editores, não estão "aceitando" novos membros por estarem funcionando bem e se colocar mais gente seria meio que deixar alguém sem trampo por lá.

Quem foi removido da organização, mas participa **ativamente** de alguma iniciativa, me avisa no privado, no Telegram (`@woliveiras`) que adiciono no time de novo.

Os times são:

- mentoria: time que cuida do projeto mentoria, mentores são colaboradores `outside`, quem quiser ajudar ativamente no mentoria precisa pedir permissão de acesso (uma issue direto no repo)
- editors: editores(as) do Medium
- meetups: pessoas que organizam meetups do TC
- accessibility: time que cuida de acessibilidade na nossa comunidade
- moderation: time de moderadores(as) da comunidade
- study-groups: time que cuida do projeto study-groups
- design: time que cuida das nossas artes <3
