### ISSUE TITLE
Usar o docz para o site

### ISSUE THREAD

**Issue by nicholasess** [training-center/sobre#76]
Olá galera!
Percebi que o docz se encaixaria bem com a estrutura do site, com as issues abertas vocês podem criar Tópicos e sub-tópicos para organizar as informações do melhor jeito.

Que tal?

Ajudo vocês no que precisar :) @woliveiras @alinebastos

**Comment by woliveiras** [comment]
Acho maneiro a ideia, mano!

Principalmente por ser um projeto que nasceu de um BR.

Mas, no caso, eu não estou mais cuidando do TC. Teria que ver com a galera que está ativa, viu. ❤️

**Comment by nicholasess** [comment]
@lucasjs O que acha ?
