### ISSUE TITLE
Criar um issue template para o repositório

### ISSUE THREAD

**Issue by teles** [training-center/sobre#8]
Criar um issue template para o repositório

1. [x]  discutir se faz sentido ter um issue template
2. [x]  montar o issue template com a estrutura necessária

[Material do github sobre templates para issue](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by woliveiras** [comment]
Vale a pena a criação do issue template pra galera que for abrir grupos depois mano.

Se cada grupo tiver 5 pessoas, então virão outros grupos rapidamente. :)

**Comment by woliveiras** [comment]
@abc-dev

**Comment by teles** [comment]
O que a galera do @abc-dev, acha? :P

**Comment by woliveiras** [comment]
Feito em: [6ee5935](https://github.com/training-center/sobre/commit/6ee5935e7ce3b4ec0385b9e428d1bab4dbaf271e)
